### ISSUE TITLE
Save file(s) before starting build

### ISSUE THREAD

**Issue by biffen** [noseglid/atom-build#10]
It would be nice if atom-build could save files before building.

I imagine something like the following in the package's settings:
- Save files before building (yes/no)
- Save (option)
  - all files
  - all files within the current project's file tree
  - just the current file
- Ask before saving (yes/no)

**Comment by nudefireninja** [comment]
Would it be good to have an option to disable the popup? I.e. don't build with unsaved files (even when build on save is enabled).
