### ISSUE TITLE
[Feature Request] Build error display

### ISSUE THREAD

**Issue by forivall** [noseglid/atom-build#101]
It would be nice to have a nicer looking display of the build errors encountered. An error message would be added to the regex  (like `^(?<file>[^\\.]+.c):(?<line>\\d+):(?<col>\\d+):\s*(?<message>)`, and then it would be displayed in a list view, alongside a display of the filename and location of the error. The error can then be clicked to navigate to the location of the build error.

For example, here's what Qt Creator does:
![screenshot](http://i.imgur.com/xpX4Awt.png)

**Comment by jhasse** [comment]
I'm actually against this feature. I would rather see better color support in outputs of compilers, so that one can easily spot the errors in the build output.

Also when double clicking on the errors it should jump to the location. Like Sublime Text's build system support.

With these fixes I don't think a list view for errors is necessary.

**Comment by forivall** [comment]
Well, most compilers output way more information than just the errors, and color is usually disabled when the output is sent to something other than a tty. IMO, writing a formatter like this would be easier than faking a tty.

However, if you're dead set against it, I would encourage you to expose some way to create plugins for this, like what autocomplete-plus, linter and minimap do.

**Comment by jhasse** [comment]
Just to be clear: I'm not a developer of atom-build, so this could still be implemented ;)

Regarding color being disabled: I'm trying to fix that situation by having compilers respect the `CLICOLOR_FORCE` environment variable, see http://bixense.com/clicolors/. But I guess it will take a LONG time before a significant number of programs do.

**Comment by noseglid** [comment]
I like the idea of having a list of all the matched errors and being able to quickly switch between them (by mouse, or neatly assigned key commands). This doesn't really extend the capabilities of atom-build, but only facilitates the usage of error matching.

Improved color support from build systems is of course nice, and doesn't really affect this feature request, IMO.

**Comment by oli-obk** [comment]
how about forwarding all matched errors to the linter-package instead of having a list? Then you also get a list (provided by the linter package and friends), and highlighting of the errors in source.

**Comment by noseglid** [comment]
Using AtomLinter is probably not a bad idea. A PR is already open for this in #117

**Comment by noseglid** [comment]
The linter integration is on its way. Ill keep tracking this in #251 .
