### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by sloc2003** [noseglid/atom-build#104]
First off, great job on this package so far.  This thing is pretty awesome.  I'm not very skilled in these things so far, but I've noticed some change in the behavior very recently

This error is thrown when I try to build:
>Ooops. Something went wrong.
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at f (path.js:178:13)
    at Object.filter (native)
    at Object.win32.join (path.js:183:38)
    at Object.module.exports.isEligable (C:\Users\BaSiK-i5\.atom\packages\build\lib\tools\atom-build.js:10:29)
    at C:\Users\BaSiK-i5\.atom\packages\build\lib\build.js:180:23
    at arrayFilter (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1409:13)
>    at Function.filter (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:6289:14)
>    at Object.<anonymous> (C:\Users\BaSiK-i5\.atom\packages\build\lib\build.js:179:18)
>    at Object.tryCatcher (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\util.js:24:31)
>    at Promise._settlePromiseFromHandler (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:454:31)
>    at Promise._settlePromiseAt (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:182:16)
    at Async._drainQueues (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:192:10)
    at MutationObserver.Async.drainQueues (C:\Users\BaSiK-i5\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:15:14)

Here's what I have in the .json file:
>{
  "cmd": "W:\\handmade\\code\\build-atom.bat",
  "args":[],
  "sh": false,
  "env": {},
  "errorMatch": "(?\<file>.+)\\((?\<line>\\d+)\\)"
}

My bet is that I'm doing something wrong - I have a lay-mans understanding of Regex (read: noob), so I removed it to see if it reacted the same way.  It does.

After my build attempts threw this error a couple times, I went to check the .json file to see if I had accidentally deleted something, and after I checked that it was fine, I tried to compile again.  **It worked!**

I've confirmed that this behavior persists - trying to run build fails until I open the .json file and compile from there.

I realize that a lot of what's in that error is found elsewhere, but hopefully you can point me in the right direction.  Thanks for the help.

**Comment by noseglid** [comment]
Thanks for the praise, and thanks for taking the time to provide such a detailed description!

Hmm, could it be that you don't have a project opened? I believe [this function](https://github.com/noseglid/atom-build/blob/master/lib/build.js#L136-L148) is the reason it doesn't work and most likely because `atom.project.getPaths()` return an empty array. This is definitely a bug in atom-build which I will address (with improved error handling).

However, if you have no active file, and no active project - what do you expect to build?

**Comment by sloc2003** [comment]
I'm not sure that's it,  but I could be misunderstanding the way the active
file/project is identified in atom.   I currently have it set to always
open the project I've been working on.   Pretty much,  every time I open
the editor I have the project folder in the tree view,  and my most recent
files up and running.

I just had a quick look at the error again and it pointed me at your
'target' code.  This is embarrassing,  and I'm not sure how it happened.  I
remember accidentally using that keybind <ctrl> + t and spazzing out with
my mouse because I didn't know what it was.   I just used it again,
clicked on "default"  and it started working again.   I don't have any
other targets listed,  so I'm not sure how it could have been set to
**anything** else.   Would typing garbage into it have broken something?
I'll have to check it out again later tonight.

**Comment by sloc2003** [comment]
I understand you consider this closed, but I looked into this after the fact.  I DID have a project open every time I tried this, and the whole "target" thing is supposed to be default, according to what I've read in here.  Can you think of ANY other reason that the call to the function you mentioned would fail?

I recreated the error and went into the dev tools to see what the call to getActiveTextEditor() was returning.  It was functioning as expected.  TextEditor is reading the active editor tabs and putting them in the array, as expected, but the check in your code still failed them.  For now, I've simply turned this (if (!textEditor || !textEditor.getPath()) { /* your code here*/}) off, and it's working just fine.

I haven't pulled your latest commit to see if it changes anything.  I'll look into that tomorrow morning.

I appreciate your help - like I said before, I'm fairly new at this, so I apologize for the misunderstandings that come with that.
