### ISSUE TITLE
Option to always keep the build panel hidden (unless manually toggled)

### ISSUE THREAD

**Issue by kankaristo** [noseglid/atom-build#105]
This is a partial duplicate of https://github.com/noseglid/atom-build/issues/62, but more literal.

I view the build log via tailing it in a console, so it would be great to be able to always hide the build panel, even on errors. This could be a separate option ("Manual Toggle" or similar), which would still enable manual toggling with `build:toggle-panel`.

Other use cases for this are the [tail](https://atom.io/packages/tail) and [log-console](https://atom.io/packages/log-console) packages.

I'm currently "emulating" this by adding `; exit 0` to the end of all of my build commands, but it would be great to have this as a feature.

**Comment by noseglid** [comment]
This should be cake to implement. I'll have a look at it.

**Comment by kankaristo** [comment]
Well, that was quick. Thanks! :+1:

**Comment by noseglid** [comment]
Will be available in the next version (`v0.39.0`)!
