### ISSUE TITLE
What is used to distinguish failed build from successful one

### ISSUE THREAD

**Issue by ilyapalkin** [noseglid/atom-build#107]
When I run a power shell build script I have the following output:
```
Error: 6/25/2015 9:46:16 PM: 
At E:\Work\...\packages\psake.4.3.2\tools\psake.psm1:184 char:9
```
but plugin still thinks that build finished and successful.

Should I use *errorMatch* for it?

**Comment by mthcrts** [comment]
Not checked in source code but certainly based on the exitcode of your script : 0=ok, 1=failure and then use regexp to highlight the errors.

**Comment by ilyapalkin** [comment]
I'll try to check it

**Comment by noseglid** [comment]
It is the exit code of the program. As seen in [the source code](https://github.com/noseglid/atom-build/blob/master/lib/build.js#L312), if a program exits with code `0`, it is considered a success. Anything else is considered a failure.

To be able to use error matching the failed build must exit with a code different from `0`.

**Comment by ilyapalkin** [comment]
CI servers are able to consider build as failed by means of analysing build log. 
Would it be beneficial to add such functionality to the plugin?.
