### ISSUE TITLE
build panel shows on activate when "keep visible"

### ISSUE THREAD

**Issue by braver** [noseglid/atom-build#108]
If you select the "Keep visible" mode, I would expect the panel to keep visible after a build is triggered and completed successfully. However, it currently has that side effect of the panel opening on activation of the package, which means it opens with every new Atom window, even though no build is triggered.

Atom 1.0, atom-build 0.38, OSX 10.10.4

**Comment by noseglid** [comment]
Fixed by 938804b (#115)
