### ISSUE TITLE
package load time is high

### ISSUE THREAD

**Issue by braver** [noseglid/atom-build#109]
atom-build takes about 170ms load time on my machine, which is a bit much. There is a lot of stuff going on before package activation that might be postponed. I was able to get [terminal-panel](https://github.com/thedaniel/terminal-panel/pull/67), which had similar activation times and a lot of requires, down to 5ms on activation by postponing everything until the package functionality is actually used. I think I might look into it if you don't mind, but also putting it on your radar just to be sure.

**Comment by noseglid** [comment]
I'd be delighted! I've been looking at timecop myself and thought along those same lines! Your help would be much appreciated.

**Comment by noseglid** [comment]
This improved some with the removal of bluebird (d3693f3). Still more to do though.

**Comment by noseglid** [comment]
Fixed with #352
