### ISSUE TITLE
build window takes up full window for large output

### ISSUE THREAD

**Issue by oli-obk** [noseglid/atom-build#118]
This is a regression that happened after one of the recent updates. It works fine for small outputs (a few lines). Sometimes it randomly works normally, but it's rare.

I'm on windows and Atom 1.0. I tried a complete uninstall + deletion of all config files + reinstall with just atom-build, but that didn't make a difference

**Comment by noseglid** [comment]
What do you mean "large output" ? I have a build task which I use on a daily basis which output `3401` rows. I don't see any problems with this.

Could you include a screen capture of the issue, and how to reproduce it?

**Comment by oli-obk** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/332036/8454537/6b8d3f72-1ffe-11e5-8503-7a673aa20e96.png)

a minimal reproducable example can be done by using a src/main.rs

```rust
fn main() {
    for i in 0..10000 {
        println!("{}", i);
    }
}
```

and a Cargo.toml

```toml
[package]
name = "test"
version = "0.1.0"
authors = ["noone"]
description = "..."
```

I also had a `.atom-build.json`, not sure if it's relevant:

```json
{
  "cmd": "cargo",
  "args": [ "run" ],
  "sh": false,
  "cwd": "{PROJECT_PATH}",
  "env": {
    "PATH": "C:\\Program Files\\Rust nightly 1.3\\bin;",
    "RUST_BACKTRACE": "1"
  }
}
```

**Comment by noseglid** [comment]
Weird, almost as CSS didn't take for you. Do you have anything in your `styles.less`?
Also, What does your `config.cson` contain (the `build` part).

**Comment by noseglid** [comment]
I found it. It didn't correctly set the height of the build window (configured percentage in monocle/maximized). I've fixed this and will be releasing next version shortly.

Thanks for reporting this!

**Comment by oli-obk** [comment]
you're the best! thanks

**Comment by oli-obk** [comment]
> Weird, almost as CSS didn't take for you. Do you have anything in your styles.less?

As i wrote in the beginning, I tried a clean install with deleting the entire config
