### ISSUE TITLE
Case Sensitivity on Windows

### ISSUE THREAD

**Issue by GlenCFL** [noseglid/atom-build#119]
On Windows, it is possible that error output will refer to files in a case different than what is actually present on the file system. Microsoft's C++ compiler, for example, seems to convert the entire path of a source file to lowercase at some point during compilation. "C:\Source\Test.cpp" would become "c:\source\test.cpp".

The problem arises whenever you capture this in regex as \<file>, then use the build:error-match command. If there is an error, then Build will open the file in a new tab, whether or not the same file is open with differing case in the file path.

- open "C:\Source\Test.cpp" in a tab.
- compiled using cl.exe, while containing an error
- command "build:error-match" used
- new tab opened of "c:\source\test.cpp"

This causes a slew of problems within Atom for that new tab, as Atom seems to expect the file path casing to match what is actually present on the file system.

I'm not sure if this is your issue or an issue for Atom itself.

**Comment by braver** [comment]
> I'm not sure if this is your issue or an issue for Atom itself.

.. or just Windows being a silly OS :wink: 

So, what you're saying is

You've got a file `File.ext`
You build that
The build process outputs errors referring to `file.ext`
atom-build reads this output and will try to open `file.ext`

You can't really expect atom-build to understand that `file.ext` should really be `File.ext`. So you're basically asking that Atom not be case sensitive when trying to open files. Would that even work reliably?

**Comment by GlenCFL** [comment]
Closing, as it's definitely not your issue. You might have been able to query the filesystem on Windows and make a pretty good assumption, but that's it.

> Would that even work reliably?

I believe the answer is no. NTFS is case sensitive, with Windows seeming to do its best to enforce case insensitivity. It's still possible that two files will exist with the same name on the file system.
