### ISSUE TITLE
For each build variant, add regexp to filtering files for build-on-save.

### ISSUE THREAD

**Issue by lygstate** [noseglid/atom-build#121]
Each build-variant can attach a 
regexp to filtering files that should trigger build when those files
are modified and saved.

**Comment by noseglid** [comment]
I'm not sure how this would work. Only `.atom-build.json` allows for any use specification. All the other build tools work *as is*.

What is this in regard to? Is it `.coffee` files you want to "build" to `.js` files?

This issue seems very close to what is asked in #50.

**Comment by noseglid** [comment]
Closing due to no response. Also likely dupe of #50
