### ISSUE TITLE
Add a button in build panel to copy text in build console.

### ISSUE THREAD

**Issue by lygstate** [noseglid/atom-build#122]
This would makes the text can be copied out for other process.

**Comment by lygstate** [comment]
Or enable ctrl-c in build console, at the current time it's not works.

**Comment by lygstate** [comment]
It's a bug of atom, occasionally the panel can not copy things.

**Comment by noseglid** [comment]
Could you point me to any error report in Atom which addresses this issue?

**Comment by lygstate** [comment]
I am sorry, this is unreproduciable
