### ISSUE TITLE
[Bug] Can't abort build, if command starts subprocesses

### ISSUE THREAD

**Issue by MackieLoeffel** [noseglid/atom-build#129]
The following is only tested on windows.

## Problem
If I start coffee.cmd as a custom tool to build my project, it starts nodejs as a subprocess to run the coffee code. When this code hangs and I want to abort it, atom-build hangs with
> Build Process termination imminent...

because it only kills the parent process, but not the child nodejs process.

## Fix
use tree-kill to kill the whole process tree

**Comment by noseglid** [comment]
Tracking this is in #130
