### ISSUE TITLE
build key doesn't work

### ISSUE THREAD

**Issue by Larceny-** [noseglid/atom-build#132]
I can't build from ctrl + alt + b.
But from menu bar i can build normally.

Ubuntu 15.04
Atom 1.0.2

**Comment by noseglid** [comment]
Most likely you have a keymap conflict..

Press `ctrl-.` (that's Control and Dot), and you can see the keymap matcher. Now press `ctrl-alt-b` and see what that resolve to in your atom.

**Comment by Larceny-** [comment]
Thanks!
