### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by janbaykara** [noseglid/atom-build#136]
I'm using .nvm, and it seems like the package is looking in the entirely wrong place for the binary.

**Comment by noseglid** [comment]
What OS are you on, what version Atom? What are you trying to build? Where do you think it is looking, and what is the correct location?

**Comment by froodian** [comment]
I'm not OP but I'm also having this issue.  I have a grunt-based project.  The output from atom-build is 

```
Executing: /Users/ian/dev/web-sdk/node_modules/.bin/grunt  default
env: node: No such file or directory
```

`/Users/ian/dev/web-sdk/node_modules/.bin/grunt` does exist on my machine (and if I run `grunt` from the terminal while in the root directory of my atom project folder, it works)

**Comment by noseglid** [comment]
Where is Node installed? How do you start Atom?
My guess is that the PATH variable is not set to include the path where node is installed when you start Atom.

**Comment by froodian** [comment]
`/opt/local/bin/node`

I start Atom by opening the .app file from my /Applications folder, doing File->Open... and choosing `~/dev/web-sdk`

**Comment by froodian** [comment]
fwiw when I do `echo $PATH` from the terminal it includes `/opt/local/bin` but I'm not sure how to check the PATH variable that's visible to Atom

**Comment by noseglid** [comment]
Just to make sure this is actually the case, if you close Atom (press `cmd-q`) and then start it in your terminal instead (by typing `atom`). Does it work then?

**Comment by froodian** [comment]
Yeah, that works.  I'm ok with doing that - much more efficient really.

**Comment by noseglid** [comment]
And if you want to fix it via the Docker/Finder application icon, [use this](http://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications).
