### ISSUE TITLE
ENH: global custom builds

### ISSUE THREAD

**Issue by spencerlyon2** [noseglid/atom-build#141]
I would love to see functionality for specifying a global custom build. 

A use case would be to run the (python|R|Julia|perl) script I'm editing -- no matter which project I'm working on.

Does this feature already exist?

**Comment by noseglid** [comment]
I think this would be a good participant to put in a plugin to atom-build. By using the service API a plugin can provide build configurations. An example on how this can be done (with gulp) can be [seen in the atom-build-gulp](https://github.com/noseglid/atom-build-gulp) package. I do not think this has been done yet for any of the script interpreters you mention.

I want to move build configurations away from this package so this would not be in scope here.

**Comment by spencerlyon2** [comment]
Ok thanks for the info
