### ISSUE TITLE
Build error display

### ISSUE THREAD

**Issue by Ser0ja** [noseglid/atom-build#148]
![build error display](https://cloud.githubusercontent.com/assets/5020923/9021216/7f34ac1e-383f-11e5-898d-ea0b2b6e0487.jpg)
Error execute a broken line.

**Comment by noseglid** [comment]
That's weird. Can you inspect the build panel (via dev tools) to see if there actually are new-line characters or if it is broken by layout?

**Comment by Ser0ja** [comment]
Ctrl+Alt+B
![image](https://cloud.githubusercontent.com/assets/5020923/9096745/cd380902-3bc7-11e5-8021-c3d60c8332c8.png)
again Ctrl+Alt+B
![image](https://cloud.githubusercontent.com/assets/5020923/9096753/da4faf14-3bc7-11e5-96ee-c2d4e8a717fe.png)

**Comment by noseglid** [comment]
So it is different the second time you run it?

**Comment by Ser0ja** [comment]
random.every press it look different.

**Comment by noseglid** [comment]
Thanks for the report. A change was recently made which likely caused this where each buffer was added as a line rather than being line-buffered as it was before.
