### ISSUE TITLE
Multiple builds being fired for rake command

### ISSUE THREAD

**Issue by griley** [noseglid/atom-build#149]
I've been attempting to use atom-build to launch a [rake](https://github.com/ruby/rake) task to do a build.  However, when I run this build via cmd-alt-b it appears that 2 instances of the build are launched.  I recreated a simple case:

Rakefile:

```
task :default => :test

desc 'Test'
task :test do |t|
  puts "Running test"
end
```

.atom-build.json:
```
{
  "cmd": "~/.rbenv/shims/bundle",
  "args": ["exec", "rake"],
  "sh": true,
  "env": {
    "FLEX_SDK_HOME": "/Applications/flex_sdk_4.6"
  },
  "errorMatch": "(?<file>src/.*\\.(mxml|as))\\((?<line>\\d+)\\): col: (?<col>\\d+)"
}
```

When I run `~/.rbenv/shims/bundle exec rake` from a shell prompt I get the expected ouptut:
```
Running test
```

However when launching from atom-build, I see the following in the build panel:
```
Executing with sh: ~/.rbenv/shims/bundle  exec rake
Running test
Running test
```

**Comment by noseglid** [comment]
Could it be that `build` has been activated twice. I've noticed via other issues that this seem to happen from time to time. If you disable `atom-build`, restart `Atom` and then enable `atom-build` again. Does it still happen?

**Comment by griley** [comment]
After restarting Atom, the issue disappeared.  I will re-open this issue if I can find a way to reproduce the problem.  Thanks.

**Comment by noseglid** [comment]
Okay cool. I don't think it has anything to do with the `build` package itself, but rather atom which starts multiple instances of it. Haven't been able to reliably reproduce it though to open an issue.
