### ISSUE TITLE
Mastering atom-build for personal use and stuck, any suggestions?

### ISSUE THREAD

**Issue by icrosil** [noseglid/atom-build#151]
* Is there ways to trigger on target from another one by creating custom builds like $(MAKE) ... in Makefile
* Any way to run command as sudo?

**Comment by noseglid** [comment]
There is currently no way to chain targets like that. I feel this is beyond the scope of the `build` plugin. I don't want it to be a build tool, but rather an executor of such tools. If you use `GNU Make` or any other buildtool I've ever heard of, you should be able to build dependency chains and run several targets at once. You could the use the `build` plugin to execute it.

It should be possible to run sudo commands if you're allowed to do sudo without a password. There's no TTY connected to the spawned process, so there's no way to provide any input. If I attempt to use `sudo` on my OSX machine, it says
```
Executing with sh: sudo echo a 
sudo: no tty present and no askpass program specified
```

I'm guessing maybe you can provide a custom application for querying the password. Another viable solution could be to allow password-less sudo (http://unix.stackexchange.com/questions/43135/allowing-a-user-to-use-sudo-without-a-password).
