### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by Gurpartap** [noseglid/atom-build#156]
Is there a plan to support a "Run" command?

Currently if a long running command is supplied as the build command, the plugin is unable to print its output (its probably waiting for the process to exit). It is also unable to terminate the process (it stays in the "imminent" state forever; I have to sigterm the process manually).

**Comment by noseglid** [comment]
Regarding the output, could it be related to #155 ?
You can press escape once more to forcefully kill the spawned command if it doesn't respond to `SIGKILL`.

I'm not sure what you mean by a "Run" command.

**Comment by Gurpartap** [comment]
Run differentiates from Build in the sense that Build command would make sure the code builds. And Run command would execute the code (for example a web server, which is a long running task).

I have a `.atom-build.json` file with: `{ "cmd": "kore build" }`. Works fine. However, when I change `cmd` to `kore run`, it'll be stuck at `Building...`. Pressing escape once or twice changes the visible status only (doesn't stop the actually process).

I suspect this is because (maybe) `kore` starts a subprocess which the build plugin is unaware of?

Quickstart to test this: `brew install kore && cd ~/Projects/ && kore create myapp && kore run`

**Comment by noseglid** [comment]
Build uses [tree-kill](https://www.npmjs.com/package/tree-kill) to kill all spawned processes. I wasn't aware that it isn't working. The first time you press escape it sends `SIGTERM` to the process and all it's children. The second time it sends `SIGKILL`. How does `kore` spawn stuff?

Running application I feel is out of scope for this plugin. Another plugin might handle that.

**Comment by noseglid** [comment]
Closing this as out of scope. If you don't get the Termination to work, open a new issue for that.
