### ISSUE TITLE
[Feature Request] Gradle Suport

### ISSUE THREAD

**Issue by Hopperston** [noseglid/atom-build#161]
If would be great if this package supported Gradle out of the box, its now the default build system for android apps among other places.

**Comment by noseglid** [comment]
I would very much like this!

But it should be done as a provider rather than integrated directly into `atom-build`. I will be looking to move all current build tools to providers as well.

**Comment by noseglid** [comment]
This now exists in package [build-gradle](https://atom.io/packages/build-gradle).
