### ISSUE TITLE
Use multiple CPU threads for `make`

### ISSUE THREAD

**Issue by Calinou** [noseglid/atom-build#166]
```
make -j$(nproc)
```

When run on a GNU/Linux system, this will automatically detect the number of available CPU threads and build.

What about having a dropdown in settings for setting the number of CPU cores to use with `make`, with an option to detect automatically? Currently, it looks like this package always uses 1 CPU thread.

**Comment by noseglid** [comment]
Thanks for the report!

I am in the process of migrating all build tools to separate projects. I'm moving this issue to [noseglid/atom-build-make](https://github.com/noseglid/atom-build-make).
