### ISSUE TITLE
Targets should inherit "errorMatch" from default target

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#170]
I have several targets with different build configurations. For each one I need to copy the "errorMatch" property in order for it to take effect. Would be great if they could fallback to the default one.

**Comment by noseglid** [comment]
The different commands are not really connected. The fact that one can be specified on the top level, and others in the `targets` subsection serves only one purpose: If you only want one target it should be easy to do so. There is no relation between targets and I want to keep it that way.

This was also discussed in detail in #89 (where the topic was chained targets).

Thanks for the suggestion though.
