### ISSUE TITLE
Panel should be dockable in other places in the workspace.

### ISSUE THREAD

**Issue by shakesoda** [noseglid/atom-build#171]
I've got all this unused horizontal space, and the build window insists on taking up the bottom!

It'd be really nice if I could instead have it open on the left or right of the window to reclaim precious vertical space.

![](http://i.imgur.com/JbGERIv.png)

**Comment by noseglid** [comment]
Work for this actually begun by in #88 but never reached mergable status.

**Comment by noseglid** [comment]
This is in a branch now, `panel-orientation`. I'd appreciate if you wanted to test it!

**Comment by shakesoda** [comment]
I changed the panel orientation, but no matter where I put it nothing happens (it's stuck at the bottom and the height settings don't do anything).

**Comment by shakesoda** [comment]
scratch that - install problem. seems to be working fine, aside from "build finished" being in a weird place (stuck to the bottom of the output, instead of the bottom of the panel)

**Comment by noseglid** [comment]
When you have the panel where? Could you include a screenshot?

**Comment by shakesoda** [comment]
Right side.

![ss 2015-09-20 at 09 58 13](https://cloud.githubusercontent.com/assets/219510/9985549/ca1fd936-5fe2-11e5-987d-5f327e82b744.png)
![ss 2015-09-20 at 09 58 46](https://cloud.githubusercontent.com/assets/219510/9985550/ca220422-5fe2-11e5-8f21-f1b59e2b8e19.png)

**Comment by noseglid** [comment]
This was fixed by #180
