### ISSUE TITLE
Running make file on specific folder/file

### ISSUE THREAD

**Issue by mendelkranz** [noseglid/atom-build#174]
Hi,

In the specific folder that I'm working in, I have a make file that uses [pandoc](http://pandoc.org "Pandoc - About pandoc") to convert a markdown file to pdf, docx, and html. However when I use the build command I think it attempts to convert the whole project and thus immediately runs into an error in trying to convert the Read Me file in the root of my project. Is there a way to specify the command so that it will only run the make file in the current folder I'm in? 

Thanks!

**Comment by noseglid** [comment]
Yes, you can set the current working directory in a custom atom-build file:
```json
{
  "cmd": "make"
  "cwd": "{FILE_ACTIVE_PATH}"
}
```

Save this as `.atom-build.json` in the root folder and it will run make in whatever path the currently active file resides in. [Read more about replacements](https://github.com/noseglid/atom-build#replacements)

**Comment by mendelkranz** [comment]
Thanks for the quick reply!

I'm getting an error though which says 

`you have a syntax error in your build file: /Users/[user]/github/papers/.atom-build.json: Unexpected string`

I copied exactly what you put up there into the file.

**Comment by noseglid** [comment]
Can you paste the contents of your `.atom-build.json`?

**Comment by mendelkranz** [comment]
`{
  "cmd": "make"
  "cwd": "{FILE_ACTIVE_PATH}"
}
`

**Comment by mendelkranz** [comment]
Sorry, but with the proper line breaks.

**Comment by noseglid** [comment]
There's no comma after `"make"`.

**Comment by mendelkranz** [comment]
ah of course! Thanks!
Ok one more quick problem, as I said I'm using pandoc to convert a markdown file, and I'm using xelatex as the latex engine. It runs fine when I run it through the terminal but if I run it here I get this: `pandoc: xelatex not found. xelatex is needed for pdf output.`
Any idea why this wouldn't work?

Thanks again for your help

**Comment by noseglid** [comment]
I'm guessing the PATH is not set correctly when you open Atom. You probably have something in your  `.zshrc`, `.bashrc` or equivalent shell init scripts which adds wherever `xelatex` is to your PATH. You could try to close Atom and start it from a terminal where it works. If it works then, you know it's a path issue.

**Comment by mendelkranz** [comment]
I'm sorry, I don't quite understand what you mean when you say `you could try to close Atom and start it from a terminal where it works.`

**Comment by noseglid** [comment]
* So, quit atom completely. (`Atom -> Quit`).
* Go to a terminal where `Make` works and start atom from there.
* Run build. If it works, it is definitely a PATH issue.

**Comment by mendelkranz** [comment]
You're right! That worked, would you mind telling me how to fix the PATH issue?

Thanks for all your help with this, I really do appreciate it.

**Comment by noseglid** [comment]
It's no problem. It depends on the operating system. On Unix/Linux, you can inspect the PATH variable by e.g. `echo $PATH`. It will be a colon `:` separated list of locations to search for binaries (such as `xelatex`).

See [this issue](https://github.com/noseglid/atom-build/issues/56) and [this issue](https://github.com/noseglid/atom-build/issues/51) for solutions from people with similar problems.

**Comment by mendelkranz** [comment]
Ok, so I added a line in my .bash_profile which says `export PATH="$PATH:$HOME/usr/texbin/xelatex"`

As I understand it, that should add xelatex to the end of my path (and I think it did based on `echo $PATH`

Anyways, now the build works! Thanks for your help.
