### ISSUE TITLE
Support .atom-build.cson

### ISSUE THREAD

**Issue by dnalot** [noseglid/atom-build#178]
Would be especially nice for error regexes:
```cson
cmd: "jade"
args: ["index.jade", "--pretty"]
errorMatch: [
  ///
    \w+Error
    :\s (?<file> [^:]+ )
    :   (?<line>   \d+ )
  ///
]
```
Compare:
```json
{
  "cmd": "jade",
  "args": ["index.jade", "--pretty"],
  "errorMatch": ["\\w+Error: (?<file>[^:]+):(?<line>\\d+)"]
}
```

**Comment by noseglid** [comment]
Thanks for the suggestion. I have a solution to this pushed to a branch; `cson`. I'd appreciate any feedback you might have.

**Comment by dnalot** [comment]
Looks solid I can't wait to try!

**Comment by dnalot** [comment]
Unfortunately the parser doesn't support regex :crying_cat_face: The only solution I can think would be to require CoffeeScript directly.

**Comment by dnalot** [comment]
@noseglid could you try updating `cson-parser` to `^1.3.0`? @jkrems implemented it :tada:

**Comment by noseglid** [comment]
Cool. Sure thing

**Comment by noseglid** [comment]
I've updated to 1.3.0 on branch `upgrade-cson-parser`, however I don't think it will match your expectations. CSON-parser appears to interpret whatever is between two instances of `///` as a regex, which is not true in a javascript sense. `build` uses [XRegExp](http://xregexp.com/), which makes use of named matching groups (the `(?<name>)` syntax). This is not supported by native regex.

**Comment by dnalot** [comment]
You're right the generated JS regex itself crashes. XRegExp actually supports a lot of the same niceties but is still messy without tagged nor highlighted. Thinking of a solution.

**Comment by dnalot** [comment]
Ah you're `require`ing the JSON so tagged strings might be the answer! Trying it out…

**Comment by dnalot** [comment]
I opened an issue with XRegExp for one possible solution. Another using native JS would require passing along flags. Passing the object alone as if  it were a regex didn't work:
```js
{
  cmd: "jade",
  args: ["index.jade", "--pretty"],
  errorMatch: [
    {
      pattern: `
        \\w+Error
        :\\s (?<file> [^:]+ )
        :    (?<line>   \\d+ )
      `,
      flags: "x"
    }
  ]
}
```

**Comment by kepler0** [comment]
If you want to use native regex syntax then we should look into handling regex like `text-mate` (the Atom package which does syntax highlighting) does.

**Comment by dnalot** [comment]
@noseglid Here are a [couple alternatives](https://tonicdev.com/dnalot/56588279e505840c00c1998a) to support nice regexes:

1. Optionally pass flags with an ES6 tagged string
2. Manually replace invalid capture tokens

**Comment by kepler0** [comment]
@dnalot Have you seen the way Atom CSON grammars are written?

**Comment by dnalot** [comment]
I've written them. This ticket is about formatting configs.

**Comment by kepler0** [comment]
I understand what this ticket is about. I'm suggesting that if you want to use vanilla CoffeeScript Regex syntax, you should follow by it's rules. Which would mean no named capture groups. If you wish to use CoffeeScript Regex Syntax then you should give the numbered capture group and identifier `build` can understand. See attaching number capture groups to identifiers [here](https://github.com/atom-crystal/language-crystal/blob/master/grammars/crystal.cson#L9-L29).

I suggest a syntax such as:
``` coffee
cmd: "jade"
args: ["index.jade", "--pretty"]
errorMatch: [
  {
    match: ///
      \w+Error
      :\s ([^:]+)
      :   (\d+)
    ///
    patterns:
      1: 'file'
      2: 'line' 
  }
]
```

**Comment by dnalot** [comment]
Brilliant! I tracked slevithan/xregexp#120 to allow `{{name}}` to work with `XRegExp.build` without associated `patterns`. This does appear far more flexible and would resolve ES6 tagged strings, my issue, and my XRegExp proposal if implemented :+1: @kepler0 Update [this line](https://github.com/noseglid/atom-build/blob/755611fc4c18a8f845480f454e66cf7e9fe4c58d/lib/error-matcher.js#L93)?
```js
var pattern = r.pattern || r // r is the pattern when r.pattern is missing
var captures = r.captures // optional
var flags = r.flags // ignored when r is RegExp
return XRegExp.build(pattern, captures, flags)
```
Updating my linked tonic.

**Comment by kepler0** [comment]
I'm not comfortable forcing named Capture groups on a Regex implementation that doesn't support them.

**Comment by dnalot** [comment]
I see what you mean now. My code still allows you to pass flags which you can't currently?

**Comment by kepler0** [comment]
A field for regex flags seems reasonable.

**Comment by dnalot** [comment]
Moreover `XRegExp.build` exposes additional functionality if desired. [Here it is](https://tonicdev.com/dnalot/56588279e505840c00c1998a) in action.

**Comment by noseglid** [comment]
Hey. Brilliant discussion. I suggest the following changes:

  1. Support for setting the regex flags
  2. Name the match groups in another entry.

So the following would be valid JSON:
```
{
  "cmd": "jade",
  "args": ["index.jade", "--pretty"],
  "errorMatch": [
  {
    "match": "\\w+Error:\\s ([^:]+):   (\\d+)",
    "flags": "m",
    "patterns": [ "file", "line" ]
  }
]
```

Since arrays are ordered, this means that the first match group will be the file, and the second match group will be the line. Specifying the `patterns` entry as `[ "line", "file" ]` and it would be the other way around. Flags are the normal [flags available in JavaScript regexes](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags).

Does this make sense and suit all our needs?

**Comment by dnalot** [comment]
@noseglid Did you see [my implementation/tests](https://tonicdev.com/dnalot/56588279e505840c00c1998a)? It's exactly your proposal (I think) but _always_ uses `XRegExp` (builtin `build`) with minimal implementation/maintenance cost.

**Comment by dnalot** [comment]
Also XRegExp always defers to RegExp under the hood if provided.
