### ISSUE TITLE
No Support for Multiple Projects

### ISSUE THREAD

**Issue by CannibalVox** [noseglid/atom-build#179]
I add multiple projects to Atom via the "Add Project Folder" functionality, but atom-build will only operate on the top folder.  I'd appreciate it if the default behavior were to build the project for the current file/focused tree node.  Or at least a toggle.

**Comment by josip** [comment]
:+1: To make it work I have to invoke "Build: Select Active Target" from the command panel and then choose the target, because the list there appears to show targets for the current project folder.

**Comment by noseglid** [comment]
Yes, the last executed command is cached to improve user experience (it might take some time to extract targets from the build tool). When running: `Build: Select Active Target`, it refreshes the list (and selects a new active target if the old one isn't available anymore (such as if you've changed project).

Definitely need to take some action on this to make it work better with multiple projects. There is already some support but it can be improved. Definitely.
