### ISSUE TITLE
auto save on build broken on latest Atom

### ISSUE THREAD

**Issue by karai17** [noseglid/atom-build#182]
I just updated to Atom 1.0.13 and it seems that this feature is bork now.

**Comment by noseglid** [comment]
Hmm, it's working for me. Could you attempt to restart Atom and/or re-install atom-build?

**Comment by karai17** [comment]
I restarted Atom, uninstalled build, restarted Atom again, reinstalled
build, and still no luck.


---
Landon Manning
lmanning17@gmail.com

**Comment by noseglid** [comment]
Just to confirm, it's the save-on-build feature, not build-on-save?

**Comment by karai17** [comment]
Correct, build-on-save seems to work fine.


---
Landon Manning
lmanning17@gmail.com

**Comment by noseglid** [comment]
I really can't get this to happen. What is happening when you have `saveOnBuild` checked, have an edited file and trigger the build command? Do the Confirm dialog popup ?

**Comment by karai17** [comment]
No dialogs pop up. If I make an edit then build without manually saving,
the program runs as if no changes were made.

**Comment by noseglid** [comment]
When editing which file? Is it a file in the project, or `.atom-build.json` itself? Any other build file?

Would you mind making a screencast when you see this? You can use [licecap](http://www.cockos.com/licecap/) to quickly capture the work flow which shows this issue.

**Comment by karai17** [comment]
It... seems to be working now. I have no idea why as I have no restarted Atom since yesterday but it appears ot be working. I just upgraded to 1.0.15 and it still works. Yay?

**Comment by noseglid** [comment]
Okay good.

No idea why. seems really weird. I'll close this for now. Please get back if the problem re-appears and we will delve further into it.
