### ISSUE TITLE
OSx: Spaces in {FILE_ACTIVE_PATH} breaks

### ISSUE THREAD

**Issue by martindsouza** [noseglid/atom-build#189]
Similar to issue #14.

When my path has a space in it, Build seems to break on the space. For example, suppose my path is: `/Users/martin/Documents/folder with space`, when I run the build script and `echo` the full path of the file name I see: `/Users/martin/Documents/folder`. Here is my `.atom-build.json` file for the project:

```json

  "cmd": "/oracle/atom/atom_compile_oracle.sh",
  "name": "Build Oracle code file",
  "args": [ "${host}", "${port}", "${sid}", "${user}", "${password}", "{FILE_ACTIVE}" ],
  "sh": true,
  "cwd": "{FILE_ACTIVE_PATH}",
  "env": {
    "user": "oracle",
    "password" : "oracle",
    "host" : "localhost",
    "port" : "1521",
    "sid" : "xe"
  },
  "errorMatch": [
  ],
  "keymap": "",
  "targets": {
  }
}
```

Part of the bash file that is `echo`ing the full path:
```bash
echo "Compiling file: $6"
```

**Comment by noseglid** [comment]
You've set `sh` to `true`. Shell separates arguments by spaces.

You have two options:
  * Change `cmd` to `/bin/sh` (or whatever shell you're using), set `sh` to false, add the path to your shell script as the first argument.
  * Quote the `{FILE_ACTIVE}` argument with single quotes, so it becomes: `"'{FILE_ACTIVE}'"`.
