### ISSUE TITLE
Detecting Error

### ISSUE THREAD

**Issue by martindsouza** [noseglid/atom-build#190]
I'm using Build to compile packages in Oracle. The following is an example of an error one might see while compiling a package:

```plsql
Package body PKG_TEST compiled

Errors: check compiler log
Errors for PACKAGE BODY MARTIN.PKG_TEST:

LINE/COL ERROR
-------- ----------------------------------------------------------------------------------------
12/3     PLS-00103: Encountered the symbol "GC_SCOPE_PREFIX" when expecting one of the following:
         
         := . ( @ % ; not null range default character
         The symbol ";" was substituted for "GC_SCOPE_PREFIX" to continue.
```
The file that was used to compile this error message is called `pkg_test.pkb`. 

- How do I show that an error occurred as part of this build?
  - Right now the build just says "Build finished" in green
- I have looked at the `errorMatch` attribute and read how to configure it but I don't think it would work in this case as the error message does not contain the file name (rather just the package that failed)

**Comment by noseglid** [comment]
Atom build detects error if the exit code from the command is `!= 0`. I have no idea how to get your command to do that.

ErrorMatcher won't cause the build to fail (yet). It just matches the output with a provided regex and opens a file at the row and column specified when pressing cmd-alt-b. If/when #144 gets merged, a match from error-matcher will also cause build to fail.
