### ISSUE TITLE
Build never finishes when run via atom-build

### ISSUE THREAD

**Issue by Dygerati** [noseglid/atom-build#191]
So I have a pretty simple build config in .atom-build.json:
```
{
  "cmd": "iojs",
  "args": [ "/usr/local/bin/gulp", "build" ],
  "sh": false,
  "env": {
    "NODE_ENV": "test"
  }
}
```

This used to work just fine, but a couple months ago or so the build box that comes up while building stopped recognizing when the build was finished. The console output will read `[15:28:22] Finished 'build' after 3.7 μs` but, just below, it will still read "Building..." and the seconds count up indefinitely.

If I run this on the command line it has no issue and exits normally. I tried searching other issues but saw no mention of similar behavior. Any thoughts?

Versions:
gulp 3.8.11
iojs 3.3.1
atom 1.0.19
atom-build 0.47.0

**Comment by Dygerati** [comment]
Got this figured; it had to do with an issue in gulp-shell:

https://github.com/sun-zheng-an/gulp-shell/issues/59

**Comment by noseglid** [comment]
Great. Sorry for taking so long to reply. I had no idea from the top of my head, and haven't had time to look into it deeper.
Good job on finding the cause!
