### ISSUE TITLE
Possible Linter Integration?

### ISSUE THREAD

**Issue by keplersj** [noseglid/atom-build#197]
This seems like a great package, I'd like to see it integrate with Linter is some way.

I'm thinking that if error range points to a file, it could tell Linter of the error so that it will be displayed inline (like other IDEs.)

If this can be integrated cleanly I'd love to feature the `build` providers on the AtomLinter homepage.

/cc @steelbrain @joefitzgerald

**Comment by noseglid** [comment]
That's a decent idea. I know this has been discussed before, but never really amounted to anything. I'm happy to accept pull requests for this.

**Comment by steelbrain** [comment]
If someone wants to do it, here's a pointer. Use the self-api exported by the linter package. Create an object of the linter shape and set messages with it. Use `atom-package-deps` to automatically install dependencies.

**Comment by noseglid** [comment]
If anyone takes a stab at this, post something here to avoid duplicated work. I'll look into it as soon as I have some time unless someone beats me to it.

**Comment by k2b6s9j** [comment]
I will give it a shot tonight. Please do not take it to be a commitment though, if someone else wants to do this please do.

**Comment by cbetancourt** [comment]
Why not just add your favorite linter to your build process? I prefer `eslint` with these global rules (in `.eslint`):
```
/**
 * See default rules here:
 * http://eslint.org/docs/rules/
*/
{
	"rules": {
		"camelcase": 0,
		"no-use-before-define": 0,
		"no-spaced-func": 0,
		"no-underscore-dangle": 0,
		"new-cap": 0,
		"no-console": 0,
		// warn on unused variables
		"no-unused-vars": 1
	}
}
```
Then in my Gruntfile, I use `gruntify-eslint`:
```
eslint: {
	src_js: {
		src: [
			"Gruntfile.js",
			"<%= dirs.source_js %>/**/*.js"
		]
	}
}
```
Also, within Atom I use the plugin `linter-eslint` which uses the rules above to validate JavaScript as it is edited.

**Comment by kepler0** [comment]
@cbetancourt I think you may have misunderstood. The intent of this issue is to take any Error Matching Result that maps to a file and send it to `linter` so that it may be displayed inline. This would be incredibly helpful for packages like `build-sbt` or `build-gradle` where creating an effcient package for linter is almost impossible, especially since `linter` was never intended to handle issues of that size.

It would be very helpful for creating a modular IDE of Atom.

**Comment by noseglid** [comment]
Closing as this is now supported.
