### ISSUE TITLE
Possible keybind overlap with Atom?

### ISSUE THREAD

**Issue by Jay1** [noseglid/atom-build#198]
I don't do this very often, pardon my Github etiquette,

CTRL-ALT-B (build:trigger on atom-build) overlap with editor:move-to-previous-subword-boundary from atom-text-editor (which is the case by default I believe)

I don't know if it's a well known fact and I'm stating the obvious here, but I had to rebind build:trigger for a few months now, every new patch.

**Comment by noseglid** [comment]
Which version of `build` do you have? This was already reported in #168 and (supposedly) fixed in #172 . This was released in `v0.46.0`.

**Comment by Jay1** [comment]
version : 0.47.0

This is my build.json
```json
{
  ".platform-darwin atom-workspace, .platform-darwin atom-text-editor": {
    "cmd-alt-b": "build:trigger",
    "cmd-alt-v": "build:toggle-panel",
    "cmd-alt-g": "build:error-match",
    "cmd-alt-h": "build:error-match-first",
    "cmd-alt-t": "build:select-active-target"
  },
  ".platform-linux atom-workspace, .platform-linux atom-text-editor, .platform-win32 atom-workspace, .platform-win32 atom-text-editor": {
    "ctrl-alt-b": "build:trigger",
    "ctrl-alt-v": "build:toggle-panel",
    "ctrl-alt-g": "build:error-match",
    "ctrl-alt-h": "build:error-match-first",
    "ctrl-alt-t": "build:select-active-target"
  },
  ".build": {
    "escape": "build:stop"
  },
  ".build-confirm": {
    "enter": "build:confirm",
    "escape": "build:no-confirm"
  }
}

```

**Comment by noseglid** [comment]
Yes, that is what the `build.json` keymap should look like. Could you bring up the Key-binding resolver (via the command palette) and press `ctrl-alt-b` or `cmd-alt-b` depending on OS? What does it show?

**Comment by Jay1** [comment]
On windows 10
![Key-binding resolver](http://i.imgur.com/tAfRaE7.jpg)
