### ISSUE TITLE
Error links in build panel are gone.

### ISSUE THREAD

**Issue by xpol** [noseglid/atom-build#201]
There was once error links (with underline) in build panel. Click the link will  jump to source code line.

But recently, the Error links are gone, just plan text. 
*(The error parse is OK because the `build: error match` command works correctly.)*

**Comment by noseglid** [comment]
Can you provide some output which reproduces this?

Is is possible to click the error and have it open the correct file still?

**Comment by noseglid** [comment]
Hopefully fixed with #207. If not, open a new issue.
