### ISSUE TITLE
Unable to execute: php-cs-fixer

### ISSUE THREAD

**Issue by dugajean** [noseglid/atom-build#208]
I am trying to use a package called `php-cs-fixer` to reformat my code in Atom. So I made a custom build command and added the following contents to my JSON file:

```
{
  "cmd": "php-cs-fixer",
  "args": ["fix", "{FILE_ACTIVE}", "--level=psr2"],
  "sh": false
}
```

However, when I press my shortcut to build everything, I get this error:
> Executing: php-cs-fixer  fix C:\xampp\htdocs\crs\app\Http\Controllers\EntriesController.php --level=psr2
> Unable to execute: php-cs-fixer

No more explanations provided and I don't get what's wrong. Could this be a bug on the package's end?

P.S: The command as the build window outputs is correct and should work

**Comment by noseglid** [comment]
Where is `php-cs-fixer` installed?

**Comment by DEATHMETALGORE** [comment]
It's in my default user and system path. Shouldn't Atom be grabbing information from there too?

**Comment by noseglid** [comment]
See if #75 help you.

To verify if it is a PATH issue try and put the absolute path as the command. If that works then you definitely have a path issue.

**Comment by DEATHMETALGORE** [comment]
Hey, I tried adding the full path and I got the same issue:

```
Executing: C:/Users/Dukagjin/AppData/Roaming/Composer/vendor/bin/php-cs-fixer  fix C:\xampp\htdocs\crs\app\Http\Controllers\EntriesController.php --level=psr2
Unable to execute: C:/Users/Dukagjin/AppData/Roaming/Composer/vendor/bin/php-cs-fixer
```
Also added the same path to the System Path, again, same issue,

**Comment by DEATHMETALGORE** [comment]
Is there a possibility to check the cause of this issue? I think it would be very useful if this worked properly, because on my end, I don't think I'm doing anything wrong. I have the same build on sublime text 3 and it works there with no problems whatsoever.

**Comment by noseglid** [comment]
Unless there is something very special in the way `php-cs-fixer` is executed, there's likely a setup error on your end.

Please paste the `.atom-build.json` you used, when you used the full path.

**Comment by cbetancourt** [comment]
I was having the issue running other commands from within the Gruntfile while building with this plugin. According to the [documentation for atom-lint](https://atom.io/packages/atom-lint#linter-executable-paths):

> There's an issue that environment variables in Atom varies depending on whether it's launched via shell or GUI. If it's launched via GUI, it cannot get the environment variables set in your shell rc files like PATH. To handle this issue, when Atom is launched via shell, Atom-Lint automatically saves the environment variables, and from then on it will use the saved variables on linter invocation even if Atom is launched via GUI.

So as suggested, I started Atom from the command line and the commands executed as expected.

**Comment by noseglid** [comment]
Closing this out due to inactivity. Please re-open if the issue remains with the details I asked for above.
