### ISSUE TITLE
Global build targets

### ISSUE THREAD

**Issue by tmazur** [noseglid/atom-build#209]
As far as I am aware, there is no way to define build targets that are available across all projects (even those without .atom-build files). Providing such a feature would be a nice enhancement.

**Comment by academo** [comment]
I can related to this, is any way to include a global config file beside the hard coded plugins?

**Comment by noseglid** [comment]
There is no way right now. But I'm looking into adding additional paths to search for the custom files (`.atom-build.json`, `.atom-build.cson` - and soon `.atom-build.yml`).

The user home directory would be an obvious candidate. Possibly also a configurable path to search for global build targets.

**Comment by academo** [comment]
@noseglid home path makes a lot of sense if you think about other plugins doing that, also, what about those projects with multiple folders from different paths (my case for instance)?

**Comment by C-Bouthoorn** [comment]
I also tried this in https://github.com/noseglid/atom-build/pull/211 , but that didn't work out well, as I created a new file containing both files. Currently I'm trying to do something with [atom-build-defaults](https://github.com/C-Bouthoorn/atom-build-defaults) (Already made files earlier, just pushed them), but it isn't working yet. I'll see what I can do with that, and will report back!

**Comment by academo** [comment]
@noseglid I haven't read the whole code but I see in `lib/atom-build.js` line 53 there is the `isEligible()` method, which is looking for the files to be parsed and it is reducing the scope of search to the specific cwd, if is easy as creating an alternative cwd with the user home path I can make a pull request when I get the moment to code the change

**Comment by C-Bouthoorn** [comment]
@academo Yeah, but *afaik* it tries to merge them, and that can have some weird effects when they have the same name for example. I've already tried such things on my own, and they worked until you actually added a `.atom-build.json` to the project, then it crashed :wink:

**Comment by academo** [comment]
@C-Bouthoorn maybe reduce the scope, first find the closest inside the project and fallback to the home directory.

**Comment by C-Bouthoorn** [comment]
@academo That's an option. Let me try something, and I will come back to it

**Comment by C-Bouthoorn** [comment]
```javascript
  isEligible() {
    this.files = [ '.atom-build.json', '.atom-build.cson' ]
      .map(file => path.join(this.cwd, file))
      .filter(fs.existsSync);
      
    if( 0 < this.files.length) {
      const atom = path.join(os.homedir(), '.atom', 'packages', 'build');
      
      this.files = [ '.atom-build.json' '.atom-build.cson' ]
        .map(file => path.join(atom, file))
        .filter(fs.existsSync);
    }
    
    return 0 < this.files.length;
  }
```

should in theory work. Don't forget to `import os from 'os';`!

**Comment by academo** [comment]
@C-Bouthoorn this code works for me and reads the build file from my home directory if there is none present in the project.

```
  isEligible() {
    this.files = [ '.atom-build.json', '.atom-build.cson' ]
      .map(file => path.join(this.cwd, file))
      .filter(fs.existsSync);
    if( 0 === this.files.length) {
      const atom = os.homedir();
      this.files = [ '.atom-build.json', '.atom-build.cson' ]
        .map(file => path.join(atom, file))
        .filter(fs.existsSync);
    }
    return 0 < this.files.length;
  }
```
remember the `import os from 'os' ` at the beginning of the file.

I can pull request a bit later or you can do it if is faster for you.

As a future update I would add a config option to the plugin so you can define your own global config file and this function can read it from there.

**Comment by noseglid** [comment]
@C-Bouthoorn I "just" fixed the issue with multiple names, partly with this feature in mind. Latest master will append `- 1`, `- 2` etc until all names are unique.

I think the build provider should always scan all paths (including the home dir) and concat all targets. Essentially it should be as easy as adding files to the array in `isEligible`.

**Comment by C-Bouthoorn** [comment]
@noseglid In that case, 

```javascript
isEligible() {
    const atom_path = path.join(os.homedir(), '.atom', 'packages', 'build');
    this.files = [ path.join(this.cwd, '.atom-build.json'), path.join(this.cwd, '.atom-build.cson'),
      path.join(atom_path, '.atom-build.json'), path.join(atom_path, '.atom-build.cson') ]
      .filter(fs.existsSync);

    return 0 < this.files.length;
  }
```
should work

@noseglid @academo Who will PR this?

**Comment by academo** [comment]
@C-Bouthoorn It should be `const atom_path = os.homedir()` instead of `const atom_path = path.join(os.homedir(), '.atom', 'packages', 'build');` if we want to look into the user homepath.

Or maybe I am getting the feature wrong and we want to look into ~/.atom/packages/build ?

**Comment by C-Bouthoorn** [comment]
@academo It should indeed be if we want to look in the home directory, but I think it's better if we keep things ordered in the atom-build folder.

**Comment by academo** [comment]
Maybe we can add atom build plugin folder and the home directory

**Comment by noseglid** [comment]
I don't think we should look in the atom package dir. This is atoms folder and may be removed or the structure may change

I think either directly in the homedir or in a subfolder directly under it 

Best would be if it were configurable. But that can be extended later

**Comment by academo** [comment]
@noseglid I agree with you, I am reading the test to be able to pull request and include my changes in the tests.

**Comment by noseglid** [comment]
Cool. We'd definitely want a test for that.

It may not be super straightforward to test it, but I think this should do it:

  1. Store the original home dir (e.g. a variable in the spec `const originalHomedirFn = os.homedir`.
  1. In the specs you are writing, create a new temporary directory (see how it is done in `beforeEach`)
  1. Override the `homedir` function, like so: `os.homedir = () => createdHomeDir;`
  1. In `afterEach`, reset the `homedir` function: `os.homedir = originalHomedirFn`.

**Comment by academo** [comment]
Here we go: https://github.com/noseglid/atom-build/pull/264

@noseglid @C-Bouthoorn please note I had to modify a lot of tests because of the method isElegible looking for config files in the home directory and founding it if have it.

**Comment by academo** [comment]
This feature is now implemented on master
