### ISSUE TITLE
Unable to execute with sh error

### ISSUE THREAD

**Issue by dabowheel** [noseglid/atom-build#214]
I get an unable to execute with sh error when trying to build.
OS is Windows 10
npm is in my path
This is my .atom-build.json config file.

{
  "cmd": "npm run build"
}

**Comment by dabowheel** [comment]
I tried an absolute path and it's not working
{
  "cmd": "C:\\Program Files\\nodejs\\npm.cmd run build"
}

**Comment by noseglid** [comment]
That's not good.

What if you try:
```
{
  "cmd": "npm",
  "args": [ "run", "build" ],
  "sh": false
}
```

and alternatively with the full path to `npm` in `cmd`?

**Comment by dabowheel** [comment]
I got it to work with this:
{
  "cmd": "npm.cmd",
  "args": ["run", "build"],
  "sh": false
}
