### ISSUE TITLE
:/usr/local/bin added to Windows path when plugin is enabled

### ISSUE THREAD

**Issue by dabowheel** [noseglid/atom-build#216]
:/usr/local/bin is added by my windows path when this plugin is enabled. This causes commands not to be found within Atom when they should. You can see the path by getting it in the console accessed by Ctrl-Alt-i.

process.env.path
"C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Brackets\command;C:\Program Files\PostgreSQL\9.4\bin;C:\Python27;C:\Program Files (x86)\PostgreSQL\9.4\bin;C:\php;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Calibre2\;C:\Program Files\MongoDB\Server\3.0\bin;C:\Users\Miguel\AppData\Local\atom\bin;C:\Users\Miguel\AppData\Roaming\npm:/usr/local/bin"

**Comment by dabowheel** [comment]
The problem is mainly assuming that the path delimiter is ":" when it can be ";" on Windows. Using path.delimiter in the Node path module instead of hard coding the delimiter would fix this.

**Comment by dabowheel** [comment]
Place in code where this happens:
$ grep "/usr/local/bin" . -r
./lib/build.js:    // Manually append /usr/local/bin as it may not be set on some systems,
./lib/build.js:    process.env.PATH += ':/usr/local/bin';

**Comment by noseglid** [comment]
That's a legacy thing from before Atom was supported on windows. It should definitely be removed (or at least only appended when running on Linux/OSX. Thanks for reporting!
