### ISSUE TITLE
request to support CLI_COLORs :-)

### ISSUE THREAD

**Issue by colin-kiegel** [noseglid/atom-build#217]
Some build tools support *colored output* like rust `cargo`. I gave this a try with atom-build, but the color seems to be ignored by atom-build.

@jhasse FYI

What I tried is the following:
* I changed args in lib/cargo.js from `test` to `test --color always -- --color always`. The duplicate flag is necessary due to https://github.com/rust-lang/cargo/issues/1983. But in atom-build these color codes are stripped somewhere along the way to the output panel. I only get _unformatted_ text as usual.
* However the command line it works nicely `cargo test --color always -- --color always | less` (color codes visible when piped to `| less`).

**Comment by jhasse** [comment]
I have a PR for Rust which would make this work: https://github.com/rust-lang/rust/pull/27867
After the pull request if `CLICOLOR_FORCE` is set to `1`, rustc will display the correct color codes for atom-build.
I wrote some of it down here: http://bixense.com/clicolors/

> But in atom-build these color codes are stripped somewhere along the way to the output panel. I only get unformatted text as usual.

Maybe this has something to do with #159?

**Comment by colin-kiegel** [comment]
Hmm .. I disabled autoscrolling, but still don't get colored output. If I understand noseglid correctly CLI_COLORs are currently *not* supported - so even if colored output would be improved on the rust side by rust-lang/rust#27867 atom-build could not deal with it right now (if I understand correctly).

**Comment by jhasse** [comment]
They are definitely supported (on Linux)! I'm using it with cmake for example. Have you tried something simple like `echo -r "\x1b[1;31mred" `?

**Comment by jhasse** [comment]
![bildschirmfoto vom 2015-10-30 16-39-59](https://cloud.githubusercontent.com/assets/80071/10850260/e6813762-7f24-11e5-821a-9a14727d20ea.png)

**Comment by colin-kiegel** [comment]
This is *strange* - but you are right, your python code produces colored output. It seems to be some strange cargo bug - if I write colored output of cargo into a file and `cat` that into atom-build it prints colors. Looks like cargos --color flag doesn't work when called from atom-build. Just weird.

**Comment by jhasse** [comment]
Can you try only rustc with the `--color` flag?

cargo handles colors a little differently from rustc afaik.

**Comment by noseglid** [comment]
@colin-kiegel The reason is probably that cargo (like most applications) determine if there is a tty connected to stdout. If it is not (which is the case when piping data into `cat`, or run via `build`) cargo will not print colors.  Very often there are switches which enable colors (maybe `--color` as suggested by @jhasse .

**Comment by evmorov** [comment]
I had a similar issue with RSpec. You should call it `rspec --tty` to have colors.

**Comment by placrosse** [comment]
Could an option, similar to that for --verbose, be added so cargo output is forced to emit the colors?

**Comment by noseglid** [comment]
This should be opened on the build cargo repo

**Comment by alygin** [comment]
The PR for build-cargo: https://github.com/AtomBuild/atom-build-cargo/pull/57
