### ISSUE TITLE
error matches can overlap

### ISSUE THREAD

**Issue by oli-obk** [noseglid/atom-build#222]
If one specifies two error regexes that can overlap, both are matched on, and in the area of overlap it's unclear which one will be called when clicked. This happen in build-cargo when a thread panics. The thread panic error message contains two different links (one of them doesn't work).

**Comment by noseglid** [comment]
Could you please provide some sample output, and the regex you're using which demonstrates this issue?

**Comment by oli-obk** [comment]
a sample output would be this line:

```
thread 'rustc' panicked at 'bla', src/lib.rs:38
```

and the regex is the one from `build-cargo`:

```javascript
[
    '(?<file>.+.rs):(?<line>\\d+):(?<col>\\d+):',
    'at (?<file>[^.\/][^\\/][^\\:]+):(?<line>\\d+)',
    'thread \'[^\\\']+\' panicked at \'[^\\\']+\', (?<file>[^\\/][^\\:]+):(?<line>\\d+)'
]
```

I think it's the last two regexi overlapping.

**Comment by noseglid** [comment]
No longer an issue since #330
