### ISSUE TITLE
matched errors should not change the build status

### ISSUE THREAD

**Issue by dirk-thomas** [noseglid/atom-build#224]
If the invoked build tool returns with a code of 0 the error matching should not change the build result to *failed*. If this doesn't seem reasonable as a default there should be an option to switch the behavior.

**Comment by noseglid** [comment]
This was actually added in #144 . I suppose an option to control this is in order.

**Comment by dirk-thomas** [comment]
I commonly trust by build tools return code more then the regular expression which might match if the output e.g. "by accident" contains a certain string. It would be great there would be an option for this to choose the desired behavior.

**Comment by noseglid** [comment]
fixed in #224
