### ISSUE TITLE
support to match warnings

### ISSUE THREAD

**Issue by dirk-thomas** [noseglid/atom-build#225]
Similar to the error matching but without marking the build as failed (related to #224).

For cycling through logic (`ctrl-alt-g`) it could first go through all errors and then go through all warnings.

**Comment by noseglid** [comment]
So, if an option is included where you can control whether or not a matched "error" fails the build, would this still be necessary?

**Comment by dirk-thomas** [comment]
With the additional option this would for sure be less important. The only inconvenience would be if a build has many builds but only a single error that it might be difficult to jump to the important error.

With a separate set of regex for warnings the logic could be smarter as mentioned before.

**Comment by noseglid** [comment]
I think this makes more sense when the linter integration ( #251 ) is complete. The linter already has the notion of warning vs errors and a nice display of them, with skip-to and click functionality.

I don't think we should add support for moving between warnings in vanilla error matching.

**Comment by dirk-thomas** [comment]
Sounds good to me.

**Comment by NuclearCookie** [comment]
#251 has been dropped in favor of #354. Do you still plan on adding warning support now that it's done?
Thanks

**Comment by noseglid** [comment]
Absolutely. Just need to figure out a nice way to do it. I haven't given it much though yet. If you don't mind, could you please open an issue where we can track it?
