### ISSUE TITLE
Regex matching documentation not clear

### ISSUE THREAD

**Issue by jspashett** [noseglid/atom-build#227]
It's not clear/I can't work out how to match the error message in the output (below) it picks up the previous output lines too and marks them all as the error -- becuase of the \n at the start of the match no doubt. I tried an anchor to start of line ^, but it does not appear to work at all in that case.

More examples would be most helpful.
```
"errorMatch": [
    "\n(?<file>[^(]+)\\((?<line>[0-9]+),(?<col>[0-9]+)\\):\\s+Error.*"
  ]
```

```
Executing: dub  build -q

## Warning for package gltest ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

unittests: Call DUB with --build=unittest

missing.d(13,3): Error: semicolon expected following function declaration
```

**Comment by noseglid** [comment]
`build` uses [XRegExp](http://xregexp.com/) to match the content of the output.

I'm thinking you want something like: http://regexr.com/3c8b9 (with the appropriate namings (e.g `?<file>`, etc) inserted.

**Comment by jspashett** [comment]
Unfortunately the regex you showed me is more or less the same as what I wrote, but it doesn't always work. It seems to break when there is only one error output line, plus the other build output; and it works properly only when there is more than one error in the output.

It seems to be because the /m multiline flag just matches all lines and I can't think of a way to stop it at the moment.

I tried ^ at the start instead of \n, but that doesn't help either.

With this:
```
 "errorMatch": [
    "\n(?<file>[^(]+)\\((?<line>[0-9]+),(?<col>[0-9]+)\\):\\s+Error.*"
  ]
```
I get this -- notice the underline. There is nothing I can find to make it just grab the error line alone.

![error line captures too much](http://snag.gy/zp0l9.jpg)

**Comment by noseglid** [comment]
Error matcher is not setting the multiline option, altough maybe it should.

What about this regex: `\n(?<file>.+\.d)\((?<line>\d+),(?<col>\d+)\)` ?

**Comment by jspashett** [comment]
I have found a solution it is this:
```
  "errorMatch": [
    "\n(?<file>[^(\n]+)\\((?<line>[0-9]+),(?<col>[0-9]+)\\):\\s+Error[^\n]+\n"
  ]
```

Changed the file name capture to add an additional \n preventing multi line matches:

[^(\n]+

That works. The mult-line must be on already no?

**Comment by noseglid** [comment]
Well, `/m` makes `^` and `$` match newlines. Without it, the whole output is considered one string.

I'm glad you got it to work.

**Comment by jspashett** [comment]
Would you consider adding a set of pre-defined error matching filters, something like this:

"errorMatchLang" : ["dlang-dmd2"]

where dlang-dmd2 is maps to a built in regex?

Or even, this, which might be too much:
"errorMatchLang" : ["http://anywhere.com/dlang-dmd2.regex"]

I just see that a lot of people are going to go though the same thing trying to get their output to match.

**Comment by noseglid** [comment]
I think the best solution to this would be creating a [build provider](https://github.com/noseglid/atom-build#service-api-for-package-developers) which includes the regex

**Comment by jspashett** [comment]
On 19/11/15 13:21, Alexander Olsson wrote:
>
> I think the best solution to this would be creating a build provider 
> <https://github.com/noseglid/atom-build#service-api-for-package-developers> 
> which includes the regex
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/noseglid/atom-build/issues/227#issuecomment-158054870>.
>
I see yes. Thank you. I will look into that.
