### ISSUE TITLE
Error match output with different `cwd` per match

### ISSUE THREAD

**Issue by KamilSzczygiel** [noseglid/atom-build#228]
Some build tools execute compiler from many various paths. For example tup ( https://github.com/gittup/tup ) executes the compiler from the folder of currently parsed Tupfile, which means that in a project with multiple Tupfiles (typical scenario - in the project used as example I have 22 of them), the compiler will be invoked from multiple folders. Thus it is not possible to just set one `cwd`, which means that error parsing will not work. An example build output (slightly edited to remove useless compiler flags) with error message looks like this:

```
*  43% 1) test/Queue: arm-none-eabi-g++  [...]  -c QueueWrappers.cpp -o ../../output/test/Queue/QueueWrappers.o
QueueWrappers.cpp: In member function 'virtual int distortos::test::FifoQueueWrapper::emplace(uint8_t, distortos::test::OperationCountingType::Value) const':
QueueWrappers.cpp:58:1: error: expected ';' before '}' token
 }
 ^
 *** tup errors ***
 *** Command ID=835 failed with return value 1
tup error: Expected to write to file '../../output/test/Queue/QueueWrappers.o' from cmd 835 but didn't
 *** Additionally, command 835 failed to process input dependencies. These should probably be fixed before addressing the command failure.
 *** tup: 1 job failed.
```

The full path of file (relative to project root) is test/Queue/QueueWrappers.cpp. In this case compiler was run from test/Queue/ folder, but in the whole build process it is run from dozen of different folders. Thus I think it is not possible to actually use current error matching method.

The first idea I had was to introduce another match-group - &lt;cwd&gt;, which could easily be parsed from the error above (assuming the package allows parsing multiple-lines with single regex) - the final path to file would then be "&lt;cwd&gt;/&lt;file&gt;".

I guess the same issue would be present with recursive Makefiles, but it couldn't be solved like that. In that case maybe it would be possible to allow `cwd` variable to be a regex? This could also solve the issue with parsing of tup output.

Would it be possible to implement something like this? Maybe such error is possible to parse with current version of the package?

**Comment by jhasse** [comment]
What do you think about adding a new `cwdMatch`? This would work with recursive Makefiles and leave the `cwd` variable intact.

**Comment by Emilgardis** [comment]
Having the same problem in `gnu make` when running make from project root. 

[Origin of bug](https://github.com/noseglid/atom-build/blob/859aaca93323d512bc853b667629a56f4a92b440/lib/error-matcher.js#L49) (Atleast for me)

Since the builder is not in `CWD` anymore, eg. `make -C otherdir`, `CWD `should now be `otherdir`.

**Comment by oli-obk** [comment]
This should be doable with the new function matches ([documented here](https://github.com/noseglid/atom-build#programmatic-build-commands-javascript)). There's an example with some basic makefile output, but it can easily be extended to more complex situations.

**Comment by noseglid** [comment]
Spot on, @oli-obk . The example is even for Make, but that should be directly applicable to use cases in here!
