### ISSUE TITLE
No eligible build target

### ISSUE THREAD

**Issue by colin-kiegel** [noseglid/atom-build#230]
atom-build stopped working for my rust projects after upgrading atom and all packages.

It gives me the message: No configuration to build this project exists. Before the updates it had worked fine. What could be the problem atom-build-cargo still is installed. I even tried a project with a custom .atom-build.json without success.

**Comment by colin-kiegel** [comment]
The problem occurred somewhere in-between the last three weeks, i.e. 2015-11-01 and 2015-11-21.

Is there any information I can collect to help find this bug?

**Comment by noseglid** [comment]
Could you try to restart atom?

**Comment by colin-kiegel** [comment]
I did some tests with both _existing_ and _new_ rust projects and atom-build. I found some *very weird* behaviour, which I am able to reproduce very consistently now:

1. New projects work fine the _first time_
 * create new project (e.g. `cargo new dummy_library`)
 * start atom + open project
 * Result: Notification: build targets are detected. It would actually build - but I just close atom without any changes to the project to continue ..
2. Projects stop working the _second time_
 * restart atom + reopen unchanged project from before
 * Result: atom-build does not detect any build targets anymore and is unable to build
3. Renamed projects work again for exactly one time
 * `mv dummy_library dummy_library2`
 * start atom + open renamed project
 * Result: ... same as (1. + 2. again), it will work exactly once
4. Delete + Recreate doesn't work
 * close atom
 * after (2.) delete project and create new dummy project
 * start atom
 * Result: Although all project files are definitely fresh, atom-build can't detect build targets.

Very strange.

My workaround will be to constantly rename the projects I am working on - and not close atom, if I don't need to. :-)

**Comment by colin-kiegel** [comment]
Update: After disabling all packages except atom-build + atom-build-cargo, I can't reproduce it anymore. Must be one of X packages - trying to find out which one.

**Comment by colin-kiegel** [comment]
Ok, after countless restarts of atom, I could boil it down to this

NOT-OK: build, build-cargo, linter, *linter-php*
OK: build, build-cargo
OK: build, build-cargo, linter, linter-rust
OK: .... basically every combination unless I combine it with *linter-php*

I have no idea what's going on - because I am having problems with non-php-projects here. Not even sure if its a atom-build bug or linter-php. Anyway - this is how far I got with my analysis. Now, I am able to work again (new workaround: disable linter-php). But it was not easy to figure out. If there is a way to give a more detailed error message, I would definitely appreciate it. :-)

**Comment by noseglid** [comment]
If you end up in state where it does not detect any build targets, do you get the notification that says `0 targets parsed..` ?

You can also manually trigger a refresh of targets by opening the command palette and issuing `Build: Refresh Targets`. Does that work on a "broken" project?

**Comment by colin-kiegel** [comment]
* No, I don't get any notification about build targets if I enable *linter-php*.
* Yes, "Build: Refresh Targets" repairs it. :-)

Thanks, the workarounds are already getting better. ^^

**Comment by jhasse** [comment]
I can confirm this. I'm also having the exact same problem and disabling linter-php fixes this.

**Comment by kepler0** [comment]
`linter-php` shouldn't be any different from any other linter provider...

Does the same occur with other linter providers installed and activated?

**Comment by colin-kiegel** [comment]
No, I tried two other linters, they didnt cause this.

Kepler Sticka-Jones <notifications@github.com> schrieb am Mo., 23. Nov.
2015, 06:55:

**Comment by noseglid** [comment]
I'll write this off as not a build bug since there has been no other reports. If this issue re-appears. Please re-open this issue (or open a new one).

**Comment by jhasse** [comment]
@noseglid Have you tried to reproduce this by installing linter-php?

**Comment by colin-kiegel** [comment]
A workaround *could* be to parse targets automatically if build is triggered and no targets are registered. Or to always delay parsing targets until build is triggered. (..Just thinking out loud..)

**Comment by noseglid** [comment]
@jhasse No I have not.

@colin-kiegel Some build providers take a long time to parse targets (For gradle it can take up to 10 seconds). Doing it when build is triggered is really not feasible.

**Comment by coriolinus** [comment]
@noseglid As I just encountered the same issue, I'm generally in favor of the suggestion to parse targets automatically if the build is triggered with no targets registered. Even with gradle taking 10 seconds, that should only be a one-time cost. That feels relatively painless compared to the experience of a mysterious failure which clears up only after one finds this thread. :)
