### ISSUE TITLE
keymap bug since last update?

### ISSUE THREAD

**Issue by NuclearCookie** [noseglid/atom-build#239]
Hi,

I have the following `.atom-build.json` file
```json
{

  "cmd": "make",
  "name": "linux-debug",
  "args": [ "-j8" ],
  "sh": false,
  "cwd": "{PROJECT_PATH}/CODE/APP/LINUX/",
  "env": {
  },
  "errorMatch": "\n(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):(?<col>\\d+)",
  "keymap": "f7",
  "targets": {
      "linux": {
        "cmd": "emmake",
        "name": "emscripten-debug",
        "args": [ "make", "config=debugcanvas_emscripten", "-j8" ],
        "sh": false,
        "cwd": "{PROJECT_PATH}/CODE/APP/EMSCRIPTEN/",
        "env": {
        },
        "errorMatch": "\n(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):(?<col>\\d+)",
        "keymap": "f8"
      }
  }
}
```

Since the `emscripten-debug` task is the one I need the most, I mostly build with f8.
Since I updated the plugin, f8 didn't build my project anymore. It showed the output window, but nothing happened. If I went into the command browser and selected the correct `build:trigger`, everything worked as expected. 

The keybinding didn't work until I pressed f7. Then a dialogue popped up asking me what target I wanted to build: `linux-debug` or `linux`. 
From then on, I can use f8 every time.
Any idea? 

Edit: Issue was not resolved after choosing target with f7. Build always triggers when starting it from the command browser.

**Comment by noseglid** [comment]
Could it be that f7 and f8 now are part of the default keymaps?

```
cmd-alt-v / ctrl-alt-v / f8 Toggles the build panel.
cmd-alt-t / ctrl-alt-t / f7 Displays the available build targets.
```

**Comment by NuclearCookie** [comment]
Oh yeah, that's exactly the behaviour i'm experiencing. Although my
.atom_build explicitly sets those keys.. any idea why they are not applied?
Seems to me that it should be overriden, no?

**Comment by noseglid** [comment]
They are applied, only they have less [specificity](https://atom.io/docs/latest/behind-atom-keymaps-in-depth#specificity-and-cascade-order) as the built-in ones. I think we can updated the customized keymaps to the same specificity, and they should take precedence. Let me get a PR ready and I'd love for you to try it out and see if it solves your problem.

**Comment by NuclearCookie** [comment]
Thank you!

**Comment by noseglid** [comment]
Can you test PR #249 and see if it works for you?

**Comment by NuclearCookie** [comment]
That works! Perfect :)

**Comment by noseglid** [comment]
Cool. I'll merge that! Thanks for the report and help testing
