### ISSUE TITLE
command line output in cp866

### ISSUE THREAD

**Issue by Ser0ja** [noseglid/atom-build#241]
![image](https://cloud.githubusercontent.com/assets/5020923/11394342/78af5d6c-9375-11e5-8424-c32a1ba03252.png)

**Comment by noseglid** [comment]
Does atom work in general with those characters?

**Comment by Ser0ja** [comment]
yes. problem only with parsing cyrillic characters from windows command line. 
executeShell("chcp 65001"); - It solves the problem of the output these characters from the code, but the error output is still in the cp866

**Comment by noseglid** [comment]
Do CP866 work if you input them into an atom TextEditor?

**Comment by Ser0ja** [comment]
i dont know. I am working with utf-8 in code. only windows cmd output in cp866 by default.
screenshot...
1. copy characters from cmd to atom
2. atom parse characters from cmd
3. visual cmd output 
![image](https://cloud.githubusercontent.com/assets/5020923/11588546/7996da10-9a92-11e5-8521-2106f1e201a3.png)

**Comment by Ser0ja** [comment]
atom-build output in utf-8? maybe choose output encoding in atom-build (utf-8 or cp866)

**Comment by noseglid** [comment]
Hmm. So I guess the problem originates from here: https://github.com/noseglid/atom-build/blob/master/lib/build-view.js#L235

Since the output really is not UTF-8.

I did some quick googling and found [another issue on node](https://github.com/nodejs/node-v0.x-archive/issues/2190). Do any of those work-around help you?

**Comment by Ser0ja** [comment]
ok thank you

**Comment by Ser0ja** [comment]
it is not a is not the way.
maybe something like "cmd" : "chcp 65001 | D:\\Dropbox\\dmd2\\windows\\bin\\dmd.exe" in .atom-build.json

**Comment by noseglid** [comment]
Yes. Some way to get the output into `utf8` is probably the best solution. `build` just assumes it is UTF-8 since there is no way to detect it from the executed command alone.
