### ISSUE TITLE
Passing an argument from config

### ISSUE THREAD

**Issue by tschf** [noseglid/atom-build#242]
I'm working on an extension utilising the build system - I'd like one of the arguments to come from a configuration item I've set up. Just wondering if there's a good way to get it to use the configuration `atom.config.get('myPkg.myProperty')` item at run time, rather than the value when the build is initially loaded.

I've seen the example you have in [`atom-build-gradle`](https://github.com/AtomBuild/atom-build-gradle/blob/master/lib/gradle.js#L85-L111) for reloading the config using the `on` callback. Was attempting to use the config observer, not with huge success so far - so thought I'd see if there was a better way?

The settings looks like:

```js
thisConfig.args = [atom.config.get('myPkg.myProperty')];
```

**Comment by tschf** [comment]
Ended up just implementing as:

```js
this.sqlPathObvserver = atom.config.observe('build-oracle.sqlPath', (val) => {
    //first call, assign the current setting value
    if (!(this.sqlPath)){
        this.sqlPath = val;
    } else {
        //only if its changed should we `refreshTargets`
        if (this.sqlPath !== val){
            this.sqlPath = val;
            evtCallback();
        }
    }
});
```

**Comment by noseglid** [comment]
Is that in the `on` callback?
Make sure you `dispose` the returned value from `atom.config.observe` in the off callback.

Also, if you want to share the build provider, please make the appropriate changes on [AtomBuild/atombuild.github.io](https://github.com/AtomBuild/atombuild.github.io)

**Comment by tschf** [comment]
Yeah, I had the `dispose` set up in the off callback.

Will get around to sharing the provider. I haven't published it to apm yet - I've got it mostly working now, but I just need to do some more testing on different platforms. I think there are some environment vars that need to be set on OS X when using `sqlplus` as the interpreter (and the other newer interpreter `sqlcl` is a bit slow to build on some instances due to it needing to start the jvm each time).
