### ISSUE TITLE
Build does not work on subpaths using symbolic links

### ISSUE THREAD

**Issue by dirk-thomas** [noseglid/atom-build#245]
This is very similar to the previous ticket #55. The applied fix only works if the project root is the symlinked path. But if the project root contains a subfolder which is the symlink the problem is still the same. The steps to reproduce (adapted from the previous issue):

**Updated**
```
/tmp$ mkdir test
/tmp$ mkdir test/sub
/tmp$ mkdir prjroot
/tmp$ ln -s /tmp/test/sub prjroot/sub_link
/tmp$ cd test
/tmp/test$ cat > .atom-build.json
{
  "cmd": "cat",
  "args": [ "{FILE_ACTIVE}" ],
  "sh": false
}
/tmp/test$ cp .atom-build.json ../prjroot/
/tmp/test$ cat > sub/whatever.abc
Hello World!
/tmp/test$
```

When atom is started from `/tmp/test`, and I try to build whatever.abc using "Ctrl+Alt+b" everything works as expected. However if atom is started from `/tmp/prjroot` it doesn't do anything. In other words:

This works:

    /tmp/test$ atom .

This doesn't:

    /tmp/prjroot$ atom .

**Comment by noseglid** [comment]
Ah, it probably needs to check realpath. Thanks for the report.

**Comment by dirk-thomas** [comment]
I am not sure if a fix will be as easy as the previous one. The problem is that the `TextEditor` instance seems to only provide the real path of the file. Without knowing the non-realpath of the open file I am not sure how it should be mapped to any of the non-synlinked project roots.

**Comment by noseglid** [comment]
Hmm, did you mean:
```
/tmp/prjroot/test_link$ atom .
```
instead of 
```
/tmp/prjroot$ atom.
```

Because that works for me. The reason `/tmp/prjroot` doesn't work is since `.atom-build.json` is not in the root folder of the projects. It is in the path `test_link/.atom-build.json`.

**Comment by dirk-thomas** [comment]
The example was actually not correct. Both the `test` folder as well as the `prjroot` folder should have the `.atom-build.json` file. I have updated the steps to reproduce in the description.

**Comment by noseglid** [comment]
I see. Indeed you are correct. We get the resolved path from `TextEditor#getPath`. without a change to that behavior it will be difficult to solve this.

Is this a real life problem for you or just something you stumbled upon?

**Comment by dirk-thomas** [comment]
This is actually something I ran into with a real project. I often have a root project path in which I symlink multiple repos I have cloned somewhere else. Mostly because I have many root project paths and only want to to have a single clone of each repo. So basically the root project path acts as a set of repos I am working on for some time.

I am not sure where to bring up the questions if `TextEditor` could have a function to return the non-real path. But that would certainly be required for a clean fix. Any idea how to get the Atom developers considering this? I could file an issue at https://github.com/atom/atom/issues but I am not sure if we get their attention with that number of open tickets...

Without that I could only imagine a heuristic to try to figure out which non-real path the text editor instance is referring to. If we would ignore the case where a file A is symlinked into the project as file B and only consider symlinked folders we could do the following:

* for all files in all project which have the filename as the current text editor
  * check if their real path is equal to the text editor path

Depending on how many files with the same filename exist on the projects this could obviously be an expensive operation.

**Comment by noseglid** [comment]
I'd definitely say you should open an issue. I really don't think TextEditor.getPath should give the resolved path. If I want the resolved path I can easily pass it thorugh `fs.realpath`.

**Comment by dirk-thomas** [comment]
I have created atom/atom#9879. Lets hope for some response there.

**Comment by noseglid** [comment]
I will close this as it is tracked in atom/atom#9879.
