### ISSUE TITLE
Custom keybinding for build targets

### ISSUE THREAD

**Issue by Giah** [noseglid/atom-build#252]
I know there is a shortcut for switching between build targets. However It would be great to have the possibility to associate custom keybinds to specific targets. This would allow you to instantly access the most frequent used target.

**Comment by noseglid** [comment]
You can design an `.atom-build.json` for this. Does that solve your issue?

**Comment by Giah** [comment]
Hi noseglid,  thank you for answering. I have my atom-build file configured with two buid targets. I usually hit ctrl+alt+t to select the current target, and then ctrl+b to build.  I was looking for a way to associate a keybind to each one of the build targets.

**Comment by noseglid** [comment]
So the `keymap` entry should suit you well. Please refer to [the documentation for the custom build file](https://github.com/noseglid/atom-build#specifying-a-custom-build-command).

**Comment by Giah** [comment]
Thanks very much, I must have missed that option when I read the documentation.
