### ISSUE TITLE
[Feature Request] Display current build target name in status bar.

### ISSUE THREAD

**Issue by xpol** [noseglid/atom-build#253]
* Display current build target name in status bar.
* Best with a icon, sth like: :hammer: make
* When the target name clicked, show the target list, select target here will not trigger build, just change the current build target.

**Comment by noseglid** [comment]
I've actually been thinking about this. Makes total sense. Thanks for the suggestion

**Comment by noseglid** [comment]
I've made a first implementation of this on the branch `status-bar-integration`. If you want to give it a whirl and let me know if it matches your expectations!

**Comment by xpol** [comment]
@noseglid 
Awesome!

**Comment by xpol** [comment]
@noseglid 
Just tested, Its pretty good!

I'd suggest the follow:

1. When the target name clicked, show the target list (not the same as `cmd+alt+t`), **select target here will not trigger build, just change the current build target**.
2. I'd prefer it shows on the right side of status bar (Linter already taken the left side) or have a config otpion.

**Comment by xpol** [comment]
And I changed the priority to 1000, I think is better, :smile: .

**Comment by noseglid** [comment]
@xpol I added a configuration which allows you to set if selecting a target via the select list should also trigger the build. It modifies the behaviour of both clicking the status bar and `cmd-alt-t`. Did you check that out?

**Comment by xpol** [comment]
@noseglid 
Can we separate the 2 case?

* cmd-alt-t -> click -> triggers command running
* click statusbar -> not trigger command

:smiley:

**Comment by noseglid** [comment]
Why do you want different things to happen depending on where you open the target view from? I think that feels counter intuitive and inconsistent; "Sometimes it build when I select a target, sometimes it doesn't".

**Comment by xpol** [comment]
You are right. My idea is too complex for user to understand.
