### ISSUE TITLE
Adding option to build on save

### ISSUE THREAD

**Issue by citosid** [noseglid/atom-build#26]
Would be very useful to add a option to automatically build on save

**Comment by citosid** [comment]
any news? I'm new at both, node and atom.io.

If you could give me a clue on how this can be done, I would be able to help you ;)

**Comment by noseglid** [comment]
I'm sorry. I've been really strapped on time lately and haven't gotten around yet.

If you'd like, you could look at the [Atom API documentation](https://atom.io/docs/api) and find an event which is sent every time a TextEditor is saved. Then register a listener of that event.

Then create a new config variable (`Automatically build on save` - boolean default off)

When the event arrives, you should check the config variable. If it is set, trigger the build command (e.g. dispatch 'build:trigger').

**Comment by sryze** [comment]
Hey, I'm kind of a noob in Atom too. I attempted to implement this in https://github.com/sryze/atom-build/commit/cc7d29046af8b99974da767e2956bec78e0eacbe but it's not working for some reason - the `build:trigger` command is not dispatched at all, I've no idea why...

**Comment by noseglid** [comment]
@sryze Thanks for the effort!

I think it needs the actual dom element in dispatch (something like `workspaceElement = atom.views.getView(atom.workspace);`. You can have a look at the specs how I dispatch build:trigger there.

Also, don't forget to implement some specs for the functionality so we can guarantee the functionality.

**Comment by sryze** [comment]
That worked, thanks.

As for the specs, should I create a separate file for this option like it's done for `keepVisible`?

**Comment by sryze** [comment]
https://github.com/sryze/atom-build/commit/95e966dfa5365faef441122e8c940987d3eb6029

Does this look good?

**Comment by noseglid** [comment]
@sryze The spec itself looks good.

It might be worth just putting it in `build-spec.js` to avoid having to duplicate beforeEach and afterEach functionality.

**Comment by citosid** [comment]
First of all, thanks for adding this option...
However is not working for me :(

This is my configuration file:
```javascript
{
    "cmd": "{PROJECT_PATH}/build.sh",
    "sh": true,
    "cwd": "{PROJECT_PATH}",
    "build": {
        "buildOnSave": true
    }
}
```
I've been trying adding the builOnSave outside the build declaration, and is not working either...

**Comment by sryze** [comment]
@citosid It's a global option, so it goes to your Atom config.

**Comment by noseglid** [comment]
You can also configure it in the setting panel of atom. Might be easier.
