### ISSUE TITLE
Ability to pass additional args to comand

### ISSUE THREAD

**Issue by nixel2007** [noseglid/atom-build#261]
hi there!

I think that your package will be more cool, if it will have an ability to set and pass to build-system some args, like "python.exe my_scrypt.py arg1 arg2". 
Can you add some fillable form like the one in [script](https://github.com/rgbkrk/atom-script) package (press ctrl+shift+alt+O to open it)?

It will be really usefull!

And thank you for you work, `build` is really good package.

**Comment by noseglid** [comment]
You could create a [custom build configuration](https://github.com/noseglid/atom-build#specifying-a-custom-build-command). Does that suit your needs?

**Comment by nixel2007** [comment]
Technically - yes. But then if you need to edit this args you edit that `.atom-build.json`. And of course it requires to create of a file itself, which is inconvenient.
I'm making a simple custom build provider (you can find it [here](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/feature-oscipt-runner/lib/main.js) if you interested). 
I think I could do some magic with setting args in some custom window, saving args in my package in variable and pass it dynamically, but (imho) it is a frequently used functionality, and it makes sense to add it into the main `build` package

**Comment by noseglid** [comment]
I don't think this fits very well with the general setup. None of the existing build providers have had a need for this.

You can always add configurations and/or other ways of setting additional arguments in your build provider.

If more providers require this, I'm open to discussing it again. But for now I will close this.

**Comment by codetender** [comment]
hi, @noseglid. Thanks for your work.  As a newcomer to atom,  I think additional arguments can be very handy. For instance, when developing Elixir application, I am used to use mix test --only line:$line_number to run the closet test. It is quite helpful especially when I want to focus on **one** test. If additional arguments is supported, I can pass the current line number under cursor or anything I need directly to `build`

**Comment by oli-obk** [comment]
@codetender would an additional `{FILE_LINE}` replacement (see https://github.com/noseglid/atom-build#replacements for other replacements) help you? Then you could write a build provider that takes the current line and passes it directly to the call args

**Comment by codetender** [comment]
@oli-obk Thanks for your reply. In this case, yes. But If there is a more generalized solution, it would be very convenient :)

**Comment by jcrben** [comment]
If I'm building a command-line tool, it would be elegant for me to do a build and pass arguments at the same time - is that possible? I'm talking about something like https://github.com/bilalba/InputArgs for Sublime

**Comment by black-snow** [comment]
Really? No (easy) way to pass args to the targets?
