### ISSUE TITLE
Java build yields Failed to Build and Cannot read property 'exec' of undefined

### ISSUE THREAD

**Issue by chaoaj** [noseglid/atom-build#269]
When building a .java file using Command-b on my mac using the native Build Package I'm getting a 
"Failed to Build" and Cannot read property 'exec' of undefined. Anyone able to give me advice?

Note: When I run this same code with the Script Package using Command-i this works fine.

**Comment by noseglid** [comment]
What does your build file look like?

**Comment by chaoaj** [comment]
I don’t know that I have one.  I was assuming this would work like the Script Package builder and automatically build for Java doing a javac of the filename.java then java of the class name/filename minus extension.

@lvin
------------------------
Alvin Chao – IT Web
JMU - MSC 5734  - Massanutten Hall 293
Harrisonburg, VA 22807
540-568-6206
Chaoaj@jmu.edu
http://educ.jmu.edu/~chaoaj

**Comment by noseglid** [comment]
There should be some sort of configuration otherwise the package would not activate. So it's finding something. What files do you have in the root of you project directory?

It does work automatically for some providers, and more added all the time. Check out [atom build page](https://atombuild.github.io)

**Comment by noseglid** [comment]
Thank you for this report. I've managed to locate the issue and should have it fixed in the next release.

There actually was [a test for this condition](https://github.com/noseglid/atom-build/blob/master/spec/build-spec.js#L434-L452), but it had unfortunate timings. I've fixed that too.
