### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\lucawen\AppData\Local\atom\app...

### ISSUE THREAD

**Issue by lucawen** [noseglid/atom-build#273]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.52.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\lucawen\AppData\Local\atom\app-1.3.2\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\lucawen\AppData\Local\atom\app-1.3.2\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at C:/Users/lucawen/.atom/packages/build/lib/build.js:217:27
    at Array.find (native)
    at Object.activePath (C:/Users/lucawen/.atom/packages/build/lib/build.js:216:74)
    at Object.updateStatusBar (C:/Users/lucawen/.atom/packages/build/lib/build.js:223:49)
    at C:/Users/lucawen/.atom/packages/build/lib/build.js:158:57
    at Emitter.module.exports.Emitter.emit (C:\Users\lucawen\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\lucawen\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (C:\Users\lucawen\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\lucawen\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\lucawen\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\lucawen\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
     -0:00.2.0 build:trigger (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {},
  "build": {}
}
```

### Installed Packages

```coffee
# User
build, v0.52.0
language-arduino, v0.3.1

# Dev
No dev packages
```

**Comment by C-Bouthoorn** [comment]
1) What did you do when you got this error ?
2) What version of Windows do you have ?
3) Does this also happen with Atom disabled ?

**Comment by noseglid** [comment]
What project root folders do you have open?

**Comment by lucawen** [comment]
Try to open a script in C, but not work.... Windows 10. When i disable, its ok!

**Comment by noseglid** [comment]
I'm but you will have to be more detailed. What do you mean by "a script in C"? This doesn't make any sense. What is open in Atom when you build? What does the Tree-View show? Exactly what is happening. Please include screenshots

**Comment by C-Bouthoorn** [comment]
@lucawen Also, please post your .atom-build.json or .atom-build.cson file.

**Comment by lucawen** [comment]
When I go to the tab of this script, it shows this error. The Script is something very simple. I managed to compile the Visual Studio.

**Comment by noseglid** [comment]
What project root folder do you have open? Could you provide a screenshot of your full Atom editor?

**Comment by DevilSauron** [comment]
Yes I can confirm this (as in my own report). I get this error every time I try to build and when I run atom.io

**Comment by noseglid** [comment]
What are you trying to build? What does the root project look like? Are you using a build provider? Which one? Are you using a custom build file? What does it look like? Please try and include as much information as possible if there should be any chance to get this resolved.

**Comment by DevilSauron** [comment]
I have fixed the problem. It was a stupid mistake. Since I am learning Rust and it was my first program, I forgot to set up the project with cargo...

**Comment by noseglid** [comment]
so what did you change to resolve it?

**Comment by lucawen** [comment]
I gave up to use, but this issue is to improve the software and help to not make this problem in the future. Great job!

**Comment by DevilSauron** [comment]
I simply created cargo app... I thought this plugin can call rustc so I didn't create cargo app before.

**Comment by bottiger** [comment]
@noseglid Do I have a root project open? I guess not, I have honestly no idea since I never worked with atom before, but I don't think I do

**Comment by noseglid** [comment]
Is there a tree-view of folders and documents on the left? If not, then you don't have one open. I suspect this has something to do with that, but only seems to happen on windows for some reason.

**Comment by bottiger** [comment]
@noseglid There is, but the tree is also empty.

![capture](https://cloud.githubusercontent.com/assets/489129/12262306/6a717a46-b927-11e5-9eaa-81ba43878237.JPG)

Since it's obviously both filesystem and windows related I would suspect it has something to do with the breaking on paths with spaces, special characters, backslash or similar things.

**Comment by noseglid** [comment]
Yea. it's weird. As if node doesn't realize it is running on windows. It originates from a call to [`fs.realpathSync`](https://nodejs.org/api/fs.html#fs_fs_realpathsync_path_cache) which `atom-build` does, but node should emulate that functionality on windows accor

**Comment by bottiger** [comment]
@noseglid Yes, "C:/Users/aplb/.atom/packages/build/lib/build.js" does indeed exist

**Comment by noseglid** [comment]
That makes sense.. but why would it even stat that when it's doing `realpathSync` on a project folder.. hmm.

If you're feeling up to it, it would be really nice to see what `p` is just above line 217 in `build.js`.
Would you mind adding `console.log(p);` there and then look in dev tools (command palette: `Application: Open Dev`) to see what it is?

**Comment by bottiger** [comment]
@noseglid  Sure, here you go       

     /* otherwise, build the one in the root of the active editor */
        return atom.project.getPaths().sort((a, b) => (b.length - a.length)).find(p => {
          const realpath = fs.realpathSync(p);
          return textEditor.getPath().substr(0, realpath.length) === realpath;
      });

[build.zip](https://github.com/noseglid/atom-build/files/87268/build.zip)

**Comment by bottiger** [comment]
@noseglid I did add the console.log(p), opened the dev-tool and reopened the file which produces the exception. Then I got the exception. Then I closed the file again, added a breakpoint to the line where I got the exception and opened the file again.

This is how it looked. I am not too familiar with javascript but it looks like "p" is "atom://config"


![capture](https://cloud.githubusercontent.com/assets/489129/12264120/c59b583a-b934-11e5-88f8-7c575eb81c1c.JPG)

**Comment by noseglid** [comment]
Hmm, but according to the inspect, it seems as `path` is `C:\Users\ap1b\AppData\Local\atom\app-1.3.3\atom:` somewhere further down the stack.. did you change it so the code looks like this:
![screen shot 2016-01-12 at 14 08 34](https://cloud.githubusercontent.com/assets/933880/12264294/23cff59a-b936-11e5-9854-a849b9325102.png)

**Comment by bottiger** [comment]
@noseglid I'm positive. Just added a "blah" just to be sure.

![capture](https://cloud.githubusercontent.com/assets/489129/12264614/4854ac42-b938-11e5-8372-d819eaa989b9.JPG)

and this is the result in the debugger when I open my file.

![capture2](https://cloud.githubusercontent.com/assets/489129/12264627/5f94bf64-b938-11e5-8711-36741c0276b0.JPG)

**Comment by noseglid** [comment]
You are correct. I wonder if `atom://config` have a special meaning. It's definitely on the form of `<protocol>://<resource>`, so maybe there's someone along the way that intercepts this and translates it to that path.

**Comment by bottiger** [comment]
@noseglid Sure. However, I just tested it in explorer and windows have no understanding of atom:// so it must be an internal thing only.

**Comment by jlsalvador** [comment]
[Enter steps to reproduce below:]

1. Edit
2. Open Your Stylesheet
3. (Broken)
4. (Focus another tab, try to click in the "styles.less" tab and you get the "Uncaught Error".)

As you can see, atom-build is trying to open a file from `/home/jlsalvador/atom:` instead `/home/jlsalvador/.atom`.
I have linked `/home/jlsalvador/.atom` to `/home/jlsalvador/.dotfiles/atom`. IMO I think that atom-build got the basename from the realpath, but is trying to open the basename from the linked directory.

**Atom Version**: 1.5.3
**System**: linux 4.4.1-2-ARCH
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.54.1


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/jlsalvador/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/jlsalvador/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /home/jlsalvador/.dotfiles/atom/packages/build/lib/build.js:127:27
    at Array.find (native)
    at Object.activePath (/home/jlsalvador/.dotfiles/atom/packages/build/lib/build.js:126:74)
    at Object.updateStatusBar (/home/jlsalvador/.dotfiles/atom/packages/build/lib/build.js:133:49)
    at /home/jlsalvador/.dotfiles/atom/packages/build/lib/build.js:68:57
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics",
      "linter-jslint",
      "pain-split"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.pyc"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/home/jlsalvador/Documentos/Desarrollo",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "build": {
    "minimizedHeight": 0.1
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-handlebars, v1.3.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.20.0
autocomplete-python, v1.6.1
autohide-tree-view, v0.25.1
build, v0.54.1
build-ember, v0.0.1
build-gulp, v0.7.0
chary-tree-view, v0.2.3
color-picker, v2.1.1
custom-title, v1.0.1
django-templates, v0.5.0
file-icons, v1.6.14
highlight-selected, v0.11.2
language-lua, v0.9.4
language-systemd, v0.1.1
linter, v1.11.3
linter-csslint, v1.3.0
linter-flake8, v1.10.1
linter-handlebars, v2.3.1
linter-jshint, v1.3.1
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
pigments, v0.23.1
project-manager, v2.7.6
tab-control, v0.6.9

# Dev
No dev packages
```
