### ISSUE TITLE
No eligible target. No configuration to build this project exists.

### ISSUE THREAD

**Issue by Gianpierre306** [noseglid/atom-build#274]
<img width="1280" alt="screen shot 2015-12-28 at 12 28 44 pm" src="https://cloud.githubusercontent.com/assets/16315902/12023386/989e37b2-ad5e-11e5-89d2-f073612149ce.png">
 
I've enable every option available, and I still cannot build my project. I've reinstalled it as well and still receiving the same issue. What does this mean?

**Comment by noseglid** [comment]
You need to setup a build configuration so `build` knows how to build it. For your project I would suggest creating a `Makefile` and install [build-make](https://atom.io/packages/build-make) to execute the targets (goals) with `ctrl-alt-b`.

You could also opt for specify custom build configuration file. See [the readme](https://atom.io/packages/build) for this.

**Comment by Gianpierre306** [comment]
Is it possible to create a Cmakelist.txt file and use those following cmds? I'm new to this, and I'm trying to figure out what works best for me to have a working complier for my C++ projects. I'm using a CMake Tutorial site, to develop my own.

**Comment by Gianpierre306** [comment]
I don't follow how to do this at all, I'm completely lost at this point. My problem is I don't know if I'm suppose to copy and paste the source code provided for Specify a custom build command into my terminal? And if I use the replacement as well in my Terminal?
