### ISSUE TITLE
Stopping the build didn't kill process

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#276]
I tried to stop make, but it only gave me `Build Process termination imminent...`. Is #129 fixed?

I've tested this on Linux.

**Comment by noseglid** [comment]
Yes, this is fixed. When pressing escape first, it will send `SIGINT` to the process and wait for it to terminate. If the process catched the SIGINT, but the doesn't terminate, it will stay in the "imminent" state. Pressing escape once more will send `SIGKILL` and forcefully terminate the process.

**Comment by jhasse** [comment]
Ah I see! Didn't understand that correctly, thanks for clarifying :)

**Comment by noseglid** [comment]
Anytime :)

**Comment by jhasse** [comment]
Just tested this again it doesn't kill the process even when I press escape the second time.

**Comment by noseglid** [comment]
I've recently made som changes to this on master (which is yet to be released). Would you mind testing with latest master?

**Comment by jhasse** [comment]
I moved `~/.atom/packages/build` and cloned the repository to that path. Then I restarted atom. Is that the correct way?

I still didn't work :(

**Comment by noseglid** [comment]
I think that should work. You could try adding a `console.log` somewhere and see if that gets logged.

What's the process that wont be terminated? Does it fork? Does it work if you manually `SIGINT` it?

**Comment by petspats** [comment]
Pressing escape 2,3,4 etc times is not working for me also. Works if i hold the escape down for a second.

**Comment by noseglid** [comment]
@petspats What executable are you running?

**Comment by petspats** [comment]
@noseglid i am running remake that starts ModelSim process - that fails and the whole process gets stuck in ModelSim TCL console. I dont see the "Build Process termination imminent..." message.

**Comment by noseglid** [comment]
What operating system is this? Can you SIGINT it manually?

**Comment by petspats** [comment]
@noseglid Ubuntu 15.10. I cannot Ctr-C it. Just noticed that when i press ESC first time, the gearbox next to the counter starts blinking but nothing happens after. Also tried hitting ESC really, really fast - no effect, have to hold it down to exit. This is not a problem for me...just reporting the stuffs.

**Comment by noseglid** [comment]
You can send any signal to a process by e.g. `kill -TERM <pid>`. The build package will send `SIGTERM` first time you press escape. Second time you press it will send `SIGKILL` which should terminate all resource held by the process. Can you verify if this works without the build package involved?

**Comment by petspats** [comment]
@noseglid yes i can kill. Build package finishes after kill.

**Comment by noseglid** [comment]
With -TERM or -KILL ?

**Comment by petspats** [comment]
Sorry for the delay. Both commands work.

**Comment by noseglid** [comment]
Could you include a screencap of the build window when you're canceling it? [licecap](http://www.cockos.com/licecap/) is a super easy way to create sceencap gifs.

**Comment by C-Bouthoorn** [comment]
I reproduced this problem [here (video)](https://vid.me/LlWL).

Also note that build didn't output anything from stdout, but did from stderr. I don't know if that is because I did something wrong, or if that's related to build

Sidenote: I'm not a native Perl user, but its signal handling made it useful for reproducing this problem.

Let me know if you need more information

#### Code
```coffeescript
# .atom-build.cson
name: "Test"
cmd: "perl"
sh: true
args: [ "test.pl" ]
```

```perl
# test.pl
{
  $SIG{INT}     = sub { print STDERR "SIGINT\n";    }; # 2
  $SIG{KILL}    = sub { print STDERR "SIGKILL\n";   }; # 9
  $SIG{TERM}    = sub { print STDERR "SIGTERM\n";   }; # 15

  $ix = 0;
  while(true) {
    sleep 1;
    print STDOUT "[STDOUT] Done $ix \n";
    print STDERR "[STDERR] Done $ix \n";
    $ix++;
  }
}
```

#### Versions
`$ atom-beta --version`
`1.6.0-beta0`

`$ apm -v`
```
apm  1.1.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0
```

`$ uname -a`
`Linux chiyuu 4.2.0-29-generic #34-Ubuntu SMP Mon Feb 8 16:57:47 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`atom-build 0.54.1`

**Comment by noseglid** [comment]
@C-Bouthoorn I think your test case is skewed. You're actually overriding the signals so it makes sense that it doesn't stop then.

I did find a problem with `tree-kill` however which did not correctly kill off subprocesses. Hopefully this closes this issue.

**Comment by C-Bouthoorn** [comment]
@noseglid You said that it would first call SIGTERM when 1x escape, and SIGKILL when 2x escape. I made it so that SIGTERM would be blocked (Just like a real program might), and that SIGKILL would be registered, but it looks like I don't ever get the SIGKILL signal? If that were the case, I would get the output "SIGKILL", right? Not sure here
