### ISSUE TITLE
Should not scroll to top on build error

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#278]
When executing a command without an `errorMatch` the actual error is most likely at the bottom. It would be great if atom-build didn't scroll to the top when the command finishes.

**Comment by noseglid** [comment]
I totally agree. In fact, it only does it if there is an error on build, but no error matcher. A successful build leaves it at the bottom. This is definitely a bug and should be fixed. Thanks for report!

**Comment by jhasse** [comment]
Awesome! Thanks :)
