### ISSUE TITLE
"No configuration to build this project exists." unsure what to do 

### ISSUE THREAD

**Issue by mitacDUO** [noseglid/atom-build#283]
hi noseglid,
the title pretty much sums up my problem. could you tell me what i need to do next (assuming this is an easy fix problem)?
cheers

**Comment by noseglid** [comment]
So, you either need to install a build provider (existing build providers are [listed on the atombuild homepage](https://atombuild.github.io) or create a [custom build command](https://github.com/noseglid/atom-build#specifying-a-custom-build-command).

You can also [create a build provider](https://github.com/noseglid/atom-build/blob/master/create-provider.md) if you want something more reusable and if that could be of use to others in the community.

**Comment by mitacDUO** [comment]
hi again, so i downloaded the build-xcodebuild but nothing changed, it still giving the same message

**Comment by noseglid** [comment]
That provider only works when running on OS X and `xcodeproj` or `xcworkspace` exists in the project root directory: https://github.com/AtomBuild/build-xcodebuild/blob/master/lib/main.js

Is this the case for you?

**Comment by mitacDUO** [comment]
that makes sense i'm running on windows 7. so do you think i should just create a custom build command or is there a build for windows?

**Comment by noseglid** [comment]
You have two options I think:

  1. Contribute to `build-xcodebuild` so that it works on windows. This is sure to be a great experience and others will definitely be able to use that.
  1. Create a [custom build command](https://github.com/noseglid/atom-build#specifying-a-custom-build-command).

**Comment by mitacDUO** [comment]
i'll custom build for now but i'll have a go at making build-xcodebuild work for windows. thanks for the advice

**Comment by noseglid** [comment]
No problem. Have fun coding.

**Comment by adityashukzy** [comment]
You're polite, noseglid. I like you. Thanks so much for the package though. It's a lifesaver.
