### ISSUE TITLE
Option to hide Build targets parsed popup

### ISSUE THREAD

**Issue by nils-werner** [noseglid/atom-build#284]
I really don't need to see

> Build targets parsed.

every time I start my editor. It would be greatly appreciated if that popup was made optional.

**Comment by noseglid** [comment]
I've been thinking about this and totally agree with you. I'll look into fixing this asap.

**Comment by C-Bouthoorn** [comment]
[*totally irrelevant*] Nice new profile pic @noseglid :wink:
[*kinda relevant*] You could maybe put it to `console.log()` so you can see it with CTRL-SHIFT-I (inspector). Just an idea

**Comment by noseglid** [comment]
@C-Bouthoorn Thanks! :D
