### ISSUE TITLE
Scroll bar is hidden by build status 

### ISSUE THREAD

**Issue by sneakypete81** [noseglid/atom-build#286]
Steps to reproduce:
1) Perform a build with a large amount of output text
2) Scroll to the bottom of the output pane
3) Observe that the scrollbar disappears behind the build status bar

The following screenshot shows the scrollbar peeping out above the build status bar:
![screenshot](https://cloud.githubusercontent.com/assets/38854/12417277/d8941b56-be9e-11e5-820d-4f97ac732ede.png)

**Comment by noseglid** [comment]
I see what you mean. That whole CSS solution is suspicious at best. Also, is there really a need for a huge bar all across the screen? I will look into changing this layout.

**Comment by noseglid** [comment]
I just pushed branch `layout-less-is-more` in #294 . I did some re-design. If you want to check it out and give me feedback I'd be delighted!

**Comment by sneakypete81** [comment]
Looks great, I like the "building" icon!

Appreciate the extra vertical space for output too... and the scrollbar
issue is well and truly fixed.

Nice one, thanks for doing this.

**Comment by noseglid** [comment]
Awesome great! Thanks for taking a look and giving me feeback. Much appreciated :)

**Comment by noseglid** [comment]
Fixed with #294
