### ISSUE TITLE
Support cursor keys for scrolling

### ISSUE THREAD

**Issue by sneakypete81** [noseglid/atom-build#287]
Currently the only way to scroll the build output is by clicking on the scrollbar (awkward due to #286) or using the mouse scroll wheel.

It would be handy to support cursor keys (particularly pgup/dn, home, end).

**Comment by sneakypete81** [comment]
[BTW: thanks for a great addon, these issue reports are not a criticism, just ideas for improvement]

**Comment by noseglid** [comment]
Cool! I'm glad you like it and I'm glad you're taking the time to send me suggestions!

Cursor keys would come for free in with term.js I mentioned in #285 . Let's track it there!
