### ISSUE TITLE
Not checking projects that add by `Add Project Folder...`

### ISSUE THREAD

**Issue by xpol** [noseglid/atom-build#290]
I have a project folder in the tree.
And add another folder by `Add Project Folder...`
The new added folder are not checked for builds.

Save the project using Project Manager and reopen Atom it find build tasks for the later folder.

**Comment by noseglid** [comment]
[It should check new project folders](https://github.com/noseglid/atom-build/blob/master/lib/build.js#L84-L89)

In fact, it works for me:
![addprojectfolder](https://cloud.githubusercontent.com/assets/933880/12450409/e2c7a896-bf83-11e5-90f1-72b7c41cb8c5.gif)

**Comment by xpol** [comment]
Ok, I'll if I can reproduce this.
tkank you very much.

Alexander Olsson <notifications@github.com>于2016年1月20日周三 下午9:41写道：

**Comment by noseglid** [comment]
Please re-open the issue if you find a reliable way of reproducing this.
