### ISSUE TITLE
[Discussion] Any interest in a config option to have Atom.beep() after a build is finished?

### ISSUE THREAD

**Issue by rahlzel** [noseglid/atom-build#291]
I'm doing this manually after updating the build package by simply adding "atom.beep()" to certain sections:

![beep](http://i.imgur.com/e35b6Ph.png)

Thought I might make it a bit more official as a PR to add this as default functionality (defaulted to "Off", probably) to the config as a checkbox. For those of us that compile often, having a notification beep can really come in handy.

Thoughts?

**Comment by noseglid** [comment]
Hello and thanks for the suggestion.

I am unfamiliar with `atom.beep()`. According to the documentation it "Visually and audibly trigger a beep.", how does that work exactly?

**Comment by rahlzel** [comment]
Not sure why it mentions a visual beep. It's purely audio.

What happens is, when the build finishes as a success, it will play the default system sound. For Windows, it's the "Default Beep" sound:

![beep](http://i.imgur.com/knWBJcl.png)

This is a big bonus for me, since while I'm compiling I usually ALT+TAB to a different window, like Chrome, and poke around on the interwebs while waiting. Then, 10 minutes later I go, 'Oh yeah, I was compiling something'. A problem I've encountered is not knowing whether or not I remembered to compile, so I have to compile it again. Especially with this build package - if it's a success, the build window disappears almost instantly, so people with a poor memory like myself are left wondering if it compiled.

This is likely not a big need for small projects that compile very quickly, but for larger projects it's very useful.

**Comment by noseglid** [comment]
Ah I see, and I think it's a valid use case. I've been doing that myself, even for 20s compilations :)
I definitely think we can add this. As you suggested it should be configurable and default off.

A suggestion for you PR: Add it in `build.js` when the spawned child process is `close`d. That way we should only have to call `atom.beep()` from one location :)

**Comment by rahlzel** [comment]
But if the spawned child process is closed (I assume that's the sidebar window), won't that mean that the build was a success and not a failure? What happens if the build is a failure? Will it still beep? I think it's important that it beeps with either a success or failure.

**Comment by noseglid** [comment]
The close event is called after the child is closed, wheter success or fail. The exit code is actually passed with that event, see https://github.com/noseglid/atom-build/blob/master/lib/build.js#L373

doc: https://nodejs.org/api/child_process.html#child_process_event_close

**Comment by rahlzel** [comment]
Oh ok. Don't mind me. I'm brand spankin' new to hacking Atom (and node.js), but I can read code fairly well and tweak it. I'll have a look at how the other config options are done and just copy/paste. Work smarter and all that.
