### ISSUE TITLE
Incorrect handling of target exit status

### ISSUE THREAD

**Issue by ivankravets** [noseglid/atom-build#304]
@PlatformIO builder outputs warnings and errors to `stderr`. This is also default behaviour for GCC compiler. However, `atom-build` treats `stderr` as "BUILD FAILED". This is NOT TRUE because return code is `0`.

Looks like `atom-build` decides that target fails if something is in `stderr` but this isn't right decision. The only `returncode` explains which is result from command execution.   

More details 
* https://en.wikipedia.org/wiki/Exit_status
* http://tldp.org/LDP/abs/html/exit-status.html

**Comment by noseglid** [comment]
That should not be true. Atom determines if the build fails by the exit code, and if opted in via `matchedErrorFailsBuild` if there is anything that matches in the output from `errorMatch`.

The code is here: https://github.com/noseglid/atom-build/blob/master/lib/build.js#L376-L379

Could you provide a sample `.atom-build.json` which exhibits this issue?

**Comment by ivankravets** [comment]
Here is warning which is handled as error
```
In file included from .pioenvs/lpmsp430g2553/OneWire_ID1/OneWire.cpp:122:0:
.pioenvs/lpmsp430g2553/OneWire_ID1/OneWire.h:245:2: warning: #warning "OneWire. Fallback mode. Using API calls for pinMode,digitalRead and digitalWrite. Operation of this library is not guaranteed on this architecture." [-Wcpp]
```

**Comment by ivankravets** [comment]
Hm.... I understand what do you mean. Looks like I should write correct regexp which will ignore "warnings".

Nevertheless, this isn't good idea to handle `errorMatch` together with `exit code`. See my output in attach. The code is valid, it's just a warning. What is more, that this link to warning/error line is useful! Because C/C++ developer can have warnings+errors and it would be very bad if "link with go to error/warning" will work only for errors.

![screen shot 2016-01-27 at 22 42 35](https://cloud.githubusercontent.com/assets/1760209/12627583/49636b58-c547-11e5-9695-3c79889d94c4.png)

**Comment by ivankravets** [comment]
Other issue: I wrote correct regexp `^(?<file>src[\\/0-9a-zA-Z\\._\\\\]+):(?<line>\\d+):(?<col>\\d+)` but it doesn't catch error lines :(

![screen shot 2016-01-27 at 22 46 56](https://cloud.githubusercontent.com/assets/1760209/12627702/fcef78ba-c547-11e5-9ad1-2ce467c34a5e.png)

**Comment by ivankravets** [comment]
As for https://github.com/noseglid/atom-build/blob/master/lib/build.js#L376-L379, do we have ability to control `build.matchedErrorFailsBuild` programatically?

**Comment by noseglid** [comment]
> Nevertheless, this isn't good idea to handle errorMatch together with exit code.
Some people would disagree with you. That's why it is configurable. Why do you want to control it? Let the user decide if that should be treated as a failed build or not.

**Comment by ivankravets** [comment]
> Some people would disagree with you. That's why it is configurable. Why do you want to control it? Let the user decide if that should be treated as a failed build or not.

OK, it can be configurable but should be turned off by default. Let's imagine that you re user of PlatformIO IDE. You open your project, build it and PlatformIO says that all "SUCCESS" because `exit status = 0` but `atom-build` says that build "FAILED". What you will think about it? Where is the true? See screenshot below. 

![screen shot 2016-01-27 at 23 41 13](https://cloud.githubusercontent.com/assets/1760209/12629200/7ba23592-c54f-11e5-80ad-327cccf9614f.png)

**Comment by ivankravets** [comment]
1. Do you have any ideas as for https://github.com/noseglid/atom-build/issues/304#issuecomment-175845765 ?
2. From the process communication exists only the one information "success or failed". This is `exit status`. The stdout/stderr can contain a lot of information but this info should not have any influence on the real `exit status`. We can use this info to highlight something, make some actions, place link to matched warning/errors and etc.

P.S: Sorry, I see that this project was created for JS tools (gulp and etc), maybe for WebDev this is normal situation when subprocess returns `exit status=0` and some regexp convert it to "FAILED", but default behaviour should use only `exit code`.
P.S.S: I'll remove this `errorMatch` from targets because users report me the bug in PlatformIO IDE that project builds "SUCCESS" but IDE says that "FAILED". I hope you understand me.

In any way, thanks a lot for great project. The problem here that we want to convert JS World to Generic World.

**Comment by noseglid** [comment]
> Do you have any ideas as for #304 (comment) ?

The error matching is [done using XRegExp](https://github.com/noseglid/atom-build/blob/master/lib/error-matcher.js#L76-L78). If you think that doesn't work, could you provide a minimal example which shows the error?

> P.S: Sorry, I see that this project was created for JS tools (gulp and etc), maybe for WebDev this is normal situation when subprocess returns exit status=0

It does look at exit status primarily. If that is 1 it will always fail the build. If it is 0, the user has an option to treat it as an error if errorMatcher matches anything. I think your best course of action is to recommend people to turn that off if they do not want to treat errors as warnings.

To be consistent with how for instance clang and gcc works I could consider setting the default value to false rather than true.

**Comment by ivankravets** [comment]
@noseglid I've tried to debug your code. XRegExp works fine as my regexp `\n(?<file>src[\\/0-9a-zA-Z\\._\\\\]+):(?<line>\\d+):(?<col>\\d+)`. See dump

![screen shot 2016-01-28 at 19 30 50](https://cloud.githubusercontent.com/assets/1760209/12652918/b5f0eecc-c5f5-11e5-9be1-580dc6b2caf4.png)

**Comment by jhasse** [comment]
What do you think about adding an extra `warningMatch` which doesn't fail the build (but still be clickable)? Had this idea in my head since a few months.

**Comment by noseglid** [comment]
@ivankravets: I'm not sure... I've never seen that behaviour before. If you open the command palette and type `Build: Error Match` and execute that. Does it correctly jump to the error in your code?

@jhasse: I think that only makes sense if people want different settings from different projects. It will add complexity and maintenance so I am reluctant to do so unless there's a strong case for it.

**Comment by ivankravets** [comment]
@noseglid, I see that @orgkhnargh fixed it in other way https://github.com/platformio/platformio-atom-ide/commit/ca6d48feab9ea97adce56936f0ce2d5a19af0248

Thanks!
