### ISSUE TITLE
Plugin doesn't work with build-cargo

### ISSUE THREAD

**Issue by Pzixel** [noseglid/atom-build#308]
I have atom-build and build-cargo packages enabled, but when I use `build` command it shows an error 

> No configuration to build this project exists.

I readed documentation multiple times and got that it seems that plugin should automaticly link with `build-cargo` and doesn't require any custom configuration, because there is nothing about it on project's main page. But it shows that configuration is not set. Both plugins are enabled and should work fine.

There is two possibilites: it could be a bug or it could be a documentation absence.
Unfortunly, I cannot provide any additional information, because I have clean installed new version of atom and every plugin (I have `language-rust` or `racer` additionaly installed only). Of course, I can provide any logs if required and if they are stored somewhere.

**Comment by noseglid** [comment]
I will move this to atom-build/build-cargo
