### ISSUE TITLE
Execute build on save of some files

### ISSUE THREAD

**Issue by MiquelAdell** [noseglid/atom-build#311]
Hi,

This is a feature request. Sorry if here is not the place to put them.

I've been looking arround to see if this feature existed or if it was available with other plugins and I can't find it.

Is it possible to auto-trigger build when some set of files are saved? or on any save in the project?

I'm very new to gulp and atom build so I guess if that feature seems so obvious to me and it does not exist I'm doing something wrong (basically building everything at every save to be able to test locally) so please don't be affraid to correct me if the feature is useless with a correct workflow.

Thanks!

**Comment by MiquelAdell** [comment]
I've just discovered "gulp watch" so now I see why my need was not shared by most.

The issue can be closed if it seems that it's irrelevant or you can point me to other things I am not taking into account.

Thanks anyway!

**Comment by noseglid** [comment]
I think what you experienced is the constant struggle of "what belongs in the build system and what belongs in the system executing the build system" :). I think this is one of those things that does not belong in `atom-build`. Gulp watch is great. For e.g. Make there is built in caching which on re-compiles the source files required etc. The build system will always know better than `atom-build` will.

Thanks for the suggestion though. I will close this.
