### ISSUE TITLE
Errors in the build panel are matched but not linked

### ISSUE THREAD

**Issue by laughedelic** [noseglid/atom-build#314]
Related to #201 and #207, but the problem remains for me.

Here is my `.atom-build.json`:
```json
{
  "cmd": "sbt",
  "name": "SBT compile",
  "args": ["compile"],
  "sh": false,
  "cwd": "{PROJECT_PATH}",
  "errorMatch": [
    "\n\\[error\\] (?<file>[^:\\n]+):(?<line>\\d+):"
  ]
}
```

Here is an example output from sbt:
```
[error] /Users/laughedelic/dev/ohnosequences/loquat/src/main/scala/ohnosequences/loquat/manager.scala:94: not found: type Instuctions
[error]     lazy val normalScenario: Instuctions[Unit] = {
```

The error is matched, because I can jump to it, but there is no clickable link in the panel.

**Comment by noseglid** [comment]
It works well for me (note: I am `cat`ing a file containing your sample output, the error match is the same). 
![screen shot 2016-02-05 at 08 28 39](https://cloud.githubusercontent.com/assets/933880/12840295/8192e82c-cbe2-11e5-9a2d-d5d8e070197a.png)

Do you have custom CSS which may override it?

**Comment by laughedelic** [comment]
hi! I've tried similar configuratino with cat and it worked for me too and then I figured out what's the problem. It's just that by default sbt output contains _color codes_ and one needs to use `-Dsbt.log.noformat=true` option to filter them out. With this option the linking feature works fine :+1: 

It's strange though that jumping to error worked. Can it be that output that is shown in the panel is different from what is parsed for the errors list?

**Comment by noseglid** [comment]
Allright. It is indeed matching on the output, as is. This should generally be no problem if the parts of the regular expression does not change color. Otherwise it is probably better to not output color codes while error matching

**Comment by adammw** [comment]
@noseglid I'm seeing the same problem in 0.56.0

**Comment by noseglid** [comment]
@adammw Unfortunately inserting links was one feature I had to dispose of when moving to term.js. I might look into getting that back in in the future, but I wanted to get the already big release out first.
