### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by garfty** [noseglid/atom-build#315]
Hi, I'm using NVM to manage node and when I try to run a gulp build i get the following error:

env: node: No such file or directory

Everything is fine on the command line, using ZSHRC.

Any help would be greatly appreciated,
Thanks

**Comment by noseglid** [comment]
Could you provide steps to reproduce? Possibly include a screenshot of the error?

**Comment by garfty** [comment]
Hey! Apologies, I should've included more information, here's a gif of the issue on a test project:

![Uploading out.gif…]()

I installed the build plugin, then the build-gulp plugin.

**Comment by noseglid** [comment]
`node` is not in your path when you're starting Atom. Where do you have `node` installed? If you start Atom from a shell that's working (make sure Atom is completely closed first by pressing `cmd-q`), does it work then?

**Comment by garfty** [comment]
Ahh, yes it works if it's opened from the command line.

Node it installed via NVM, so the installation path is ~/.nvm/versions/node/vX.X.X

**Comment by noseglid** [comment]
So you need to add that to the PATH so Atom build knows where to find it (or rather so the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) in `gulp` knows where to find it).
