### ISSUE TITLE
Unable to select active target

### ISSUE THREAD

**Issue by jamie85** [noseglid/atom-build#319]
Have installed the atom-build pack and 'build-xcodebuild' for C/C++ building.  

Unable to build - I receive error message:

> No eligible build target.
> No configuration to build this project exists.

Upon "Build: select active target" (or opt+cmd+t) there are no targets to select from.

I have tried to refresh targets.

**Comment by noseglid** [comment]
Please open a ticket on `build-xcodebuild`.
