### ISSUE TITLE
Can't build c++

### ISSUE THREAD

**Issue by niij** [noseglid/atom-build#321]
Linux Mint 17.3
Atom 1.5.1
Build 0.54.1

I can't compile C++ programs using build. I can compile and run these programs with g++ without a problem. The Build pane loads, but when I run with F9 I get the error:

>> No eligible build target.
>> No configuration to build this project exists.

Is there something I am doing wrong?

![build error](https://cloud.githubusercontent.com/assets/16074300/12993597/bb7ff41e-d0e0-11e5-8ef4-85a0e262bc54.png)

**Comment by noseglid** [comment]
Did you specify a build command? Or install a build-provider?

**Comment by niij** [comment]
I didn't.  I guess I should ask, are there more steps to building for C++ on Linux than installing `build` and having GCC installed on my system?

I appreciate your help!

**Comment by noseglid** [comment]
You must [create a configuration](https://github.com/noseglid/atom-build#specify-a-custom-build-command) explaining how your project is built, or use an existing [build provider](https://atombuild.github.io/).
