### ISSUE TITLE
Doesn't pick a theme 

### ISSUE THREAD

**Issue by evmorov** [noseglid/atom-build#338]
Colors in a build result are always black. Changing a theme doesn't affect the colors.

<img width="1047" alt="screenshot 2016-03-12 14 08 46" src="https://cloud.githubusercontent.com/assets/1059480/13722595/ff2720ec-e85b-11e5-8b9d-6ccff7958438.png">

Environment:
- Atom 1.5.4
- OS X 10.11.3
- build 0.56.0 (the bug exists since this version)

**Comment by evmorov** [comment]
Sure the problem is in term.js that was picked up in https://github.com/noseglid/atom-build/commit/fe7e2c2b04425831706c622b1ebfb7bd2180a7b4. Now I don't see many advantages in this package over tons of packages that somehow use term.js. Before this we had had a lot of control of output.

**Comment by noseglid** [comment]
This is a doozy. The "terminal" defines colors as "red" and "blue", which doesn't really match with a theme since they "set the colors of borders, text etc".
What a theme may want to do is redefine what "red" means, but this also means it may deviate from what the creator of the CLI tool intended.

Now maybe we should have a way to override the colors for themes. This would include changing `term.js` to add classes to colored output rather than actually setting the `style` attribute.

Either way, I'm all for adding ways to control the color.

I hope there are other good qualities with this plugin than the control of the colors in the build output :)

**Comment by evmorov** [comment]
> I hope there are other good qualities with this plugin than the control of the colors in the build output :)

I'm sure that many people use this package only as a test runner. Features in this package that are useful:
1. You run a command and if it's green a windows disappears, if not it stays
2. You have commands per project (rspec {FILE_ACTIVE} for Ruby, ant test for Java, etc.)
3. The package has potential: you can create error file paths clickable, you can add a test summary block (like in IDEA IDE). Because of this potential we had right colors in an output

For now the package doesn't have the point 3. Points 1 and 2 people can emulate with terminal packages (they have many features but as this package they have the same huge problems with colors).

**Comment by evmorov** [comment]
> Now maybe we should have a way to override the colors for themes. This would include changing term.js to add classes to colored output rather than actually setting the style attribute.

Do you really think that it's possible? If it is I'm not sure that it's easy. Spacemacs uses just buffers for command output (not a terminal), vim doesn't use a terminal for this, IDEs sure don't use a terminal for this. But of course they can do it if they wanted. But why should they do it? What are pros for this?

**Comment by noseglid** [comment]
The primary reason are all the controls sequences, which gives the ability to produce a very rich console output. Of course it's possible to add classes to the output of `term.js`. 

These tools were (almost always) built to run in a terminal, that's why I want to run them in a terminal.

As long as the features you deem valuable goes, I value a few others too: specify ways to run tools which rely on multiple environment settings, having a compiler re-compile on change and show the state next to the code I edit, etc. I'm sure other people have other uses/needs.

**Comment by evmorov** [comment]
Thank you for your extended response. Hope the functionality of coloring an output properly will be easy to return.

**Comment by noseglid** [comment]
Thank you for taking the time to report this and voice your concerns. This is how we become better!

**Comment by TarrX** [comment]
Had to downgrade to 0.55.0 again, I see the reasoning behind using a terminal, but a black background with almost not readable grey fonts, no coloring or underlining on my machine makes the whole package not very useful, which is a pity.

**Comment by noseglid** [comment]
@TarrX Could you detail what you mean with `almost not readable grey fonts` ? A screenshot perhaps?

**Comment by noseglid** [comment]
I've thought more about this, and setting the background on the terminal to whatever the theme defines as background on a panel is quite easy. I'll try and get around to that soon.

However, ANSI colors are defined as being on a black background - but you already seem to be happy with the end result, so a configuration for "forcing black background" or "using theme default" seems to be in order.

**Comment by aphecetche** [comment]
Hi,

Just to add my 2 cents. Indeed the last update of the plugin brought a not-so-nice visual difference with the preceeding version I was quite happy with. See the black background with "almost not readable grey fonts" (meaning I can relate to that comment ;-) ) in the attached screenshot.

![capture d ecran 2016-03-14 a 09 47 45](https://cloud.githubusercontent.com/assets/1566009/13739245/58483c6e-e9ca-11e5-92dc-c953827a2e0f.png)

**Comment by noseglid** [comment]
Hello @aphecetche 
Thanks for your input. If you add
```
.build .output {
  background-color: unset;
}
```

To your custom stylesheet (Command Palette > Application: Open Your Stylesheet). Is this the visuals you'd expect?

**Comment by aphecetche** [comment]
Absolutely. Thanks.

**Comment by evmorov** [comment]
Works. @noseglid, thanks.

**Comment by noseglid** [comment]
I'll add an option to override the theme's color with black. That way one can opt out and have the theme colors instead.

**Comment by tesselode** [comment]
I recently updated to the newest version (not sure which version I was on previously), and the terminal has some really gross fonts now.

![capture](https://cloud.githubusercontent.com/assets/2637802/13767193/871227d4-ea3e-11e5-94a9-ba873fa8d5fb.PNG)

Do you think this is a related issue to what @TarrX and @aphecetche were experiencing or something else?

**Comment by noseglid** [comment]
@tesselode It's something different, but what you found was addressed in #340 which is already merged. It can hopefully have a release out alter today

**Comment by TarrX** [comment]
Sorry for the late answer, my visual experience is basically the same @aphecetche and @tesselode has. I am using ArchLinux and OneLight as UI and Syntax Theme.
