### ISSUE TITLE
No scrollbar in output

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#343]
Since updating to the new version there's no scrollbar in the build output. Also Ctrl+Pos1 and Ctrl+End don't work anymore.

I'm using Atom 1.5.4 on Windows 10 with the One Dark theme (compact).

**Comment by noseglid** [comment]
Thanks for reporting.

These issues certainly arose during the transition to `term.js`. I'm not certain how to implement it back since `term.js` doesn't render stuff that isn't visible.
I think this should be an issue on `term.js` as it should be the one to render the scrollbar. (BuildView would have no way of knowing the number of rows etc, without inspecting the terminal object).

I'll keep the issue here in the meantime though, as `build` is actually built upon a fork of term.js by @jeremyramin - so there's no obvious place to put that issue.

**Comment by jhasse** [comment]
I see. Is it possible to make term.js an option? Or should I create a fork of atom-build of the last version without it? Because the way it is now, the term.js integration has zero advantages for me and beside this issue also the following ones:

* no theme support #338
* no links #346 
* takes up more vertical space (always visible header bar with the command which got executed)

Sorry for the critic :-( You've probably spend a lot of time on integrating it and I sure appreciate all you work on atom-build.

**Comment by noseglid** [comment]
I am always interested in constructive feedback.

The theme support has been solved, the links I'm planning to solve with an integration with the Linter package. This also gives a nice overview of all current errors (and clickable with the mouse for those that desired that).

The vertical space doesn't really have anything to do with `term.js`. I just made it like that to not mix what the command is outputting with random stuff (such as the command itself) that `build` wants to display to the user.

I think maybe the best solution is to make it possible to have UI's as a service. We'd need to specify and interface - but it should be quite easy. BuildView is very decoupled from the logic as it is already. I think the status bar could also be a consumer of this service. We could then release the old BuildView as a separate package and users could pick whatever made most sense.

**Comment by jhasse** [comment]
> The theme support has been solved, the links I'm planning to solve with an integration with the Linter package. This also gives a nice overview of all current errors (and clickable with the mouse for those that desired that).

Awesome! :)

> The vertical space doesn't really have anything to do with term.js. I just made it like that to not mix what the command is outputting with random stuff (such as the command itself) that build wants to display to the user.

I see. I've created a new issue for that: #357

**Comment by sorear** [comment]
@jhasse At least for me it's still possible to scroll using a scrollwheel.  Not that I'd mind having the scrollbar back, but that might work for you.

**Comment by jhasse** [comment]
Yes, but `Ctrl+Pos1`, `Ctrl+End` don't work anymore and I also can't select multiple pages of text via the mouse.

**Comment by noseglid** [comment]
I've been talking with the authors of [`xterm.js`](https://github.com/sourcelair/xterm.js) and may switch to their fork of `term.js`. When that is done, the scrollbar and other keymaps should be handled by `xterm.js`.
