### ISSUE TITLE
No eligible build targets

### ISSUE THREAD

**Issue by price-Tag** [noseglid/atom-build#345]
Packages are atom-build, atom-language-rust, language-rust, linter, linter-rust, and racer. What do I need to do to build?

**Comment by price-Tag** [comment]
I have build-cargo installed.

**Comment by noseglid** [comment]
Do you have a file named `Cargo.toml` in your project root? Add one and do `Build: Refresh Targets` to get started.

**Comment by price-Tag** [comment]
I didn't. Thanks.
