### ISSUE TITLE
No link to error on errorMatch

### ISSUE THREAD

**Issue by Supernerd11** [noseglid/atom-build#346]
I get no link to any error on errorMatch after the updated terminal.

Pressing f4/shift-f4 still works.

**Comment by noseglid** [comment]
This is a known issue. To be able to release that in reasonable time I didn't have time to implement that.
You can still use `F4` and `cmd/ctrl-alt-g`. I'll be looking into bringing this feature back in when I find some time.

**Comment by noseglid** [comment]
So, I will be integrating Atom Linter to solve this. It'll provide a list like this:
![](https://noseglid.github.io/build-linter.png)

Work is being done in #354
