### ISSUE TITLE
Build not working on Windows 10 in python since 0.57.0

### ISSUE THREAD

**Issue by Javieriegofer7** [noseglid/atom-build#349]
When trying to build, says "no eligible build target", in precious versions the command worked perfectly.
Tank your very much for the package, it is amazing!

**Comment by noseglid** [comment]
Could you provide more info. What build targets are you expecting? How are you configuring them?

**Comment by jhasse** [comment]
Try `Build: Refresh Targets`. I had some problems with atom-build after upgrading on Windows, too.

**Comment by Javieriegofer7** [comment]
Oh sorry, i realized after that that the problem what after updating the package "Script" (they do very sismilar stuff), so no problem with yours, thank you very much! (Sorry again)
