### ISSUE TITLE
Add default `PATH` in settings

### ISSUE THREAD

**Issue by agektmr** [noseglid/atom-build#35]
As per discussed at [gitter](https://gitter.im/noseglid/atom-build).

Currently atom-build doesn't support PATH export from `.bashrc`, `.zshrc` etc. It would be helpful if default PATH can be configured at settings so that I won't have to create `.atom-build.json` on every and each projects.

**Comment by noseglid** [comment]
How do you start Atom? atom-build actually [extends the environment Atom is started with](https://github.com/noseglid/atom-build/blob/master/lib/build.js#L186). So if you'd have exported something in your shell rc file, then start Atom from that shell, that full environment should be available.

**Comment by agektmr** [comment]
Ok, I noticed if I launch Atom with `atom` shell command, atom-build seems to import shell rc files. But if I launch Atom by clicking on the Atom icon in `/Applications` (which I was doing), it doesn't.

**Comment by noseglid** [comment]
I'm still uncertain whether or not I want to add a configuration for this. There already is a way to achieve this. If it gets some :+1: I'll reconsider. But for now I'll close this out.

**Comment by mickav8r** [comment]
It would be helpful if this was at least added to the docs - I would prefer to launch from the App icon vs the shell command - but at least I can build successfully but a way to set the JAVA_HOME and other vars would make life easier.

**Comment by noseglid** [comment]
There are ways to modify the environment for the atom folder without running it from a specific shell. For instance the [atomenv](https://atom.io/packages/atomenv) package. You could also make an icon shortcut in your OS which starts Atom with a specified environment. I think global environment is outside of the scope for this package.
