### ISSUE TITLE
[FR] trigger build manually

### ISSUE THREAD

**Issue by farfromrefug** [noseglid/atom-build#355]
I am trying to improve this plugin:
https://github.com/HazemKhaled/Titanium-Build

First it does even work for me anymore.
Now it does something different from all the other build packages: it adds menu entries which trigger a build.
Those entries decide of an array of "targets" then should open the target selection to build or launch the build directly if only one.
I think it was doing it using :
```javascript
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:select-active-target');
```
But this does not seem to work anymore. Also i tried with:
```javascript
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:refresh-targets');
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:select-active-target');
```
without success. There i think it should work but because of promises, ```'build:select-active-target``` is called before ```build:refresh-targets``` has finished.

Is there another way to do that?
Could you maybe add a new "command" that we could use like this:
```javascript
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:select-active-target', arrayOfTargets);
```

Thanks

**Comment by noseglid** [comment]
Both of
```
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:refresh-targets');
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:select-active-target');
```
work. In fact, `cmd-alt-t`/`ctrl-alt-t` triggers the `build:select-active-target` one.

Those are built-in commands in Atom which is part of the command flow. They're not under my control.

I'm sorry, but I don't know what you're asking for here.

**Comment by farfromrefug** [comment]
OK sorry let me explain in more details.
The idea behind that package is that the targets list is not fixed. Which means it can't simply return the array of targets within the ```settings()```.
What really happen is this.
The user choose for example to build on iPhone from the menu.
Then an array of target is built(async) based on the XCode version and the list of simulators installed.
Then that list should be presented to the user which should choose one and then build with it.

Everything is already working up to the last line. I have the list of targets but i can't find a way to present it.
I tried a call to ```build:refresh-targets``` so that ```settings()``` can be called again and i can return my list. But then i need (i think) a call to ```build:select-active-target``` to present the list of target.
My problem is that ```build:select-active-target``` seems to be called before ```build:refresh-targets``` is finished and so i get a ```no target found```.

So i am looking for a way to dynamically update the ```settings()``` array and present/trigger it.

**Comment by farfromrefug** [comment]
Actually i just found out that 
```javascript
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:refresh-targets');
atom.commands.dispatch(atom.views.getView(atom.workspace), 'build:select-active-target');
```
works! 
the problem was with ```activePath()```
In my case ```atom.project.getPaths()``` is ```["/Volumes/data/dev/titanium/Akylas/akylas.alpi.maps"]```
and ```activePath()``` was always return ```undefined``` which made your package not work ...
And i found the reason why.
I am in a project for which the path is  "/Volumes/data/dev/titanium/Akylas/akylas.alpi.maps" but i am editing a file out of that project.
The build should still work as i am in my project but it wont because it tries to compare the path of the edited file with the path of the project.

**Comment by noseglid** [comment]
This is intended behavior.
