### ISSUE TITLE
Option to disable the header bar in the build view

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#357]
In order to save vertical space it would be great to have an option to hide the always visible header bar with the command which got executed.

**Comment by noseglid** [comment]
Do you feel this should be a global setting, or should it be toggled (via. e.g. a keymap) ?

**Comment by jhasse** [comment]
I think a global setting is fine. I never really need to look at the command, only the build target which is still visible in Atom's status bar.

**Comment by noseglid** [comment]
Understood. We can definitely implement something like this.
