### ISSUE TITLE
Limit to scope

### ISSUE THREAD

**Issue by idleberg** [noseglid/atom-build#358]
When working with several build providers, I'd find it useful to limit the availability of providers (or targets) that only work in the current scope. For instance, if I was working on a JavaScript file, I'd expect the selected provider to only work for `source.js`. Instead, I have to choose from *all* installed builders, each and everytime I start Atom.

Suggested layout for the target selector dropdown, in this example for  `source.js`.

```bash
-------------------
| Gulp            | # JavaScript providers
| Grunt           | # or targets are listed
| JPB             | # first
-------------------
| Make            | # All other (non-JavaScript)
| XCode           | # providers or targets listed
| ...             | # separately below
-------------------
```

Ideally, Atom Build would remember the preferred provider for each scope.

**Comment by C-Bouthoorn** [comment]
Side question; how would `build` know which provider provides what? For example, I have a Makefile which builds all other files needed to run my JavaScript. When I want to build my JavaScript, I would prefer Make on top.

If we would want to do something like this, we need to implement that the person can specify which provider shows where.

**Comment by idleberg** [comment]
I'd probably add the scope in the build provider (or build file), but leave the option to the user to override this

**Comment by noseglid** [comment]
I don't think this makes much sense for `build`. Build aims to build projects (even if there are occasions when single files are build, but that's an exception). The scope of the current file doesn't really fit this idiom.

Thanks for the suggestion though!
