### ISSUE TITLE
errorMatch: option to capture character range

### ISSUE THREAD

**Issue by idleberg** [noseglid/atom-build#359]
Alright, this might sound odd. I've come across a compiler that does not report the error in the common `<line>:<col>` scheme, but the character range in which the error occurred.

**Example**:

Here is an AppleScript that will break on build

```applescript
tell application "Finder"
  if condition --then omitted
    -- statements
  end if
end tell
```

Building would produce the following error

```
/Users/me/Desktop/broken.applescript:31:40: execution error: The variable condition is not define
d. (-2753)
```

The number `48` marks the beginning of the range where the error occurs, `57` marks the end.

I'm not sure how many compilers follow this, but it would be nice to have a pattern that allows us to capture this, e.g. `?<from>` and `?<to>`.

**Comment by C-Bouthoorn** [comment]
Character 48 to 57 is equal to `omitted` in the comment on line 2. Are you sure that's correct?

**Comment by idleberg** [comment]
@C-Bouthoorn you're right, i forgot i edited the script but did not update the error message

**Comment by noseglid** [comment]
This would only have any effect when used with the Atom Linter integration, right?

**Comment by idleberg** [comment]
If it's the linter integration that highlights the line of the — yes!

**Comment by idleberg** [comment]
The new version does not close this. The compiler does not output `<line>` or `<col>`, only character position. The position is counted from the beginning of the file, line numbers are ignored.

```
/Users/me/Desktop/broken.applescript:31:40: execution error: The variable condition is not define
d. (-2753)
```

The above means the error occured between the 31st and 40th character in the file.

**Comment by noseglid** [comment]
Oh I misunderstood. That is indeed an unusual way of outputting error locations.

To solve this we're gonna need new error matcher categories and translate those to row/col. That'll be really tricky and would involve opening the file and inspecting the content.

Is there no way to get it to output row/col instead?

**Comment by idleberg** [comment]
> Is there no way to get it to output row/col instead?

Unfortunately, there is no way to modify the output.

If there's no easy way, then don't think about it. In theory, the Open Scripting Architecture can be used for other scripting languages, but I think it's only used for AppleScript and JavaScript ([JSOSA](https://www.wikiwand.com/en/JavaScript_OSA)). Since JavaScript OSA was since replaced by JavaScript for Automation ([JXA](https://developer.apple.com/library/mac/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/Articles/Introduction.html)), support for character ranges is probably a very small niche.

Maybe keep it on your list if you ever have plans for a major rewrite that also supports partial building (based on selected code). Otherwise, forget about it! :smile:

**Comment by noseglid** [comment]
It feels very niched indeed. I would not be opposed to it, but I don't expect I will prioritize it anytime soon :smile:

**Comment by noseglid** [comment]
I'm closing this. It seems too big of an effort and too little of a gain.
