### ISSUE TITLE
Install fails on Windows

### ISSUE THREAD

**Issue by skjohansen** [noseglid/atom-build#36]
I just tried to install atom-build on my windows machine with the following error.
I guess the main reason is the absence of Istat on windows.

Installing “build@0.23.1” failed.Hide output…

npm WARN excluding symbolic link spec\fixture\node_modules\.bin\grunt -> ../grunt-cli/bin/grunt
npm WARN excluding symbolic link spec\fixture\node_modules\.bin\gulp -> ../gulp/bin/gulp.js
npm WARN excluding symbolic link spec\fixture\node_modules\grunt-cli\node_modules\.bin\nopt -> ../nopt/bin/nopt.js
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\.bin\cake -> ../coffee-script/bin/cake
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\.bin\coffee -> ../coffee-script/bin/coffee
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\.bin\js-yaml -> ../js-yaml/bin/js-yaml.js
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\.bin\nopt -> ../nopt/bin/nopt.js
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\.bin\rimraf -> ../rimraf/bin.js
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\.bin\which -> ../which/bin/which
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\js-yaml\node_modules\.bin\esparse -> ../esprima/bin/esparse.js
npm WARN excluding symbolic link spec\fixture\node_modules\grunt\node_modules\js-yaml\node_modules\.bin\esvalidate -> ../esprima/bin/esvalidate.js
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\.bin\semver -> ../semver/bin/semver
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\chalk\node_modules\.bin\has-ansi -> ../has-ansi/cli.js
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\chalk\node_modules\.bin\strip-ansi -> ../strip-ansi/cli.js
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\chalk\node_modules\.bin\supports-color -> ../supports-color/cli.js
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\tildify\node_modules\.bin\user-home -> ../user-home/cli.js
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\vinyl-fs\node_modules\.bin\mkdirp -> ../mkdirp/bin/cmd.js
npm WARN excluding symbolic link spec\fixture\node_modules\gulp\node_modules\vinyl-fs\node_modules\.bin\strip-bom -> ../strip-bom/cli.js
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/ansi-to-html
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/atom-space-pen-views
npm http GET https://registry.npmjs.org/temp
npm http 200 https://registry.npmjs.org/temp
npm http 200 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/ansi-to-html
npm http GET https://registry.npmjs.org/ansi-to-html/-/ansi-to-html-0.3.0.tgz
npm http 200 https://registry.npmjs.org/ansi-to-html/-/ansi-to-html-0.3.0.tgz
npm http 200 https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/fs-plus/-/fs-plus-2.4.0.tgz
npm http 200 https://registry.npmjs.org/atom-space-pen-views
npm http GET https://registry.npmjs.org/atom-space-pen-views/-/atom-space-pen-views-2.0.3.tgz
npm http 200 https://registry.npmjs.org/atom-space-pen-views/-/atom-space-pen-views-2.0.3.tgz
npm http 200 https://registry.npmjs.org/fs-plus/-/fs-plus-2.4.0.tgz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/entities/-/entities-1.1.1.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/grim
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/entities/-/entities-1.1.1.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 200 https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/space-pen/-/space-pen-5.0.1.tgz
npm http GET https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/space-pen/-/space-pen-5.0.1.tgz
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/coffeestack
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/coffeestack
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http 200 https://registry.npmjs.org/coffee-script
npm http 200 https://registry.npmjs.org/mixto
npm http 200 https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/property-accessors
npm ERR! Error: ENOENT, lstat 'C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9\node_modules\build\node_modules\atom-space-pen-views\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\source-map\binary-search.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\[mydir]\\.atom\\.apmrc" "install" "C:\\Users\\[mydir]\\AppData\\Local\\Temp\\d-115016-7640-lesuff\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\[mydir]AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9\node_modules\build\node_modules\atom-space-pen-views\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\source-map\binary-search.js
npm ERR! fstream_path C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9\node_modules\build\node_modules\atom-space-pen-views\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\source-map\binary-search.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\[mydir]\AppData\Local\atom\app-0.172.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9\node_modules\build\node_modules\atom-space-pen-views\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\optparse.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\[mydir]\\.atom\\.apmrc" "install" "C:\\Users\\[mydir]\\AppData\\Local\\Temp\\d-115016-7640-lesuff\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9\node_modules\build\node_modules\atom-space-pen-views\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\optparse.js
npm ERR! fstream_path C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9\node_modules\build\node_modules\atom-space-pen-views\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\coffee-script\optparse.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\[mydir]\AppData\Local\atom\app-0.172.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\[mydir]\\AppData\\Local\\atom\\app-0.172.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\[mydir]\\.atom\\.apmrc" "install" "C:\\Users\\[mydir]\\AppData\\Local\\Temp\\d-115016-7640-lesuff\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\[mydir]\AppData\Local\Temp\apm-install-dir-115016-7640-gzvii9
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm

**Comment by noseglid** [comment]
Looking at the error it seems that you're lacking git. I think this is a dependency. Could you install git and try again?

**Comment by skjohansen** [comment]
I was that simple! Thanks a lot!

**Comment by noseglid** [comment]
Glad I could help!
