### ISSUE TITLE
Uncaught TypeError: registry.register is not a function

### ISSUE THREAD

**Issue by rangelfinal** [noseglid/atom-build#367]
Error thrown on Atom init.
No side effects - package runs as usual after the error.

**Atom Version**: 1.6.0
**System**: "Fedora release
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.58.0

### Stack Trace

Uncaught TypeError: registry.register is not a function

```
At /home/rangel/.atom/packages/build/lib/build.js:414

TypeError: registry.register is not a function
    at Object.consumeLinterRegistry (/home/rangel/.atom/packages/build/lib/build.js:414:28)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
angularjs, v0.3.4
atom-ternjs, v0.13.2
atom-yeoman, v0.3.15
autoclose-html, v0.23.0
bottom-dock, v0.4.1
browser-plus, v0.0.54
build, v0.58.0
build-coffeescript, v0.1.0
build-grunt, v0.4.0
build-gulp, v0.7.0
build-npm-apm, v0.10.0
build-rake, v0.1.1
build-xcodebuild, v0.2.0
color-picker, v2.1.1
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.3
file-icons, v1.6.19
fonts, v1.2.0
json-schema, v0.1.15
linter, v1.11.4
linter-alex, v2.0.0
linter-clang, v3.4.4
linter-coffeescript, v1.0.0
linter-csslint, v1.3.2
linter-flint, v0.1.2
linter-jade, v0.3.2
linter-jshint, v2.0.3
linter-just-say-no, v0.6.1
linter-manager, v0.2.12
linter-pylint, v1.2.0
linter-rubocop, v0.4.7
linter-scspell, v2.0.1
linter-scss-lint, v2.5.1
linter-tidy, v2.1.0
linter-write-good, v0.6.1
meteor-api, v2.20.0
minimap, v4.21.0
minimap-linter, v1.1.1
navigate, v0.1.13
omnisharp-atom, v0.27.0
pigments, v0.26.0
pull-requests, v0.0.19
remote-edit, v1.8.24
travis-ci-status, v1.0.0
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Does this happen on every start, or just this once?

**Comment by rangelfinal** [comment]
At every start.
The package seen to run as usual, as every other.

**Comment by noseglid** [comment]
Could you open `/home/rangel/.atom/packages/build/lib/build.js` and add a `console.log` to see what `registry` is in this case.

The regsitry is provided by Atom Linter via Atom's Service API, it's weird that it's not a function - but it doesn't appear to be undefined either. Possibly it can shed some light on what it is from console-logging it.

**Comment by noseglid** [comment]
ping @steelbrain
Do you know how something like this could happen?

**Comment by steelbrain** [comment]
@noseglid This should not happen under any sane scenario. To debug this further, we need to know the value of registry it's receiving from linter's API like you pointed out

**Comment by rangelfinal** [comment]
For some reason, the error panel and the console disagree on which line the "registry.register" error occurred.
The panel says line 415, the console says line 473.
Here are the screenshots: http://imgur.com/a/ALPNv
Here's the IndieRegistry object:

```
IndieRegistry
{
  "subscriptions": {
    "disposables": {}
  },
  "emitter": {
    "handlersByEventName": {
      "observe": [
        null
      ],
      "did-update-messages": [
        null
      ]
    }
  },
  "indieLinters": {}
}
```

**Comment by steelbrain** [comment]
@noseglid There seems to be some weird thing going on, the value of the same object was `IndieRegistry` the first time and `Promise` the second time

**Comment by noseglid** [comment]
Weird indeed.
One thing I can think of is if there's some other package with the `linter-indie` service and provides a `Promise`.

@rangelfinal Do you think you could try with *only* `build` and `linter` installed/enabled?

**Comment by rangelfinal** [comment]
I uninstalled every community package that wasn't a linter or build (I left all the build-* and linter-* ones), and the error is now gone. The console.log only shows the IndieRegistry.
So, now for a journey to find which package is messing with build.
Thanks a lot for your help!

**Comment by steelbrain** [comment]
@rangelfinal It would be very helpful if you would tell us which packages you had previously installed so we can pinpoint the package and ask the authors not to export that service

**Comment by rangelfinal** [comment]
The full list of packages is available on the first post of this issue.
If it's of any help, I made a backup using sync-settings, and my full configuration is available here: https://gist.github.com/rangelfinal/9d67f2f2365921e954b22526851bad35

**Comment by noseglid** [comment]
I have no idea why this happens. It's likely an issue in the service api, but since it's solved I will close this.
