### ISSUE TITLE
Allow customization based on current cursor selection

### ISSUE THREAD

**Issue by 3noch** [noseglid/atom-build#375]
I often want to run a custom build target that uses the current selection to know what to run. For example,  I'd like to write a command that does `py.test {current-file} -k {current-selection}`. It runs the currently selected test in the current file.

**Comment by noseglid** [comment]
Current file is possible using [replacements](https://github.com/noseglid/atom-build#replacements).

The current selection would be very involved and require knowledge of the current grammar scope and parser for that. This is outside of the scope of what this plugin can handle

**Comment by 3noch** [comment]
I don't understand how using the current selection would require any parsing or knowledge of the grammar. It's literally just the text in the selection.

**Comment by noseglid** [comment]
I'm sorry I didn't read you carefully enough. I though somehow extracting the currently selected test from the function.

A replacement for the cursor selection is actually a great idea! I'll look into this!

**Comment by 3noch** [comment]
Sweet!
