### ISSUE TITLE
Attempting to resize the build panel with panel heading disabled causes issues.

### ISSUE THREAD

**Issue by PJB3005** [noseglid/atom-build#379]
#### Problem summary:
If you try to resize the build panel with the panel heading hidden, the panel will become seemingly invisible. I assume it is is actually getting a height of 0.
This makes it impossible to use. To fix it you have to enable the heading to actually have something to resize with.

#### Steps to reproduce:
1. Go into the package's settings.
2. Tick "Hide panel heading".
3. Attempt to resize the panel.

**Comment by noseglid** [comment]
Easily reproducible. I'll fix this as soon as possible.

**Comment by noseglid** [comment]
Sorry for taking so long on this. I've found and remedied the issue. Will be fixed in next release!

**Comment by PJB3005** [comment]
Eh it's not really a bother for me but I thought I'd report it anyways.

**Comment by noseglid** [comment]
Much appreciated.
