### ISSUE TITLE
Jump to file line

### ISSUE THREAD

**Issue by Zilarrezko** [noseglid/atom-build#38]
I find myself wanting to be able to jump to a specific file / fileline when a build fails (of course). And Was wondering if it was possible to hotkey something to jump to a file specified when my build fails and jump to a specific line and set my cursor to it.

I don't think all makefiles/compiler stuff make the same things, but I use cl (visual studio's compiler) to compile my code and from top to bottom it lists the full path the file and the file line in parenthesis.

EX in my compile:
z:\workspace\singularity\src\singularity.cpp(61) : error C2065: 'test' : undeclared identifier
z:\workspace\singularity\src\singularity.cpp(61) : error C2143: syntax error : missing ';' before 'if'

this happens when I write this:
```C++
test
	
if(!Memory->IsInitilized)
{
}
```
Notice no semicolon after test and no type definition.

definitely would make coding more streamlined than having to alt+g and type in line number, and make sure I'm in the correct file.

**Comment by noseglid** [comment]
I think the best way to solve this is to supply a regular expression (like line_regex and file_regex from Sublime Text build systems).

**Comment by AngelEzquerra** [comment]
This would be truly awesome!

**Comment by noseglid** [comment]
I've started to work on this. I think I should have something available fairly soon. I'd appreciate some help with testing it before I release it. I'll post it shortly.

**Comment by Zilarrezko** [comment]
Awesome! Id be happy to help test it.

**Comment by noseglid** [comment]
I've pushed this to master. You should able to test it quickly by running
```bash
apm develop build
atom --dev <path to project>
```

**Comment by Zilarrezko** [comment]
hmm. Is anything suppose to be different? This is what I'm seeing right now.

![buildtesting](https://cloud.githubusercontent.com/assets/8561784/6358291/6b65e7da-bc1f-11e4-81e4-3c7b068240f4.jpg)

**Comment by noseglid** [comment]
Ah. I should've linked you to [the documentation as well](https://github.com/noseglid/atom-build#error-match) :)

You must add the regular expression to the .atom-build.json. For the example you provided it should be something like: `^(?<file>[^(]+)\\((?<line>\\d+)\\)` (there doesn't seem to be row specification in your exmaple so we can't extract that).

**Comment by Zilarrezko** [comment]
Alright, so now we're working with something. Not sure how useful these pictures are. But if there's a better way go ahead and say (rhymed).

Here's Pre alt-ctrl-g (to skip to line in the file) [You can see the error just above the build console window]

![buildtestprealtctrlg](https://cloud.githubusercontent.com/assets/8561784/6358708/75f140de-bc22-11e4-88e4-70f1dec10d4b.png)

Here's after alt-ctrl-g. My limited understanding is that it opens another tab at the top to a new file somewhere. It's empty and I have my cursor hovered over the tab title to show the path.

![buildtestpostaltctrlg](https://cloud.githubusercontent.com/assets/8561784/6358744/bdee49d6-bc22-11e4-8bfb-f384bd8f55c6.png)


And here's my .atom-build.json file based on your specifications in your documentation (holy long words batman.)

![buildtestatombuildjson](https://cloud.githubusercontent.com/assets/8561784/6358753/d2acf41c-bc22-11e4-8392-e00565eaf54e.png)

**Comment by noseglid** [comment]
Pictures are great. It really shows what you're doing!

Hmm, it seems as the regex for matching the file might be incorrect. Is the name of the file actually `z:\workspace\sing... win32.cpp z:\workspace\sing... singularity.cpp` - that is, two paths in one file name, or is that just a rendering issue?

The regex I suggested should match start of string, up to the first paranthesis. Maybe you could tweak that regex to match the file better.

**Comment by Zilarrezko** [comment]
It should be the path to the file that's opened. But it looks like it has two file paths for some reason. The first one doesn't point to a proper file at all. All of my .cpp and .h's are in the src folder. And you can see that first kind of path points to my root folder (singularity) and then imediately tries to point to singularity_win32.cpp which isn't in there and nothing in the error had singularity_win32.cpp in it, the error was in singularity.cpp (no win32).

Not sure what else to say about it, here's my project layout:

![notinroot](https://cloud.githubusercontent.com/assets/8561784/6376510/22e13b36-bcd3-11e4-8cb8-a9fdbb6eccbc.png)

Though sometimes there is a small happening when I do build:

![buildtestodd](https://cloud.githubusercontent.com/assets/8561784/6376540/5d4016b2-bcd3-11e4-889b-19db88382277.png)

sometimes it doesn't even give line 4

The oddest thing today is that I can't alt-ctrl-g anymore. I looked in the packages and saw both the community package and dev package was toggled to disabled. I enabled it and it fixed the problem in the line above. And I recompiled everything. It made another build window like below, and  then I alt-ctrl-g, it then opens up 7 of those weird tabs haha

![buildtestuhhh](https://cloud.githubusercontent.com/assets/8561784/6376669/3c7ebeb4-bcd4-11e4-8843-80d0ca1138d2.png)

Gotta love bug fixing.

**Comment by noseglid** [comment]
Hmm, it appears as atom-build has been activated multiple times. That's no good. Don't know why that happens. I would just close down Atom and start it up again. Are you running with `--dev` flag, or have you linked the package?

It seems as the regular expression is quite good. Maybe it's because of windows line endings (`\r\n` vs `\n` on Linux/OSX). Unfortunately I don't have a windows machine to test on.

If you're up for some debugging, you could try to do `console.log(match)` on row 189 in `build.js` (in the errorMatch function). Then check the developer tools in atom for the output.

**Comment by Zilarrezko** [comment]
running the --dev flag. Should I only have the dev package or should I have both the community and the dev package?

And I'm not going to lie, I have never messed with Atom API, let alone JS. So I have no idea what the source code is doing. I would have to read up on it.

**Comment by noseglid** [comment]
Just the dev package enabled.

**Comment by Zilarrezko** [comment]
Could the errormatching be thinking that the filename that my compiler outputs because that's the file it compiles is part of the file to open?

![buildtestthis](https://cloud.githubusercontent.com/assets/8561784/6378796/740633ae-bce2-11e4-81b1-02b75254db7d.png)

I'm building off of singularity_win32.cpp, and my compiler likes to mention that.
Not sure why but my alt-ctrl-g is gone now, I feel like a real script kiddie right now as I'm not too familiar with atom and it's methods.

**Comment by noseglid** [comment]
Hmm. What `atom-build` does is basically just apply the regular expression on all of the output if it finds a match then it will open the file matched, on optionally matched row and column.

Could you copy and paste the output of the build window as is?

Also, is there such a thing as stdout and stderr on windows, and do you know which of those streams your output is on?

**Comment by Zilarrezko** [comment]
Here's pretty much the extent of what many errors will look like in the build window

```
Executing: build.bat 
singularity_win32.cpp
z:\workspace\singularity\src\singularity_win32.cpp(630) : error C2039: 'PlayCursor' : is not a member of 'win32_debug_time_marker'
        z:\workspace\singularity\src\singularity_win32.h(38) : see declaration of 'win32_debug_time_marker'
z:\workspace\singularity\src\singularity_win32.cpp(630) : error C2660: 'Win32DrawSoundBufferMarker' : function does not take 7 arguments
z:\workspace\singularity\src\singularity_win32.cpp(631) : error C2039: 'WriteCursor' : is not a member of 'win32_debug_time_marker'
        z:\workspace\singularity\src\singularity_win32.h(38) : see declaration of 'win32_debug_time_marker'
z:\workspace\singularity\src\singularity_win32.cpp(631) : error C2660: 'Win32DrawSoundBufferMarker' : function does not take 7 arguments
z:\workspace\singularity\src\singularity_win32.cpp(983) : error C2039: 'PlayCursor' : is not a member of 'win32_debug_time_marker'
        z:\workspace\singularity\src\singularity_win32.h(38) : see declaration of 'win32_debug_time_marker'
z:\workspace\singularity\src\singularity_win32.cpp(984) : error C2039: 'WriteCursor' : is not a member of 'win32_debug_time_marker'
        z:\workspace\singularity\src\singularity_win32.h(38) : see declaration of 'win32_debug_time_marker'
```

I have no idea what was said in the third paragraph. stdout and stderr are foreign to me, but then again I don't know a whole lot about it.

I do use cl (visual studio's compiler) like so (I'm going to take out the compiler switches)

```bat
call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
::Gives access to the cl compiler commandline command

cd build\win32
cl ..\..\src\singularity_win32.cpp
::Creates a singularity_win32.exe in the build\win32 folder by
::being in the build\win32 and using cl as a path to my main cpp file (singularity_win32.cpp)
```

You probably didn't need to know that. But maybe it pointed you in the right direction?

**Comment by noseglid** [comment]
Allright, there seem to be an issue with the regex I provided for you. Running it in the console of chrome I got:

```
'singularity_win32.cpp\nz:\\workspace\\singularity\\src\\singularity_win32.cpp(630) : error C2039: \'PlayCursor\' : is not a member of \'win32_debug_time_marker\'\n        z:\\workspace\\singularity\\src\\singularity_win32.h(38) : see declaration of \'win32_debug_time_marker\''.match(/([^(]+)\((\d+)\)/);
["singularity_win32.cpp
z:\workspace\singularity\src\singularity_win32.cpp(630)", "singularity_win32.cpp
z:\workspace\singularity\src\singularity_win32.cpp", "630"]
```

and obviously match[1] is both `singularity_win32.cpp z:\workspace\singularity\src\singularity_win32.cpp` in one go, with a space in-between. Not good. I modified it a little and came up with this, which seems to work better:

```
'singularity_win32.cpp\nz:\\workspace\\singularity\\src\\singularity_win32.cpp(630) : error C2039: \'PlayCursor\' : is not a member of \'win32_debug_time_marker\'\n        z:\\workspace\\singularity\\src\\singularity_win32.h(38) : see declaration of \'win32_debug_time_marker\''.match(/(.+)\((\d+)\)/);
["z:\workspace\singularity\src\singularity_win32.cpp(630)", "z:\workspace\singularity\src\singularity_win32.cpp", "630"]
```

So the `errorMatch` you should set should be: `(?<file>.+)\\((?<line>\\d+)\\)`.

**Comment by Zilarrezko** [comment]
I seem to be having trouble with alt-ctrl-g. I will post some information like pictures in a second.

**Comment by noseglid** [comment]
But but, it worked before :)

If you press `ctrl-alt-p` and type `build:error-match' and issue that command. Does it work? If so, it's probably something with the key map.

You could also press `ctrl-.` (ctrl and dot) to get the keymap resolver running. That way you can see what key-presses atom registers and what commands it's executing.

**Comment by Zilarrezko** [comment]
I know! I don't know what the problem is D';.

This is a video of me trying using the ```ctrl-.``` and stuff:

https://www.youtube.com/watch?v=CyEdjyPAfug

Hopefully by the time you see it, it will be done processing (I didn't bother lowering the bitrate by rendering it. so it may take a small minute or two).

**Comment by noseglid** [comment]
Hmm I don't know why it doesn't work for you.Maybe you could try something simpler, e.g. a build which only outputs something like 'file:row:col', and then fails the build. You could then use the regular expression `^(?<file>[^\\.]+.c):(?<line>\\d+):(?<col>\\d+)` which should match this. See the readme on the github page.

**Comment by noseglid** [comment]
Solved with d6ce947b8bac6e9bbce3d7c604a44eb885fa270e

**Comment by Velro** [comment]
Anyone who comes across this trying to use Visual C++ 2015, the regex

(?<file>(c:.+((cpp)|h)))\\((?<line>[0-9]+)

Worked for me. Replace c: for the drive you are compiling on. Never had to mess with regex before so there is probably a better way to do this.

Note that warnings will be caught up by this too...

**Comment by Zilarrezko** [comment]
I've been using:

(?<file>.+)\\((?<line>\\d+)\\)

I used 2015 a while back to test out some of it's new stuff... And I believe it was still working like that. You just have to make sure that you use the -FC commandline switch for the full file location when it throws the error. Though I don't think warnings are caught, unless you specify higher warning levels.
