### ISSUE TITLE
Re-render output after panel-resize

### ISSUE THREAD

**Issue by dkerzig** [noseglid/atom-build#381]
Hey,
I really really appreciate your work on making it possible to resize the panel by dragging it, this is how it should work. Thanks! This feature could be even more helpful when the text inside the build-panel adapts the new size :) Common use case: I've started my build process and every outputted path has an ugly line-break what makes it a little bit unreadable -> So I drag the panel to be a little bit wider to see the paths properly what doesn't work yet.   

Dennis

**Comment by noseglid** [comment]
We are issuing a resize to the rendering component (which is @jeremyramin's fork of [term.js](https://github.com/jeremyramin/term.js). I will be looking to switch to [`xterm.js`](https://github.com/sourcelair/xterm.js) instead. Once that is done we can see if this is still an issue, and if so, create an issue on that project!
