### ISSUE TITLE
Append custom regex to errorMatch for a project

### ISSUE THREAD

**Issue by Khady** [noseglid/atom-build#384]
Hi,

I am using a Makefile to compile an ocaml project. This makefile actually calls `ocamlbuild`, which is a wrapper around `ocamlc`/`ocamlopt` (the ocaml compilers).

The errors that are provided by those compilers follow this schema:
```
File "foo/bar.ml", line 277, characters 12-13:
Warning 26: unused variable g.
File "foo/bar.ml", line 280, characters 6-64:
Warning 34: unused type t.
File "foo/bar.ml", line 279, characters 0-6:
Error: Syntax error
```

I have a regex to match the warnings and errors:
```
(?<file>[\\/0-9a-zA-Z\\._\\-]+)", line (?<line>\\d+), characters (?<col>\\d+)-(?<col_end>\\d+):\\n(?<message>.+)
```

For the moment, I have a fork of [build-make](https://github.com/AtomBuild/atom-build-make) in which I added my regex to the errorMatch array.

I wonder if there is a way with `.atom-build.{js,json,cson,yml}` to specify my regex rather than to modify build-make?

I'm thinking about using `preBuild` to append my regex to the existing array, but I'm not sure this is the clean way to do it. Also, I would have to create a custom build command for all the targets in my makefile. This is not really convenient, I would like to use this regex for all the targets.

Or should I create a build provider for `ocamlc`/`ocamlopt` and even if I launch a make task, the regex from my provider will be applied? As my workflow (Makefile + ocamlopt) is common in the ocaml world, I would be happy to provide a solution that works for everyone.

I have the problem for ocaml now, but will probably have the same one with C/C++ or other languages/tools later. I am curious to know what is the best solution. 

Also, subsidiary questions: 
- is there a way to display the warnings and the errors in a different way? (I suspect it is not possible because of [this line](https://github.com/noseglid/atom-build/blob/859aaca93323d512bc853b667629a56f4a92b440/lib/build.js#L305))
- can I access `col` and `col_end` from `postBuild`? I'd like to modify their value.

Thanks

**Comment by noseglid** [comment]
Can you not make a PR to `build-make` with your regex?

**Comment by Khady** [comment]
Sure, I will do it today.

**Comment by noseglid** [comment]
Oh, also saw your other questions now:

  * There is no way to differentiate between errors and warnings right now. I wouldn't mind a way of doing this, I just don't know the best way yet.
  *  You cannot access `col` or `col_end` from postBuild, not change them either. Before enabling things like this I want to verify that it makes sense in all (at least most) scenarios. I haven't thought too much about what one might want to achieve in `postBuild`, it's a quite new feature.

**Comment by Khady** [comment]
Ok, thanks for the answers and for your great tool :)
