### ISSUE TITLE
Option to disable opening of build-pane after starting a build-process

### ISSUE THREAD

**Issue by dkerzig** [noseglid/atom-build#385]
Hey, I would find it useful to have an option (or extra shortcut) to disable the opening of the build-pane when I start the build-process (i.e. via shortcut). Or is this already possible?

**Comment by noseglid** [comment]
Yes,  set the option `Panel Visibility` to `Hidden`.

**Comment by dkerzig** [comment]
Looked two times through the settings and have overseen the first item 😵😂
Thanks!
