### ISSUE TITLE
Error installing build package on OS X El Capitain

### ISSUE THREAD

**Issue by l-gothberg** [noseglid/atom-build#389]
Tried installing via the GUI, command line _without_ sudo, and command line _with_ sudo.  Received the following error message in all cases.

Latest version of Xcode, node.js, and git installed and verified.  Any feedback would be greatly appreciated.

Installing “build@0.59.0” failed.Hide output…

npm WARN addRemoteGit git+https://github.com/jeremyramin/term.js.git#de1635fc2695e7d8165012d3b1d007d7ce60eea2 resetting remote /Users/Leo/.atom/.apm/_git-remotes/https-github-com-jeremyramin-term-js-git-e93f5087 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/Leo/.atom/.apm/_git-remotes/_templates --mirror https://github.com/jeremyramin/term.js.git /Users/Leo/.atom/.apm/_git-remotes/https-github-com-jeremyramin-term-js-git-e93f5087: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Leo/.atom/.apm/.apmrc" "--userconfig" "/Users/Leo/.atom/.apmrc" "install" "/private/var/folders/n9/kj5bnnms3mv47hh420vlv17w0000gn/T/d-11639-23800-105af4v/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 69

npm ERR! Command failed: 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/n9/kj5bnnms3mv47hh420vlv17w0000gn/T/apm-install-dir-11639-23800-sgn0pv/npm-debug.log

**Comment by C-Bouthoorn** [comment]
You haven't agreed with the Xcode/iOS licence yet. You should do that first separately.

Please see [StackOverflow](http://stackoverflow.com/questions/26197347/agreeing-to-the-xcode-ios-license-requires-admin-privileges-please-re-run-as-r) to do this
