### ISSUE TITLE
View closing automatically

### ISSUE THREAD

**Issue by LPugens** [noseglid/atom-build#39]
I am not sure if I just do not know how to configure it, but the build view closes automatically if the build is successful. It would be nice if we could check the results of the build file even if the build is successful.

**Comment by noseglid** [comment]
The Keep Visible option let's you have the build window open at all times. Would this suit your needs?

**Comment by LPugens** [comment]
It seems like it would, I just don't know where I can access it.

**Comment by noseglid** [comment]
Open the settings (on mac 'cmd-,' on linux/win 'ctrl-,'). Click packages. Find the 'build' package. Check the box next to 'Keep Visible'.

**Comment by LPugens** [comment]
After all, just a user doubt, thanks for the patience.

**Comment by noseglid** [comment]
That's no worries. Glad I could help.
