### ISSUE TITLE
Gulp task not found with `gulp-sass`

### ISSUE THREAD

**Issue by cheich** [noseglid/atom-build#390]
Tested with Atom 1.6.0, atom-build 0.59.0, build-gulp 0.7.0, Windows 10.

When using `var sass = require('gulp-sass');` my custom tasks are not listed in the available targets list (F7).

This is my tested gulpfile.js:
```js
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('default', function() {
  // Default task just works
});

gulp.task('my-task', function() {
  // This task is not found
});
```

Now, if I remove the `gulp-sass` module __and after restarting Atom__, `my-task` is listed as expected:
```js
var gulp = require('gulp');
// var sass = require('gulp-sass');

gulp.task('default', function() {
  // Default task just works
});

gulp.task('my-task', function() {
  // This task is now found and listed
});
```

EDIT: gulp 3.9.1, gulp-sass 2.2.0

**Comment by noseglid** [comment]
I believe this is an issue with `build-gulp` using the Atom environment when spawning the gulp task. Would you mind posting this issue to that project instead?

**Comment by cheich** [comment]
Works fine with the latest update _build-gulp v0.8.0_ - thanks!

**Comment by noseglid** [comment]
Awesome! :)
