### ISSUE TITLE
No eligible build target

### ISSUE THREAD

**Issue by karai17** [noseglid/atom-build#391]
I just updated to Atom 1.6.2 and build to 0.59.0 and when I try to build my project, it says I have no build targets. my .atom-build.json file is where it has always been. Last known working version was Atom 1.6.0 and build 0.55.0.

I am running on Linux, Fedora 23.

```
Ooops. Something went wrong.
watch ENOSPC
Error: watch ENOSPC
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1247:11)
    at Object.fs.watch (fs.js:1273:11)
    at /home/karai/.atom/packages/build/lib/atom-build.js:77:51
    at Array.map (native)
    at CustomFile.settings (/home/karai/.atom/packages/build/lib/atom-build.js:77:36)
    at /home/karai/.atom/packages/build/lib/build.js:111:52
```

**Comment by noseglid** [comment]
`ENOSPC` indicates that you're out of diskpace. Clean some up and try again.

**Comment by karai17** [comment]
I have hundreds of gb free...

**Comment by noseglid** [comment]
On all mounts? (http://lxr.free-electrons.com/source/include/uapi/asm-generic/errno-base.h#L31). The error indicates that there is a devices which have no space left

**Comment by karai17** [comment]
I have hundreds of gb free on each and every mount, yes. I also have several gb of memory free.

**Comment by noseglid** [comment]
You're getting a kernel error when you try to execute a command. The issue is very unlikely to be in the `build` package. Could you please provide more information if I should be able to help you.

**Comment by karai17** [comment]
Apparently this was the issue (and it is now solved)

https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path
