### ISSUE TITLE
Dependencies between targets

### ISSUE THREAD

**Issue by TheStealthReporter** [noseglid/atom-build#396]
The thing I would like to see is a `depends` object `.atom-build.*` files. This allows grouping commands, for example: 

Target: "All"
```json
{
  "targets": {
    "Debug": { ... },
    "Release": { ... },
    "All": {
      "depends": ["Debug", "Release"]
    }
}
```

Target: "Compile & Run"
```json
{
  "targets": {
    "Build Debug": { ... },
    "Run Debug": { ... },
    "Build & Run Debug": {
      "depends": ["Build Debug", "Run Debug"]
    }
}
```

A mechanism like this makes it easier to run applications, because now I don't have to wait for the project to build to call the run shortcut (other packages aren't nearly as comfortable to run a created binary file).

If there is already a way of doing this, I would appreciate any comments on that (I'm fairly new to Atom).

**Comment by noseglid** [comment]
This has already been [discussed and decided against](https://github.com/noseglid/atom-build/issues/89#issuecomment-108261280).

`atom-build` only aims to run other build systems. Not be a build system itself.
