### ISSUE TITLE
[ Feature request ] setting window for shell (even for windows)

### ISSUE THREAD

**Issue by K4zuki** [noseglid/atom-build#397]
I would like to use `git-bash` (from "Git for Windows"), instead of `cmd.exe`.
I think I found setting in `spec/helpers.js` which specifies cmd.exe but it would be better if selectable from setting window of the package.

**Comment by noseglid** [comment]
How does this work on windows? Is git-bash in you path? Is it possible to run unix commands?
`spec/helpers.js` are just for the tests. The shell used when building is in `lib/build.js`, which defaults to `cmd.exec`.

Why do you want a different shell?

**Comment by K4zuki** [comment]
I would like to use same Makefile on Win7 and OSX.
To do this, I want to use best unix-like environment, or command set, like bash or make.
I can use busybox or cygwin or MSYS to use bash, but for any choice it would be better to point the path to shell from Atom.
So I would like setting option on atom for this package.

`Git for Windows` installs git on subset of `msys2` which has basic unix commands, including bash(git-bash).
git-bash uses PATH from system and adds path to unix command set in msys2.

***
#####  backgrounds:
I am using `atom-build-make` to 'make' on both OSes.
when I try a build from `build-make` on OSX, it works. But on Windows, it fails.
this is because each command behaves different(such as: `whoami` returns `host\username` while `username` is expected)
However this is not matter of `build-make`, but the shell which used from this `build` package on each OS.

So if I could point path to git-bash then my Makefile would work on Windows.

**Comment by noseglid** [comment]
`build-make` doesn't use shell at all, it invokes `make`: https://github.com/AtomBuild/atom-build-make/blob/master/lib/make.js#L78

So this would likely not help you. What problems do you get when using this Makefile under windows?

**Comment by K4zuki** [comment]
problem was the make(invoked from build-make) cannot understand semicolon as command separator 
as bash can and uses everything as argument of first command.

considering a directory which has one Makefile like:
```{.makefile}
all: target

target:
    @echo foo; \
    ls
```
##### expected(or OSX) result:
```
foo
Makefile
```
##### build-make on Atom-Windows result:
```
foo; ls
```
if I start cmd.exe prompt and move to the directory and run make, output is same as
build-make result on Windows Atom

if direct invoking is calling cmd.exe, then enabling use-shell option makes more sense, but default shell seems to be also cmd.exe, then need an option to specify shell.

**Comment by noseglid** [comment]
Which shell `make` uses has nothing to do with this plugin. See the GNU make reference: https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html
