### ISSUE TITLE
Windows, after updating to atom 1.7: unable to execute...

### ISSUE THREAD

**Issue by underdpt** [noseglid/atom-build#399]
Hi,

After updating to Atom 1.7 all my builds stopped working, with the next message:

```
Unable to execute: d:\desarrollos\bctpv\php-gtk2\php-win.exe
Make sure cmd:'d:\desarrollos\bctpv\php-gtk2\php-win.exe' and cwd:'D:\desarrollos\bctpv' exists and have correct access permissions.
Binaries are found in these folders: C:\Python35;;/usr/local/bin;/usr/bin;/bin;/usr/sbin;/sbin
```
It doesn't work with or without sh enabled, and changing que slash to "\\" or "/".
Also, it's strange it states where the binaries are found, but except for the first one, the others are linux folders and I'm working on windows.

**Comment by noseglid** [comment]
The binary paths is the `PATH` environment variable.

Have you made sure both `cmd` and `cwd` exist and have correct access permissions?

**Comment by underdpt** [comment]
My PATH environment isn't related at all with the one that shows the output:

```
C:\Users\underdpt>PATH
PATH=C:\Python35\Scripts\;C:\Python35\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\java\jre7\bin;c:\xampp\php;C:\Program Files\Norman\Npm\Bin;C:\Program Files\Calibre2\;C:\Python27;C:\Python27\scripts;C:\Program Files\Aladdin\eToken\PKIClient\x32;C:\Program Files\Aladdin\eToken\PKIClient\x64;C:\Program Files\Cinterion\Module Exchange Suite\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\IronPython 2.7\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\GitExtensions\;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Users\underdpt\AppData\Roaming\npm;C:\Program Files (x86)\Git\bin;C:\Users\underdpt\AppData\Local\atom\bin;C:\Users\underdpt\AppData\Roaming\Composer\vendor\bin
```

On the other hand, `cmd` exists but `cwd` not. I'm not sure cwd is a windows command anyway...

**Comment by noseglid** [comment]
`cwd` is not a command, it's the _current working directory_ from which relative files will be resolved. If it does not exist the command cannot be execute.

The `PATH` is apparently different in your `cmd.exe` and when opening Atom (which is not uncommon). There are other issues on this project which talk about how to set the path event for an Application (such as Atom).

**Comment by underdpt** [comment]
I'm sorry to reopen this.

This is my .atom-build.json:
```
{
  "cmd": "php-gtk2\\php-win.exe",
  "name": "bcTPV",
  "args": [ "bcTPV.pgtk2" ],
  "sh": false,
  "cwd": "{PROJECT_PATH}",
  "env": {
  },
  "errorMatch": [
  ],
  "keymap": "f6",
  "targets": {
  }
}
```

As you can see, the cmd is relative to `cwd`, which is set to `PROJECT_PATH` so it should work (and was working) without touching the environment `PATH`:
```
Unable to execute: php-gtk2\php-win.exe
Make sure cmd:'php-gtk2\php-win.exe' and cwd:'D:\desarrollos\bctpv' exists and have correct access permissions.
Binaries are found in these folders: C:\Python35;;/usr/local/bin;/usr/bin;/bin;/usr/sbin;/sbin
```
If I set `cmd `to the full path of the executable, it also doesn't works (thats the log from my first comment).

**Comment by noseglid** [comment]
So where is `php-win.exe` located?
Is it exectuable?
I'm pretty sure this has nothing to do with `atom-build` but rather your environment. Please double-check all paths and permissions.

**Comment by underdpt** [comment]
Hi noseglid,

`php-win.exe` is on path: `{PROJECT_PATH}\\php-gtk2\\php-win.exe` and it's executable and readable by everyone.
The problem is not related only with this project but with any project on windows, at least for me. Projects that were working before atom being updated to 1.7, so i think that is at least related.

Anyway, I'ts working after last build package update, thanks!

**Comment by underdpt** [comment]
Ok, 
So now i find that it's not working again. It was working just after the upgrade, but now the issue remains.
I'll wait until the next release and check it.

**Comment by noseglid** [comment]
I'd be willing to bet it has nothing to do with `build` itself but rather something that's changing in your environment. Try and fully qualify the path to `php-win.exe`

**Comment by underdpt** [comment]
Hi,
First, thanks for your patience :-)

I already checked that, and it's not working.  I was going to recheck it now, and then it worked again. After some testing, it works (without changing the paths) if I open the project on a new window. I'm using `project-ring` package so I uninstalled it and the same results so it seems unrelated.

Quick resume: If I open atom and try to use any build, It doesn't work.
If I open atom, then go to File -> New Window, and on this new window I load any project the builds works perfectly.

I'm also thinking it's something on my environment, but it's driving me crazy as it stopped working just after upgrading to atom1.7.

**Comment by underdpt** [comment]
I'm now sure this has nothing to do with `atom-build`. Another package, `atom-beautify`, has the same extrange behaviour.
It seems  https://github.com/atom/atom/issues/11302  is related to this, so I'll wait to the next atom release.
Thanks for your support.
