### ISSUE TITLE
Add support for compiling nim scripts

### ISSUE THREAD

**Issue by AngelEzquerra** [noseglid/atom-build#40]
It would be neat to have built-in support for compiling nim scripts. The configuration would be:

{
  "cmd": "nim",
  "args": [ "compile", "{FILE_ACTIVE}" ],
  "sh": false,
  "cwd": "{FILE_ACTIVE_PATH}"
}

It would probably be easy to add support for a few other popular languages, such as go or rust (I don't mention C or C++ because atom-build already has makefile support).

**Comment by noseglid** [comment]
I'd love support for more languages/tools natively. Since this support is just a massive if-else-if statement right now I think it needs to be refactored and more plugin-based so it can easily be extended first. I'm all for ideas!

**Comment by noseglid** [comment]
I've made a first attempt at modularizing the build tools in 6efd5f3.
I though I could add support for nim scripts using this new approach.

What would determine if `nim` can run or not? Is it the extension of the current file? Is it a specific build file (such as `Makefile`, or `package.json`)?
