### ISSUE TITLE
Not found `npm`!

### ISSUE THREAD

**Issue by LestaD** [noseglid/atom-build#401]
I use builder `build-npm-apm` (https://github.com/AtomBuild/atom-build-npm-apm/issues/16)
I installed node by [nvm](https://github.com/creationix/nvm).
Nvm loader exists in my `.bashrc`.

![image](https://cloud.githubusercontent.com/assets/5620073/14687026/1d7131ee-0744-11e6-9409-ab99dfc73ac4.png)

**Comment by LestaD** [comment]
@noseglid ping!

**Comment by noseglid** [comment]
So where is `npm` ?

**Comment by noseglid** [comment]
Please don't open multiple issues for the same thing unless asked.
Issue discussed in AtomBuild/atom-build-npm-apm#16.
