### ISSUE TITLE
Invalid Build File

### ISSUE THREAD

**Issue by DougEdwards47** [noseglid/atom-build#402]
just started using Atom and Corona SDK. Have installed the syntax colouring and auto completion packages (which work) as well as the build package. I have copied the suggested .atom-build.json file, but I get "Invalid build file"  ... "you have a syntax error in your build file .... Unexpected token"
Any suggestions?
MacOS 10.1.4
````
{    "cmd": "/Applications/CoronaSDK/Corona\ Simulator.app/Contents/MacOS/Corona\ Simulator",
    "args": ["main.lua"],
    "name": "Corona SDK",
    "cwd": "{PROJECT_PATH}"
    "sh": true 
}
````

**Comment by noseglid** [comment]
You're missing a comma after `"{PROJECT_PATH}"`.
