### ISSUE TITLE
Update build target after active dir change

### ISSUE THREAD

**Issue by yufanyufan** [noseglid/atom-build#404]
Hi,
My project has several sub project, each has its own build config.
How can I program my build provider, so that it update config when active dir changes?

Thank you!

**Comment by C-Bouthoorn** [comment]
Could you give an example ?

**Comment by yufanyufan** [comment]
I want to write a bazel provider. http://bazel.io/
Each dir has its own build config.
So when I switch between files, I want to use the build target from their own config.

**Comment by C-Bouthoorn** [comment]
I would make a "simple" bash script (in my case), and let that handle the dynamicity.

```coffeescript
# .atom-build.cson

name: "Build file"
cmd: "{PROJECT_PATH}/build.sh"
sh: true
args: [ "{PROJECT_PATH}", "{FILE_ACTIVE_PATH}", "{FILE_ACTIVE_NAME}", "{FILE_ACTIVE_NAME_BASE}" ]
```

```bash
# {PROJECT_PATH}/build.sh

#!/bin/bash
root=$1
folder=$2
name=$3
base=$4

configfile="$folder/build.cfg"

# Use default config if failed to load from folder
if [ ! -f "$configfile" ]; then
    configfile="$root/build.cfg"
fi

# Get command from configfile
cmd=$(grep "^CMD: " "$configfile" | sed 's/^CMD: //g')

# Replace arguments
cmd=$(sed -e "s/{NAME}/$name/ig" -e "s/{BASE}/$base/ig" <<< "$cmd")

# Execute
$cmd
```

```
# /the/folder/where/to/build/in/build.cfg

CMD: gcc -o "{BASE}" "{NAME}" && "./{BASE}"
```

```
# {PROJECT_ROOT}/build.cfg

CMD: #
```


(_and then I realise that it is really ugly_)

I have no idea if this should be solved by Build, or if this is the "proper" way of doing these kind of things.

**Comment by noseglid** [comment]
In a build provider, you should be able to emit the `refresh` event to let `build` know new/changed targets may be available. The `settings` function of your provider will then be called again, and you can provide new targets based on the current active folder.

**Comment by yufanyufan** [comment]
Thanks, noseglid!

When does build call provider's settings() function?
Does build call settings() for each project once, or for each file once?

**Comment by noseglid** [comment]
Right now it's for each project. But you shouldn't worry too much about that. The root will be passed to you in the constructor and you should treat this as the root of a project. In later releases this may or may not correlate to what Atom calls a "project".
