### ISSUE TITLE
Support warnings in addition to errors

### ISSUE THREAD

**Issue by NuclearCookie** [noseglid/atom-build#408]
Currently, the only supported property is "errorMatch". It would be great to have "warningMatch" and let linter show the warnings. Basically exactly the same behaviour as for errors except that they don't break the build ( by default ) and that they show up orange in linter :)

**Comment by noseglid** [comment]
So this begs the question, how should this be specified.

Adding a new key `warningMatch` as suggested is one way to go about it.

A different way could be If we add another error matching group (e.g. `(?<level> RE)`), then we would need to support a variety of vocabulary for error and warning (such as `E`, `ERR`, `ERROR`, `ERRNO` etc.). I'm willing to bet there are quite a few variations (even though I believe `ERR` and `ERROR` would be among the most common ones. I'm kinda liking your suggestion better.

**Comment by NuclearCookie** [comment]
seperating the warningMatch from the errorMatch seems more straight forward. As a user it would also be more readable this way. In addition, you won't change the behaviour of errorMatch so there is less chance to break anybody's regex. And it's easier to spot on your documentation :)

**Comment by oli-obk** [comment]
> In addition, you won't change the behaviour of errorMatch so there is less chance to break anybody's regex. And it's easier to spot on your documentation :)

This won't break any existing regexes, because the `level` group is new, so the change is backwards compatible.

> As a user it would also be more readable this way.

you mean the regex would be more readable? I don't consider regexes to be human readable ;)
