### ISSUE TITLE
Refresh Targets not called in common initial workflow

### ISSUE THREAD

**Issue by nathancarter** [noseglid/atom-build#409]
If a user creates a new project, edits some files in Atom, and adds a `.atom-build.*` file, they cannot then run the build process (<kbd>Cmd+Alt+B</kbd>) because "Refresh Targets" has not been run.  This is a gotcha that can be confusing to a new user, who may very well encounter atom-build for the first time in just such a situation.  For more information, see the discussion [here](https://github.com/noseglid/atom-build/issues/310#issuecomment-215433313).

One possible solution:  Run Refresh Targets when there is no build target.  See comments at the end of the thread linked to above for details.

**Comment by noseglid** [comment]
Thanks! I'll try and get around to this shortly.

**Comment by nathancarter** [comment]
Nice, thank you!

**Comment by noseglid** [comment]
Thank you for helping make `build` better!
