### ISSUE TITLE
Support for multiple tree roots?

### ISSUE THREAD

**Issue by tylermumford** [noseglid/atom-build#41]
First of all, this is a great plugin. I really appreciate the ability to build/run a file and see the results directly below.

Currently, it only searches the first root folder in the tree-view for `.atom-build.json` files. I was working on a file in another root folder, with its own config file, and kept getting messages about the first root folder. Could we perhaps search only the root folder with the active file? Or is there a better solution to this?

**Comment by noseglid** [comment]
Hello,
Could you detail and outline the structure of your project and what you want to achieve?

**Comment by tylermumford** [comment]
Sure thing: Since Atom can be slow to open new windows, and I sometimes have related projects in multiple directories, I may add more than one directory to the tree view of a window:

![Two root folders in sidebar, build system of the first is always executed](https://www.dropbox.com/s/f61vd12srtpqi4p/two-root-dirs.png?dl=0)

In this screenshot the two projects are unrelated, but you can see that there's an `.atom-build.json` file in the first one, (configured to just run `py` on the active file) that is incorrectly used when triggering atom-build on files in the second directory (the gulpfile shown).

When the order of directories in the tree view is reversed, atom-build again uses the system of the first directory, attempting to run the gulpfile even when the active file is in the second directory. I was hoping it could be adjusted to use the build system of the file currently in focus, regardless of its position in the tree view.

**Comment by noseglid** [comment]
:+1: 

I haven't really looked into multiple tree roots yet since I don't use it myself. But what you're describing definitely needs to be addressed. Thanks for the report.

**Comment by noseglid** [comment]
This is available in the next release (0.27.0).
