### ISSUE TITLE
executing multiple commands with on key command

### ISSUE THREAD

**Issue by joaodafonseca** [noseglid/atom-build#423]
Hi everyone,

This is more a question than a issue but haven't really found any answer around so I decided to write here.

So I'm creating a custom build provider for openframeworks so I'm able to build and run OF projects from atom using the makefile.

I've been successful so far, I'm able to build and run the projects by specifying the build commands like this: 

`    settings() {

      const args = [ `-j${atom.config.get('build-of.jobs')}`];
      const args2 = [ `-j${atom.config.get('build-of.jobs')}`, 'RunRelease'];

      return [
        {
          exec: 'make',
          name: `BUILD`,
          args: args,
          sh: false,
          keymap: 'alt-cmd-a',
          atomCommandName: 'build',
          errorMatch: errorMatch
      },
      {
        exec: 'make',
        name: `RUN`,
        args: args2,
        sh: false,
        keymap: 'alt-cmd-w',
        errorMatch: errorMatch
      }
    ];
  }`

So pressing "alt-cmd-a" builds the project  and pressing "alt-cmd-w"  runs the projects.(so far so good)

But what I'd like to do is running those two build commands(sequentially build, run) with the same key command, @noseglid is it possible to do this?

Thanks in advance,
Best,
J

**Comment by noseglid** [comment]
Hello,

This is not possible, and have been discussed multiple times. It's been decided agains with the reason that it is outside of the scope of this plugin. Chaining different targets together or handling dependencies between them is better suited for a build system (such as Make, which you're using).

To achieve what you want, I'd create a new target which first build then runs the project.

Good luck

**Comment by joaodafonseca** [comment]
Thanks for the answer @noseglid I'm not that familiar with Make but I'll give it a try.
