### ISSUE TITLE
html error text

### ISSUE THREAD

**Issue by oli-obk** [noseglid/atom-build#428]
Since `linter` supports html error text, would it make sense to add a `html_message` field/regex match ?

Note: my actual use case is markdown, but converting that to html is trivial.

**Comment by noseglid** [comment]
You should be able to pass HTML as it is if you're using the build files programmatically (or via a build provider). Does this not suffice?

**Comment by oli-obk** [comment]
I don't think it works, linter has an extra field for html.

**Comment by noseglid** [comment]
Did you have any time to look into this?

**Comment by oli-obk** [comment]
not yet, I forgot about this...

**Comment by alygin** [comment]
Linter escapes html before showing the message. It would be really handy to be able to pass an html to Linter's `html` field.

**Comment by alygin** [comment]
Here's the PR in case you decide to add such support.
