### ISSUE TITLE
modify buffer output

### ISSUE THREAD

**Issue by oli-obk** [noseglid/atom-build#429]
@noseglid what do you think about giving programmatic builds the ability to modify the displayed build output (e.g. to erase matched parts).

Maybe even for regex matches. Erase all matched text

obviously this only makes sense if `linter` is active, because otherwise we loose information.

I don't have an exact design in mind, just throwing the idea out there.

An alternative would be that I create a separate package to which I can pass just the data I want to see and then hide `atom-build`'s output window. This has obvious advantages, as the display method could be more than textual.

**Comment by noseglid** [comment]
Sorry for taking so long to reply to this.

I am not sure we should increase complexity by this. I think it can be quite tedious to be able parse/modify output as it is appended, not to mention issues that may rise from incorrectly built transforms.

The alternative is a much better approach, I think and is something I've been thinking about for a while. Extracting the build view and connect to it via the service-hub, would allow anyone to create a view for atom-build. The current view could still be installed as default so users are not affected if they're happy with current implementation.

Linter is talking about the same thing.
