### ISSUE TITLE
how to control output panel always visible?

### ISSUE THREAD

**Issue by sbwtw** [noseglid/atom-build#430]
i want to keep output panel visible

**Comment by oli-obk** [comment]
You can change it in the package settings. Reach them this way:

1. Press `Ctrl` + `,`
2. Click Packages
3. search for `build` -> press Return
4. Click the Settings Button on the `build` package
5. Change the first setting to `Keep Visible`

**Comment by sbwtw** [comment]
thanks a lot!

**Comment by noseglid** [comment]
When it's "kept visible" it can be toggled manually with `ctrl-alt-v`. This may be useful if you temporarily need more space for the editor.

It will always be brought up and stay up when you issue build commands though.
