### ISSUE TITLE
Removal of Build Targets

### ISSUE THREAD

**Issue by darArch** [noseglid/atom-build#431]
This may or may not be an issue, but should/would it be possible to remove build targets on deletion of all files matching the `isEligible()` check from a project? 

For example, with the build-coffeescript package, if all `.coffee` and `.cson` files are deleted from a project then I would expect the build targets in the above package to disappear from those available to me within that project. 

Is this something that is currently possible that I need to implement or is it currently not within the capability of the atom-build system?

**Comment by noseglid** [comment]
Anytime a build provider thinks that the build targets must be updated, it can emit the `refresh` event ([see how it's done in build-gulp](https://github.com/AtomBuild/atom-build-gulp/blob/master/lib/gulp.js#L68-L70)). This will remove all the build targets and replace them with a new invocation of `settings()`.
