### ISSUE TITLE
Addind pane for Make targets 

### ISSUE THREAD

**Issue by Rix** [noseglid/atom-build#433]
Hi there,

Thank you for developing the great atom-build package,

We are using C & GNU Make for embedded systems development. After compiling the code with make, each time we need to flash the compiled binary code into microcontroller . We are also using makefile to flash the program. But every time we need to change the target twice. Could you add something to make it easier ? For example;

* A pane for makefile targets, activated by clicking the target
* Custom shortcut key for each target (i.e. F1 clean, F2 make, F3 flash, F4 install etc..)
* Buttons for clean, make, install

We were using kdevelop ide before the Atom. It has clean, build and install buttons. install button runs 'make install' so we use install button to flash the program into device. (install target calls flashing command)

**Comment by noseglid** [comment]
I would suggest creating a target which does all the things you want. e.g. `run: build install`.

Or you can set [`Selecting a new target triggers the build`](https://github.com/noseglid/atom-build/blob/master/lib/config.js#L61-L67) and use `ctrl-alt-t` as the pane.

Using custom keymaps can be achieved if using a custom build configuration.
