### ISSUE TITLE
errorMatch lineter custom type

### ISSUE THREAD

**Issue by Supernerd11** [noseglid/atom-build#434]
I would like to make a note error type for linter for example, since I use the visual c++ compiler and it has "note" to an error sometimes.

**Comment by oli-obk** [comment]
Well we have `warningMatch`, which is less than an error, so it doesn't break the build, but it displays them in linter.

**Comment by Supernerd11** [comment]
Yeah, but id loke it to show "note". I am using warningMatch for now.

**Comment by oli-obk** [comment]
there is a slight chance that you can wrap the `note` text that you are matching on like this: `(?<type>note)`, but no guarantees.

@noseglid: that hack might accidentally work, should it be documented?

**Comment by Supernerd11** [comment]
could you give me an example of how the errorMatch regex should look?

**Comment by oli-obk** [comment]
show me yours and I'll adjust it

**Comment by Supernerd11** [comment]
`(?<file>.+)\\((?<line>\\d+)\\): (?<message>error .+)`

**Comment by oli-obk** [comment]
that doesn't match on notes, how does a note message look?

**Comment by Supernerd11** [comment]
what do you mean?
the message my compiler gives?

**Comment by oli-obk** [comment]
ah you edited the message... but now it matches on everything...
probably something like that should work:

```regex
(?<file>.+)\\((?<line>\\d+)\\): (?<type>note)(?<message>.+)
```

**Comment by Supernerd11** [comment]
It matches, but still shows as "Error".

**Comment by noseglid** [comment]
@oli-obk I think we'd be better off adding a regex which maps to `info` severity type. What do you think?

**Comment by oli-obk** [comment]
Fine with me :)

**Comment by noseglid** [comment]
I guess that's the solution the. @Supernerd11 Feel free to implement it and submit a PR, you can follow [how it's done with `warningMatch`](https://github.com/noseglid/atom-build/blob/master/lib/error-matcher.js#L124)

**Comment by Supernerd11** [comment]
I don't know how to do it, so I'll wait till something easier is implemented.

**Comment by Supernerd11** [comment]
Got it to match, how do i set colour?

**Comment by Supernerd11** [comment]
Is it possible?

**Comment by Supernerd11** [comment]
I added my own colour in my stylesheet.

**Comment by Supernerd11** [comment]
It was quite simple after all.

**Comment by noseglid** [comment]
Care sharing what you did?

**Comment by Supernerd11** [comment]
How?

**Comment by Supernerd11** [comment]
I went and ofllowed all warningMatch, copied, and renamed to noteMatch
