### ISSUE TITLE
Build window font-size and font-family strictly tied to the editor settings

### ISSUE THREAD

**Issue by michalsc** [noseglid/atom-build#436]
I have found that there is no option to change font size or family of the build window, since they are strictly bound to the editor.font-family and editor.font-size. IMHO much better would it be to let user decide what font size and family shall be used in the build window.

On my local copy I have changed  lib/build-view.js lines 72 and 73 accordingly:
`    atom.config.observe('build.fontSize', ::this.fontSizeFromConfig);
    atom.config.observe('build.fontFamily', ::this.fontFamilyFromConfig);`

This way I can adjust the parameters by editing .atom/styles.less file:
`.build {
  font-size: 10px;
  font-family: InputMonoCompressed-Light
}`

**Comment by noseglid** [comment]
Why can you not put this in your `.atom/styles.less`?
```
.build .terminal {
  font-size: 10px;
  font-family: InputMonoCompressed-Light;
}
```

**Comment by michalsc** [comment]
Awww! I haven't realized it will work that way, I'm pretty new to Atom :) Thanks, problem solved :)

**Comment by noseglid** [comment]
Great 👍
