### ISSUE TITLE
Is there any way to configure panel hide timeout

### ISSUE THREAD

**Issue by pftbest** [noseglid/atom-build#440]
When build is successful output panel hides almost immediately and there is no way i can see the text.  I would like it to have a 1 or 2 second timeout before hiding so i can look at the results
```
arm-none-eabi-size bin/program
   text    data     bss     dec     hex filename
    644       8    1564    2216     8a8 bin/program
```
and verify that my program fits in memory.

Another option I tried is to set "Panel Visibility"->"Keep Visible" and then map escape button to hide the panel (like I do in QtCreator), it kinda works, but there is one hitch. I need `build:hide-panel` action and not `build:toggle-panel`, because toggle brings up the panel when i use escape button for other actions.

P.S. Thank you for the plugin, it works great and have saved a lot of my time.

**Comment by oli-obk** [comment]
You could add a functional match that checks whether the program fits and causes the build to break if it doesn't fit.

**Comment by pftbest** [comment]
It is not that simple, for example I added a 4KB array in one of my memories and some code that works with it, so I should expect that bss should be 4KB bigger than a last time, and if it's not, than either I missed a section somewhere or it was just optimised away by a compiler for some reason.

**Comment by noseglid** [comment]
You should use `cmd-alt-v` (or `ctrl-alt-v` on win/linux) to toggle the build panel.
