### ISSUE TITLE
Errors parsing is coupled with build tool support

### ISSUE THREAD

**Issue by kriomant** [noseglid/atom-build#444]
Look at `build-make` build provider: `make` tool itself is widely used to build anything, but `build-make` package supports GCC and OCaml errors only, which seems rather arbitrary. I have implemented `build-ninja` build provider with good support for clang diagnostics parsing, but it is currently unnecessary tied to `Ninja` tool.
Build providers and error matcher should really be different things and should be installed and choosen separately.

**Comment by noseglid** [comment]
While I admire the sentiment, I think it makes build providers overly complicated for the gain it gives. Most providers have very rudimentary error checking (and frankly don't need more than a simple regex in many cases).

That said, there's nothing stopping a you from creating an "error matcher service" which provides the error matching you created, and then consume it from various build providers.

This could also be achieved with something simpler, such as an npm package with the functionality bundled.

I don't think the gain is great enough to bring it into `atom-build` anyhow.

**Comment by kriomant** [comment]
Build providers will become simpler, because they won't have to provide errors handling at all, only build too support.
And while I can share my error matching code using npm package, how I, as a user, can use `make` tool for building sources with `clang` when `make-build` package has no built-in support for it?
