### ISSUE TITLE
Build: Select Active Target freezes Editor

### ISSUE THREAD

**Issue by chessweb01** [noseglid/atom-build#457]
Running Atom 1.8 with build package 0.65.0 on Windows 7.

I am having problems with the processing package. Every time I try to build a sketch, I get the error "No eligible build target. No configuration to build this project exists." 

So I tried "Build: Refresh Targets", and when that was not successful "Build: Select Active Target" which invariably causes the editor to freeze up. After some time a message box with "Editor is not responding" pops up that allows to close Atom.

**Comment by noseglid** [comment]
Already reported in #447
