### ISSUE TITLE
Print to output buffer

### ISSUE THREAD

**Issue by Supernerd11** [noseglid/atom-build#458]
Is it possible to print to the output buffer in pre and post build?

**Comment by C-Bouthoorn** [comment]
Let `build` call a (ba)sh script which does just that for you.

```javascript
// .atom-build.json
{
    exec: 'build.sh',
    sh: true
}
```

```bash
# build.sh
#!/bin/bash
echo PRE
COMMAND
ex=$?
echo POST
exit $ex
```

something equivalent should also be possible on Windows
