### ISSUE TITLE
Encoding Problem after building/compiling

### ISSUE THREAD

**Issue by braintuts** [noseglid/atom-build#459]
after building a PL/SQL-Package in the database via the atom-build plugin i got some encoding issues.
For example ü, ö, ä turns into a ¿

Im not really sure, but i think that issues didn't exist in earlier versions.

Note: I set the default Encoding of atom to Windows 1252.

Edit: database encoding: WE8ISO8859P1 
selected via:
select * from database_properties
where PROPERTY_NAME in ('NLS_CHARACTERSET')

**Comment by 4223** [comment]
Can confirm this problem.

**Comment by noseglid** [comment]
Hmm, the character encoding and how it's displayed is not handled by build at all. Everything that is output from the command will be put as is in a `div`.

Can you create a minimal `.atom-build.yml` file which `echo`es the characters that doesn't work?

**Comment by C-Bouthoorn** [comment]
Bump @braintuts

**Comment by noseglid** [comment]
Closing as inactive. Please re-open if you wish to pursue this further.
