### ISSUE TITLE
Warning: spawn ENOENT

### ISSUE THREAD

**Issue by seleckis** [noseglid/atom-build#46]
I have a project built on grunt, grunt-contrib-jade, grunt-contrib-sass, etc.
While running atom-build in Atom I get a warning, and building terminates:
```
Executing with sh: grunt 
Running "jade:compile" (jade) task
>> 37 files created.

Running "sass:dist" (sass) task
Warning: spawn ENOENT Use --force to continue.

Aborted due to warnings.
```
If I run "grunt" command in a terminal, everything works fine. Any suggestion?

**Comment by noseglid** [comment]
If you start atom from the terminal where you can run grunt and try to build again. Does it work then?

**Comment by seleckis** [comment]
Yes, It works.

**Comment by noseglid** [comment]
You either need to start Atom in an environment where grunt is in your path. Or you need to fully qualify the location to grunt in a custom build file.

The custom build file could look like:
```json
{
  "cmd": "/path/to/grunt"
}
```

You can find the path on a unix-like system (Linux or OS X) by running `which grunt` in a terminal.

**Comment by seleckis** [comment]
> You either need to start Atom in an environment where grunt is in your path.
can you explain? I start Atom.app (OS X version), like any other app. It is not a custom build.

**Comment by noseglid** [comment]
Simply put: You must install grunt in a globally available directory (like `/usr/bin` or `/usr/local/bin`) otherwise it wont be possible to launch it by just saying "`grunt`".

**Comment by seleckis** [comment]
It is.
$ which grunt
/usr/local/bin/grunt

**Comment by noseglid** [comment]
Most likely `/usr/local/bin` is not in the path when launching `Atom` as a regular app. Try this:

```
sudo echo 'setenv PATH /opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin' > /etc/launchd.conf
```

and restart Atom.

**Comment by seleckis** [comment]
sudo echo 'setenv PATH /opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin' >> /etc/launchd.conf
zsh: permission denied: /etc/launchd.conf
