### ISSUE TITLE
Button text

### ISSUE THREAD

**Issue by danqing** [noseglid/atom-build#461]
This is a fantastic package! Thank you for it!!

There are 3 buttons on the right of the top bar: a lightening bolt, a trash can and a close. I'm not entirely sure what they are for, and the tooltip often doesn't show up somehow. Also is there a button to abort the build? The close button seems to only close the pane?

Thank you!

**Comment by noseglid** [comment]
The buttons are

  * **Lightning bolt** run the active build target. Same as ctrl/cmd-alt-b.
  * **Trash can** clear the output. Any new output will be appended to the now empty build panel.
  * **Cross** close the build window. This will not terminate the process that's running. The build window can be shown again with ctrl/cmd-alt-v.

You can press `escape` to abort the build (by default, `SIGINT` will be sent. Pressing escape a second time will send `SIGTERM`, and a third time will send `SIGKILL` which guarantees process termination. Read more [in the README about `killSignals`](https://github.com/noseglid/atom-build#configuration-options).

**Comment by danqing** [comment]
Hi @noseglid thanks for the reply! I know what they mean and I know that there are shortcuts. However, I'm hoping for some more clarity directly from the buttons so that it's a more intuitive UI. Do you think that makes sense?

**Comment by noseglid** [comment]
I see. Perhaps some better icons or a tooltip. Added button for stopping the build would also make sense. I accept PRs.
