### ISSUE TITLE
Build Continues to Run

### ISSUE THREAD

**Issue by prestontw** [noseglid/atom-build#467]
Hello,

Getting right to the chase, when I try to build I get an "emitter.prependListener is not a function" error. I don't know if this is related to the real issue: I can only run a target once and it seems to run indefinitely. Attached is a photo of this. If I change targets, it seems like I can't run them either. Please let me know if there is any other information I can provide.

![screenshot from 2016-08-25 18-44-27](https://cloud.githubusercontent.com/assets/11056277/17988466/764fb402-6af4-11e6-8da5-cae44ecc8ae9.png)

**Comment by prestontw** [comment]
I wasn't sure whether it was a problem with `build` or `build-make`, so I wrote a little custom build script. As you can see, I switched targets back to `build-make` but the original target is still running.

**Comment by prestontw** [comment]
I was on Arch Linux, using atom from the community repo. Removing it and apm and installing atom-editor-bin from AUR solved my problem. Working beautifully now!

**Comment by noseglid** [comment]
👍
