### ISSUE TITLE
Error match for cargo

### ISSUE THREAD

**Issue by r-darwish** [noseglid/atom-build#47]
I'm not sure where this should be placed in the code exactly, but the following regex seems to do the job for Cargo:

    ^(?<file>[^\\.]+.rs):(?<line>\\d+):(?<col>\\d+):

**Comment by noseglid** [comment]
Cool thanks! I'm gonna have to figure out somewhere to put stuff like this. In the readme, or directly in the  build tool so it just magically works.

Is output from Cargo always in that format?

**Comment by r-darwish** [comment]
I think so. I'll update the code if I ever encounter a different format. In
my opinion the error regexs should be part of the package, and users should
write their own regexs only if they use a build tool which isn't yet
supported by this package

**Comment by noseglid** [comment]
I think that is a sound approach. I will add it to the build in error match! Thanks!
