### ISSUE TITLE
Multiple targets for same projects

### ISSUE THREAD

**Issue by tsoernes** [noseglid/atom-build#472]
Hi,

I would like to create a custom build provider, but I would like to be able to run the compiled file as well.
There are two options:
1) Two different targets with different names; one for building and one for running
2) Automatically running after successful build

Example commands:
```
ozc -c MyFile.oz (compiling)
oczengine MyFile.ozf (running)
```

How can I achieve this? Thanks!

**Comment by noseglid** [comment]
It's up to you really.

Two different targets is really straight forward. Just return multiple targets from the `settings`.

Chaining can  not be done natively. Your best bet would be to execute it via shell (set `shell: true`) and give a command similar to `ozc -c {FILE_ACTIVE_NAME_BASE}.oz && oczengine {FILE_ACTIVE_NAME_BASE.ozf`.

Good luck

**Comment by tsoernes** [comment]
How do I name the build files if I want two targets? Or can I have multiple targets in the same .atom-build file?

**Comment by oli-obk** [comment]
you can have multiple targets in the same .atom-build file, as you can see [here](https://github.com/noseglid/atom-build#specify-a-custom-build-command) there's a `target` field.

To keep the command window open after a build, you need to check the appropriate box in the settings of `atom-build`
