### ISSUE TITLE
can you add a Ruby build tool

### ISSUE THREAD

**Issue by borkobt** [noseglid/atom-build#48]
Can you please add a Ruby build tool.

**Comment by borkobt** [comment]
Started with the custom tool. THe code is 
{
    "cmd": "rvm-auto-ruby",
    "args": ["{FILE_ACTIVE}"],
    "cwd": "{FILE_ACTIVE_PATH}",
    "sh": false,
    "errorMatch": "^regexp$"
}

But i got this error:
Executing: rvm-auto-ruby  /mnt/24F7A3FC172C4E8F/Proekti/Ruby/.atom-build.json
Unable to execute: rvm-auto-ruby

**Comment by noseglid** [comment]
`rvm-auto-ruby` is not in your path. See my comment in #46 for suggestions on how to counter this.

**Comment by borkobt** [comment]
It is in my path, i can start it from terminal, i now have this feature with the script plugin. 
https://atom.io/packages/script
