### ISSUE TITLE
Unable to see build output clear with a white background

### ISSUE THREAD

**Issue by Jamesits** [noseglid/atom-build#482]
It seems build output text is always white regardless of syntax theme.

**Comment by noseglid** [comment]
Could you add a screenshot of this?

**Comment by Jamesits** [comment]
Tried Atom Light and solarized light.

This is under Atom Light: 
![image](https://cloud.githubusercontent.com/assets/1297257/20238815/8db0a7aa-a92e-11e6-8215-a65757b48716.png)

Switched to Atom Material (dark theme):
![image](https://cloud.githubusercontent.com/assets/1297257/20238821/cd69fbd0-a92e-11e6-9911-bf32affe7884.png)

**Comment by darkyen** [comment]
Would it be possible just to use the terminal output and pipe it as is? Including the color information ?

**Comment by Jamesits** [comment]
@darkyen The problem is this plugin don't use theme's foreground color.

**Comment by noseglid** [comment]
Have you tried the `overrideThemeColors` setting?
