### ISSUE TITLE
Feature request: silence some output lines

### ISSUE THREAD

**Issue by underdpt** [noseglid/atom-build#483]
Hi,

I would like the feature of removing some lines of the output, via a regexp as it's done with the errormatch or warningmatch options, but simply hiding the matched lines of the output (or not outputting them at all).
Thanks,

**Comment by oli-obk** [comment]
This has been discussed in #429 and is out of scope for the build package. A secondary package hooking into build and creating an alternate display would be ok though

**Comment by noseglid** [comment]
Yes, what @oli-obk said. I don't want to do such processing in the build package. A view could selectively display lines though, once that's pluggable.
