### ISSUE TITLE
Infinite loop if no target

### ISSUE THREAD

**Issue by fzzr-** [noseglid/atom-build#484]
I got the infinite loop of calls `isEligible` method for all build-providers. It happens if I have no any `.atom-build.*`-file;

For localise & reproduce this issue I was create a new atom-plugin with empty provider contains `isEligible() { console.debug("LOOP HERE"); return false; }`

![atom-build loop issue mov opt](https://cloud.githubusercontent.com/assets/888526/19960968/2052b56e-a1c1-11e6-9d38-c0aa815a62f0.gif)

Steps for reproduce:
1. Open any/new project;
2. Call `build:select-active-target` (press F7 by default)

**Comment by fzzr-** [comment]
Loop is [here](https://github.com/noseglid/atom-build/blob/master/lib/target-manager.js#L216).

**Comment by noseglid** [comment]
This should be fixed. Thanks for report.

As a workaround it seems as if you add a `.atom-build.yml` with a single target it it shouldn't occur. This helps you work with the package until this is fixed.

**Comment by fzzr-** [comment]
👍
