### ISSUE TITLE
Match error command should also scroll the build panel

### ISSUE THREAD

**Issue by r-darwish** [noseglid/atom-build#49]
Match errors scrolls the code window to the location of the first build error. While it works fine, I often need to manually scroll the build panel up to see what is the error.

**Comment by noseglid** [comment]
I like this. I would definitely want something like this. I don't think it's possible to get the "row number" or anything like that from a matched regex though.

One option would be to count the number of new-line characters in the output which are present before whatever was matched, and scroll there.

**Comment by r-darwish** [comment]
I'm not yet familiar with how to write plugins for Atom, but if I understand correctly the build panel contains HTML. If that's the case, isn't it possible to put an HTML bookmark tag every time the regex matcher finds a match?

**Comment by 5n8ke** [comment]
I just hacked together something quick for scrolling the build panel. 5n8ke/atom-build@a1bedd97aea922e5c6ae3457400c9fa0180de716
It adds during parsing an html id in a ```<b>``` to every matched position and then it scrolls to this element.

As of now there is now failsafe or extra tests in the code.

**Comment by 5n8ke** [comment]
I updated my branch 5n8ke/atom-build@a1b22dbc57cfa52a5e11f12430407223ba1de69a.
I built in the least bit of failsafe and prepared it so that there could be different types of matches supported (e.g warnings).

**Comment by colin-kiegel** [comment]
@5n8ke / @noseglid : While you're at it - wouldn't it make sense to provide each match with some 'link-behaviour'? I.e. being able to click on the matched error to get to that point in the source code? I think that would be nice too.

**Comment by MackieLoeffel** [comment]
I updated @5n8ke 's code, so it can merge cleanly with current master, fixed a small bug and created a pull request. Since my cygwin and node hate each other, I can't run the tests or add new ones.
@noseglid if you would like some more tests, I can see, if I can fix this.

@colin-kiegel good suggestion, I can look in implementing it
