### ISSUE TITLE
C++ raw string literal not working

### ISSUE THREAD

**Issue by S-March** [noseglid/atom-build#492]
Attempting to build a project that has the following:
static const char PROGMEM INDEX_HTML[] = R"rawliteral(.....)rawliteral"

I am getting the following two errors on build:

warning: missing terminating " character [enabled by default]
static const char PROGMEM INDEX_HTML[] = R"rawliteral(

warning: missing terminating " character [enabled by default]
)rawliteral";

Since it isn't a build error I can still upload the code, but it ends up moving a chunk of code from after the literal into it. For example:

Code as written
static const char PROGMEM INDEX_HTML[] = R"rawliteral(.....)rawliteral";
AAA;
BBB;
AAA;

Code as it appears after build
static const char PROGMEM INDEX_HTML[] = R"rawliteral(..
BBB;
..)rawliteral";
AAA;
AAA;

It appears as if it can't handle raw string literals. The project builds in other ide's so I know it's working.

**Comment by noseglid** [comment]
Not sure what you're implying here.
atom-build simply runs a command (similar as a shell would) and puts it output into a section in the Atom editor. What command being run shouldn't matter.

Do you mean that the build command is run as it should, but the display is incorrect in Atom?

please use tripple-backticks for better formatting so I can grasp your problem more easily. [More on formatting](https://guides.github.com/features/mastering-markdown/).
