### ISSUE TITLE
Issue persists after code change

### ISSUE THREAD

**Issue by avrono** [noseglid/atom-build#496]
Scenario: 

(1) Have .yml which calls make
(2) Make file build some simple files with g++
(3) if build fails with errors, then errors are fixed, they persist 

see screenshot
![screenshot from 2017-01-17 16-29-13](https://cloud.githubusercontent.com/assets/83041/22029344/25bd2632-dcd2-11e6-89cd-4307eb094fbf.png)

**Comment by C-Bouthoorn** [comment]
Are you sure that those errors are from atom-build, and not a linter?

**Comment by avrono** [comment]
Fair point will check that ...
