### ISSUE TITLE
Still no scroll bar in output window

### ISSUE THREAD

**Issue by webeule** [noseglid/atom-build#498]
First of all many thanks for this cool package!
I saw that you made a branch including xterm as terminal to get scrollbars.
When will you put it into the master?

**Comment by noseglid** [comment]
I'm not sure that I ever will. It's not working as well as I'd hope.

I think the next step I will take regarding views is to make it modular so you can select which view you want (all have different trade-offs and I don't think there is one general solution that applies to all users).
