### ISSUE TITLE
Panel not showing on Sass compile error

### ISSUE THREAD

**Issue by onetrev** [noseglid/atom-build#499]
My apologies if I'm being a massive n00b right now, but as far as I can tell this is an issue. I have my Panel Visibility set to "Show on Error" but it does not show. If I open the panel (as attached image shows) there definitely is a sass compile error. And my gulp notify pops up as usual. However the panel definitely _does not_ open automatically.

Accordingly, despite having Atom Linter running as usual, I also do not receive Atom Build errors in my linter panel. Which I'm assuming is very much related to the above issue.

Please let me know if there is anything I can do to troubleshoot this. Thanks!!

SYSTEM DETAILS:
Atom 1.14.2 x64
Windows 10

![snip_20170215183347](https://cloud.githubusercontent.com/assets/597601/22964663/e121cd6e-f3ad-11e6-8b93-1a1d3143a275.png)

**Comment by noseglid** [comment]
The command is exiting with a zero exit status, thus atom-build does not detect the error. You need to add something that makes gulp exit with an error when a sass compile error is detected. [Something like this](https://www.npmjs.com/package/gulp-sass-error).

There are no error matchers in build-gulp, unfortunately so you wont get linter errors. Feel free to implement and send a PR!

**Comment by onetrev** [comment]
Ahhhh, that makes sense. Thanks a ton for the super quick follow up! 

Not sure I have the JS skills yet to successfully implement errors matchers in build-gulp, but I'll put that on a list of projects for practising my javascript.
