### ISSUE TITLE
Can I build a single file? Not a project

### ISSUE THREAD

**Issue by farzher** [noseglid/atom-build#50]
If this isn't something you want to support, that's fine. But I'll tell you my use-case.

I have sublime text setup so that anytime I ever save a `.coffee` file, it builds it into a `.js` file.

It's great, I never need to set up any grunt/gulp build.
But I don't know how to do this with atom

**Comment by noseglid** [comment]
Yes, that should be quite easy. You'd want to create a .atom-build.json file which looks something like this (I think `cake` is used to build .coffee to .json, right?).

```json
{
  "cmd": "cake",
  "args": [ "{FILE_ACTIVE}" ],
  "sh": false
}
```

Not sure about the flags to cake if, but you can add more arguments and use [the replacements for the build file](https://github.com/noseglid/atom-build#replacements) to achieve most things.

**Comment by farzher** [comment]
That sounds good except

* where do I put the `.atom-build.json` file? Doesn't that go in the project root? I want my editor to compile every `.coffee` I save, in any folder. Should I put that file in the root of my C:/ drive?
* how do I tell it to only compile `.coffee` files?

**Comment by noseglid** [comment]
Ah, I understand what you're trying to do. Unfortunately this is not supported. I'm thinking one way would be to integrate this in the plugin so that it runs `cake` if the file is .coffee and no other build tools works.

How did you set this up in Sublime Text?

**Comment by farzher** [comment]
Sublime has a built in build system (no plugin)

You put a file in `Packages\User` called `whatever.sublime-build`

	{
	    "cmd": ["coffee", "-c", "$file"],
	    "file_regex": "SyntaxError: (.*)",
	    "selector": "source.coffeescript"
	}

Now in sublime when I build, if the syntax highlighting (it's kind of weird, the `selector` is based on syntax highlighting, not file extension) for my file is coffeescript it'll run that.
And I use a build on save plugin so it's automatic.

(I don't know the command to build coffeescript. I'm actually lying for simplicity. I'm not trying to build a coffeescript, I'm trying to build an obscure language. But it's exactly the same idea)

**Comment by noseglid** [comment]
I see. I think this would be great to have in atom-build. The `selector` syntax is used heavily in Atom as well.

I think a way to globally define an `.atom-build.json` file which runs if a specific file type is open would get things running for you. I'll look into it!

Thanks for taking the time to report this.

**Comment by bwinton** [comment]
Just as a quick note, if we go with the service API in #139, a Coffeescript provider could check the current file to see if it wanted to build it (like the sample [Markdown provider](https://github.com/bwinton/atom-build-markdown/blob/master/lib/markdown.js#L9) does, to provide this functionality.

**Comment by noseglid** [comment]
As @bwinton says. It should be easy to implement a `CoffeeScript` provider now which always turn `.coffee` into `.js`. I want to move build configuration out of this package and into separate provider.

This is out of scope for this project and should be achieved with a separate plugin.
