### ISSUE TITLE
Run target once

### ISSUE THREAD

**Issue by wiggisser** [noseglid/atom-build#504]
In my project I have two targets A and B. Most of the time I need A, so it's set as active target which I can start with a single key stroke. In rare cases I need to start B. So I have to set it as active target, but after that I have to reset the active target to A again.

So I would really appreciate a command which runs an arbitrary target once, without affecting the active target setting.

**Comment by noseglid** [comment]
You should use the [`keymap` configuration](https://github.com/noseglid/atom-build#configuration-options)
