### ISSUE TITLE
gulp not found on windows

### ISSUE THREAD

**Issue by nyn3x** [noseglid/atom-build#51]
I just installed atom-build. I have a Project with a gulpfie.js.

When I Trigger a build gulp cannot be found, because just "gulp" is being searched for as an executable in the path. Windows seems to only look for gulp.exe oder gulp.com, but my path contains a gulp.cmd instead.

**Comment by noseglid** [comment]
How did you install gulp?

**Comment by nyn3x** [comment]
I just ran "npm install gulp -g" from my commandline.

**Comment by noseglid** [comment]
Hmm allright. It seems as atom-build should look for 'gulp.exe' as well to be compatible with windows. I don't have windows myself so it will be difficult to fix for me. I'm guessing it should look at (os.platform)[https://nodejs.org/api/os.html#os_os_platform] to determine which binary to use.

**Comment by nyn3x** [comment]
Well, actually gulp.cmd would be better, because at least on my machine (and being a total newbie to node.js) I have a npm-folder with a gulp.cmd, which was created by the "npm install" command.

**Comment by noseglid** [comment]
I finally got a hold of a windows computer. When I do `npm install gulp -g` in `cmd.exe` it successfully installs gulp globally into `C:\Users\<user>\AppData\Roaming\npm\`. (this can be seen by running `where gulp`.

Can you verify that you did a global install from an Administrator command prompt?

**Comment by gpit2286** [comment]
This definitely sounds like a path problem.  

http://stackoverflow.com/questions/24027551/gulp-command-not-found-error-after-installing-gulp
http://stackoverflow.com/a/9588052/1041104

See if either of those help you

**Comment by noseglid** [comment]
Closing this out. Please re-open the ticket if the problem persists.

**Comment by nyn3x** [comment]
running `where gulp` shows me the same location:

    C:\Users\eiben>where gulp
    C:\Users\eiben\AppData\Roaming\npm\gulp
    C:\Users\eiben\AppData\Roaming\npm\gulp.cmd

I can run gulp from the command-prompt (cmd) just fine, Only from within atom-build the gulp.cmd seems not te be found.

**Comment by noseglid** [comment]
Did you try the suggestions linked bu @gpit2286 ?
It appears as those paths are not in your system path environment, hence  Atom is unable to find where gulp is installed.

**Comment by nyn3x** [comment]
Well, as I said, I can execute gulp from the prompt just fine, it's just that atom-build doesn't seem to recognize gulp, as it's looking for a gulp.com or gulp.exe, but not a gulp.cmd. I believe that's something, windows itself is causing. I looked at the call-trace using the sysinternals process-monitor.

![image](https://cloud.githubusercontent.com/assets/581049/7023856/cfc23ca8-dd38-11e4-939d-3d987d8f35cd.png)

As you can see with the where-command a couple of comments above, the gulp.cmd is locate just there.

The links of @gpit2286 refere to problems, where gulp doesn't seem to be found by the command-prompt at all. When I type `gulp` at the prompt I get the following:

    C:\Users\eiben>gulp
    [15:16:10] No gulpfile found
