### ISSUE TITLE
No eligible build target.

### ISSUE THREAD

**Issue by lucianoRM** [noseglid/atom-build#515]
Hi!

I am not able to execute the Quick start. 
I installed atom-build, i created .atom-build.yaml with this line inside : cmd: echo Hello world
and i get "No eligible build target" error

**Comment by C-Bouthoorn** [comment]
As far as I'm aware, you need to put more information in the build file. Could you send us the complete `.atom-build.yaml` file?

**Comment by noseglid** [comment]
You need to name your file `.atom-build.yml` (not `.yaml`). At least until #497 is merged.

**Comment by lucianoRM** [comment]
That was it!
Thanks and sorry for being that stupid
