### ISSUE TITLE
build system about input-args

### ISSUE THREAD

**Issue by chenws1999** [noseglid/atom-build#517]
I want to build and run javascript in atom,but before run it, I want to input some args ,e.g.,node index.js  argv1 argv2. The args is variable so that I can not  write it in the config files. So can I do it use atom-build but not terminal?

**Comment by noseglid** [comment]
No. This has been discussed several times and been rejected. `build` is not for running stuff, even if it can be used as such in limited settings.

**Comment by chenws1999** [comment]
well....whatever, thank for your reply. I will try to do it with terminal.
