### ISSUE TITLE
Keep one instance of CMD | Run start up commands [Enhancement]

### ISSUE THREAD

**Issue by Zilarrezko** [noseglid/atom-build#52]
Had an idea to speed up my build time.

Everytime I build, I run vcvarsall to access the Visual Studio's compiler, that takes a couple seconds and I'd like to shave that off.

To do that I suggest (if it hasn't already been done). To keep one instance of the cmd, or whatever shell you run, and have startup commands for when atom starts up, so everytime I build I don't have to call vcvarsall.

I'm not sure where I would do this in the code in build or the code at all, if I knew how to do so I would pull and make a merge request, but maybe I can learn.

**Comment by noseglid** [comment]
I'm not fully certain under which conditions this would be necessary. The commands I run have very little "startup" time compared to the time the build takes.

Initially I feel that what you're requesting shouldn't be the responsibility of the poor schmuck executing the build, but rather the build itself. Compare with how you would do it without any IDE integration and how that could be sped up?

**Comment by Zilarrezko** [comment]
Maybe I don't understand how atom-build works...

If I was to say open command prompt and type in "cl" I would get shot an error (because it doesn't know that command). When I run visual studio's vcvarsall.bat, it takes a few seconds to run. I type in "cl" and it's now a valid command, and I can compile my project. I then close that command prompt. I open it up again and type in "cl" and it's an invalid command.

Is this how build works? Everytime I build it makes a new shell/command-prompt instance?

An initial way to fix this is to just have a command-prompt open with an initial start-up command to vcvarsall (to access visual studio's compiler), and just keep it open and use that to build. But then I wouldn't be using atom-build and lose some of it's features.

**Comment by Zilarrezko** [comment]
Seems after messing around. I guess Atom-build uses the same instance of the cmd that is used to start atom? So I have my command-prompt call vcvarsall when opening my command prompt, then open atom using said cmd, giving atom build the cl command that vcvarsall gives. It's a work-around, and it works. So I'm not complaining too much. And now my builds take less than a second compared to 7 seconds.

**Comment by noseglid** [comment]
I see. Yes, build runs in the same environment as Atom so what you're doing will work well.

I'm not aware of what `vcvarsall` really does but it sounds as it's setting a bunch of environment variables. If that is the case, those could also be set by populating the `env` entry in an `.atom-build.json` file.
