### ISSUE TITLE
Selecting Text in Build Pane

### ISSUE THREAD

**Issue by msp1kpj** [noseglid/atom-build#529]
I am unable to highlight and select text from the Build pane. Every time I try it highlights all text on the file I am editing, the build pane and the linter pane.
![image](https://user-images.githubusercontent.com/7109246/29529145-1f837c58-8664-11e7-8b40-9c68b50e63b6.png)

**Comment by landonboyd** [comment]
This worked for me (Mac OS 10.11.6, Atom 1.21.2):

```
--- build-view.js.orig	2017-11-03 16:53:53.000000000 -0700
+++ build-view.js	2017-11-03 17:20:34.000000000 -0700
@@ -134,7 +134,7 @@
   }
 
   resizeEnded() {
-    document.body.style['-webkit-user-select'] = 'all';
+    document.body.style['-webkit-user-select'] = 'text';
     document.removeEventListener('mousemove', this.resizeMoved);
     document.removeEventListener('mouseup', this.resizeEnded);
   }
```

**Comment by noseglid** [comment]
thanks @landonboyd . That was exactly the issue.
