### ISSUE TITLE
Error: No eligible build target. (noseglid) 

### ISSUE THREAD

**Issue by jaydrue** [noseglid/atom-build#540]
Somehow I cannot figure it out (yes I read through many forums already)

I installed Atom 1.20.1. 
I want to use the "build 0.68.0" package by noseglid and installed it accordingly. (where do I put the file .atom-build.yml exactly). 
I want to code in java so I installed the package build-gradle 0.6.0

running on mac Sierra 10.12.6.

Thanks for your help!!

**Comment by C-Bouthoorn** [comment]
The `.atom-build.yml` file should be located in the root folder of your project. This is usually the folder that contains the `.git` directory (and the `LICENSE` and `README.md` file), configuration files such as `.gitattributes`, `.travis.yml`, `.codeclimate.yml`, and package-specific options, such as `.jshintrc`, `gulpfile`, `.atom-build.yml` etc.

**Comment by jaydrue** [comment]
What if I don’t use a .git directory. Do I have to? Eventually I am going to need the editor to go with Android App Development (probably use Android Studios) and use Atom for prototyping or testing smaller pieces of the project.

Thanks for the help!



On 21 Sep 2017, at 19:31, Charlie Bouthoorn <notifications@github.com> wrote:

The .atom-build.yml file should be located in the root folder of your project. This is usually the folder that contains the .git directory (and the LICENSE and README.md file), configuration files such as .gitattributes, .travis.yml, .codeclimate.yml, and package-specific options, such as .jshintrc, gulpfile, .atom-build.yml etc.

**Comment by C-Bouthoorn** [comment]
There's no need to have a `.git` directory, but if you have one, that's probably the project root folder.

**Comment by noseglid** [comment]
Closing as question has been answered.
