### ISSUE TITLE
Please explain in the README how to get this linter look-and-feel

### ISSUE THREAD

**Issue by doudou** [noseglid/atom-build#545]
I just can't find what packages I should install to get the linter look and feel that you show in the README... It's not a bug per se, but it would really be helpful. What's you show there is so much better than what I am getting ...

**Comment by julian-poidevin** [comment]
Will also be interested. 😄

**Comment by idleberg** [comment]
The screenshot depicts [version 1.x](https://github.com/steelbrain/linter/tree/v1.11.23) of the linter plugin. Version 2 was released in 2017 and features a [new UI](https://github.com/steelbrain/linter-ui-default).

There are two options:

1. Install and use the old version, which is probably a bad idea (`apm install linter@1.11.23`)
2. Write (and publish?) your own UI based on the old design

**Comment by doudou** [comment]
Switched to VSCode a long time ago. I'll fix this (since the fix is "WONTFIX")
