### ISSUE TITLE
'"Gulp.cmd"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Hugaga** [noseglid/atom-build#552]
Hey!

First of all, thank you so much for making this package, it makes working so much easier!
I'm trying to get familiar with sass and gulp, and downloaded your package, but every time I hit f9 I get the message in the Title and a few other lines.

What might be the cause of this and do you know if it could be solved?

Thank you in advance,

**Comment by wiggisser** [comment]
I'm not entirely sure, what SASS and gulp have to do with this package but two points you could check: 

- There is an additional package `build-gulp` (https://atom.io/packages/build-gulp) for running gulp tasks with atom-build

- have you installed gulp globally (`npm install gulp --global`) and are you able to execute gulp from commandline?

**Comment by Hugaga** [comment]
You're absolutely right! I forgot to mention that I have installed build-gulp, but completely ignored the global gulp installation! I feel kinda stupid...

Thank you!

**Comment by noseglid** [comment]
Is this working for you now, @Hugaga?
