### ISSUE TITLE
Unable to execute: sass

### ISSUE THREAD

**Issue by borishere** [noseglid/atom-build#554]
Hi, 
Please help me build .scss files using `build-sass`. 
Some time ago I built it with no problems, don't know exactly why it stopped working now.
I get the following error:

Unable to execute: sass
Make sure cmd:'sass' and cwd:'C:\<path_to_folder_with_scss_file>' exists and have correct access permissions.
Binaries are found in these folders: C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\
Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\TortoiseSVN\bin;C:\Users
\User\AppData\Roaming\npm;C:\Users\User\AppData\Local\Android\Sdk\tools;C:\Users\User\AppData\Local\Android\Sdk\platform-tools;C:\Users\user\AppData\Local\atom\bin

**Comment by borishere** [comment]
Solved.

**Comment by noseglid** [comment]
If you don't mind, what did you do to resolve it? Might be useful for someone else experiencing the same or similar problem.

**Comment by borishere** [comment]
Seems that ruby was lost from my environment `PATH` variable.
I updated ruby, entered it in `PATH` variable and reinstalled `SASS`.
