### ISSUE TITLE
Unable to  parse targets from included makefile

### ISSUE THREAD

**Issue by swapnil823** [noseglid/atom-build#556]
All targets are specified in the included file but plugin is unable to find them.
Is there any way to specify targets manually?
```
CONCATENATE_USER_FILES = no
include ../Makefile/incino.mk

```

**Comment by noseglid** [comment]
This is really an issue [build-make](https://github.com/AtomBuild/atom-build-make). You need to enable `Target extraction with make` on that package for support with included files.
