### ISSUE TITLE
How to use a provider

### ISSUE THREAD

**Issue by aacirino** [noseglid/atom-build#558]
Hi, I am using meson build and ninja in my project. Being able to build it without leaving atom would be interesting. My problem is that I can't figure out where to put the ninja provider. The readme isn't clear on the directory were I must copy or link the `atom-build-ninja` provider.

**Comment by noseglid** [comment]
You should be able to simply install it (I'm guessing it's https://atom.io/packages/build-ninja ?).
It should automatically hook up and provide build targets.

**Comment by aacirino** [comment]
I didn't search the packages installer how I should, thanx
