### ISSUE TITLE
Can't build Rust (cargo) project.

### ISSUE THREAD

**Issue by JeromSar** [noseglid/atom-build#56]
Hello,

I'm getting the following error message when building a cargo project on Windows 7 x64:
 
![Build error](https://pravi.us/W9a)

cargo and rustc are both included in the %PATH% directory (they run fine from command prompt and git sh).

Any ideas what could be the problem?

**Comment by noseglid** [comment]
Did you try http://stackoverflow.com/questions/24027551/gulp-command-not-found-error-after-installing-gulp/24042936#24042936? You need to set it system wide and restart atom.

**Comment by JeromSar** [comment]
@noseglid Hey, thanks for the quick reply. I managed to get it working by adding the rust bin folder to the system-wide %PATH% directory.

This might be a point of improvement though, since Rust only adds itself to the user's %PATH% variable by default. Allowing builder to find binaries in the local environment might spare other users some work. :)

**Comment by noseglid** [comment]
Good that you got it to work.
I'm not sure we should modify how the system works too much. Maybe an instruction for people who doesn't get it to work, but I'm not sure I want to modify system behavior.
