### ISSUE TITLE
Possible to issue other gulp commands, such as "serve" or just "default"?

### ISSUE THREAD

**Issue by lombardi-gux** [noseglid/atom-build#59]
My projects all have a command "gulp serve" (sometimes aliases to simply "gulp") to build and run the project.

Would be great if I could invoke this from your plugin.

**Comment by noseglid** [comment]
You could achieve this by specifying a custom build. In this case you would write a file in you project root called `.atom-build.json`. It could look something like

```json
{
  "cmd": "gulp serve"
}
```

If simply `gulp` is sufficient, then you don't need to do any modifications at all. `atom-build` will invoke `gulp` when triggered if the project root contains a `package.json` with `engines` containing `node`.

**Comment by noseglid** [comment]
Closing this, if you require further assistance please re-open this issue.
