### ISSUE TITLE
Problem to make errorMatch work

### ISSUE THREAD

**Issue by mthcrts** [noseglid/atom-build#61]
Hello,

I'd like to open the source file in fault when an error occurred.
It does not work and I don't know how to check if my regexp matches nothing or wrong file names...
Please help!

Example of output:

    Executing with sh: ./waf  install
    Waf: Entering directory `/home/mc/dev/codeaster/src/build/release'
    [7558/7743] c: bibc/supervis/aster_core_module.c -> build/release/bibc/supervis/aster_core_module.c.1.o
    ../../bibc/supervis/aster_core_module.c: In function ‘cheksd_’:
    ../../bibc/supervis/aster_core_module.c:561:4: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘res’
        res = PyObject_CallMethod(get_sh_pymod(), "checksd", "s#s#", nomsd, lnom, typsd, ltyp);

Content of my `.atom-build.json`:

    {
      "cmd": "./waf",
      "args": ["install"],
      "sh": true,
      "cwd": "{PROJECT_PATH}",
      "env": {
      },
      "errorMatch": "^\\.\\./\\.\\./(?<file>.*.c):(?<line>\\d+):(?<col>\\d+):"
    }

When it will work I will send a PR for a `lib/tools/waf.js`.

Thanks in advance!

**Comment by sryze** [comment]
Perhaps it can't find the file because the path is not relative to the project directory?

**Comment by mthcrts** [comment]
The path is relative to the project directory :
- the source file is : `bibc/supervis/aster_core_module.c`
- the build directory is : `build/release/`, that's why the message starts with `../../bibc/xxx`.
Any idea?

**Comment by noseglid** [comment]
If you try and remove the circumflex (`^`), does it work then?

**Comment by mthcrts** [comment]
Yes, it does.

**Comment by noseglid** [comment]
So, does that solve your problem?

**Comment by mthcrts** [comment]
That's ok for me, you can close this issue.
But as the path starts at the beginning of the line, it should work with '`^`', it's curious.

**Comment by noseglid** [comment]
`atom-build` do not do multiline regex, so it's technically not the start of a string. the start of the string is `Waf: ...`. If the regex had the multiline option (`m`), then your regex would've worked. However, it should work the same for you even if you omit the circumflex.
