### ISSUE TITLE
Option to disable build panel

### ISSUE THREAD

**Issue by LKuechler** [noseglid/atom-build#62]
I have a build task that is finished really fast and runs on every save.
The only problem is that every time when i save the build panel pops up for a few seconds and blocks the view of the code.

Maybe the best way to implement this would be that the build panel only opens when there is a error.

**Comment by noseglid** [comment]
I understand what you mean. I think I might need to add a configuration variable, called `Show On Error` or something similar. If this is checked, all builds would be hidden until something actually went awry. Would that solve your issue?

**Comment by noseglid** [comment]
I have committed this, please test it out!

It will be in the next version (v0.30.0)

**Comment by LKuechler** [comment]
Works great.
Thanks
