### ISSUE TITLE
Prefixing the value of `cwd` to the file of matched errors

### ISSUE THREAD

**Issue by nikswamy** [noseglid/atom-build#63]
I am using an .atom-build.json that sets the `cwd` property ... it looks like this:

```
{
  "cmd": "fstar",
  "args": [ "{FILE_ACTIVE_NAME}" ],
  "cwd": "{FILE_ACTIVE_PATH}",
  "sh": false,
  "errorMatch": "(?<file>[^\\(]+.fst)\\((?<line>\\d+),(?<col>\\d+).*\\n"
}
```

The command I'm using, `fstar`, reports error locations relative to the working directory from which it isi executed, as usual.

However, this doesn't work well with atom-build, since it expects the matches `<file>` string to be relative to the root of the project. 

Is there a way to configure `atom-build` so that it uses the `cwd` value in `.atom-build.json` (if set) to be the base of any matched files in error messages.

**Comment by noseglid** [comment]
I see. I think it really should match the file relative to the specified `cwd`. If `cwd` is not specified it should be relative the root directory of the project. Thanks for reporting!

**Comment by noseglid** [comment]
I have fixed this on master. Please test it and see if it works for you!

It will be included in the next release (`v0.30.0`).

Thanks for reporting this!

**Comment by nikswamy** [comment]
Thanks for looking into this promptly. 
I tried your change, and it almost works ... but not quite. 

The problem is that it is not expanding variables that appear in the `cwd` field. 

Specifically, my `cwd` field is set to `"{FILE_ACTIVE_PATH}"`. So, your change causes the error jumping feature to go searching for  `{FILE_ACTIVE_PATH}/myfile.txt` ... which is bad, of course.

Can you expand variables before pre-pending to the path? 

Thanks!

**Comment by nikswamy** [comment]
This change does the trick:
At build.js line 181:
```
    atom.workspace.open(this.replace(this.cmd.cwd) + path.sep + this.match[0].file, {
```

At build.js line 198:
```
 atom.workspace.open(this.replace(this.cmd.cwd) + path.sep + this.match[0].file, {
```

**Comment by noseglid** [comment]
That is true! Excellent catch. Do you want to make a PR for that change, or should I just change it?

**Comment by nikswamy** [comment]
Please change yourself... Thanks!

Sent from my Windows Phone
________________________________

**Comment by noseglid** [comment]
This has been fixed on master. Would you mind testing it out?
