### ISSUE TITLE
Use makefile in subdirectory instead of project root

### ISSUE THREAD

**Issue by alshakh** [noseglid/atom-build#65]
Hello, I love this tool. I work with multiple components in one project, and I use multiple Makefiles in subdirectories of project. When I open the folder of the project, atom-build uses the makefile in project directory. Can I make it use the closest makefile to the ACTIVE_FILE?

**Comment by mthcrts** [comment]
With something like that:

    {
      "cwd": "cd {FILE_ACTIVE_PATH} && make"",
      ...

no?

**Comment by noseglid** [comment]
Almost, if you change `cwd` to `cmd` as key.

But I would do it like this:

```json
{
  "cmd": "make",
  "cwd": "{FILE_ACTIVE_PATH}"
}
```
