### ISSUE TITLE
Copy from build window

### ISSUE THREAD

**Issue by andschwa** [noseglid/atom-build#68]
Although I can select text, it does not seem possible to copy text output from the build window. It is not possible to bring up the context menu, and `Cmd-C` does not get the text onto the clipboard.

Is this fixable?

**Comment by andschwa** [comment]
Ugh totally not this extension's fault. They way Atom rebinds keys is strange. Still learning.

**Comment by andschwa** [comment]
If anyone else runs into this, I found the real cause was with [emacs-core-keys](https://github.com/mndrix/atom-emacs-core-keys/issues/2).

**Comment by noseglid** [comment]
Thanks for taking the time to report this!
