### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by efoster** [noseglid/atom-build#72]
I am probably doing something really dumb but I installed this package on Windows and I cannot get it to work. 

I have setup a custom build which I could not get to work and so then I copied one of the files from your test package (see below) and that does not work either.
```
{
  "cmd": "echo",
  "args": ["Hello"],
  "sh": false,
  "env": {}
}
```
All I seem to get when I run build is this error 
![build-error](https://cloud.githubusercontent.com/assets/2668115/7590447/801ffc78-f8c0-11e4-9d95-df7da28ee36d.png)

I have tried numerous permutations but I get the same thing each time

**Comment by noseglid** [comment]
I'm not very familiar with windows. But I'd assume that `echo` is not a command which can be used on windows?

**Comment by efoster** [comment]
I wish that were the case but unfortunately it does the same thing that it does on Linux/Unix. I tried a bunch of other commands such as `dir` (directory listing on Windows) and even `ls` (*nix equivalent).

Not that it probably matters much but the *real* thing I was trying to implement was this...
```
{
  "cmd": "sas.exe",
  "args": [ "-noautoexec", "-sysin '{FILE_ACTIVE}'"],
  "sh": false,
  "cwd": "{FILE_ACTIVE_PATH}",
  "env": {}
}
```
...so that I could kick off a job that executed my code (SAS - A statistical programming language similar to R). `sas.exe` is in my `PATH`. I get the same error as above
![build-error](https://cloud.githubusercontent.com/assets/2668115/7596974/be0c9c1c-f8e8-11e4-9841-7e3fadce3535.png)

**Comment by noseglid** [comment]
Does it work if you fully qualify the path to `sas.exe` ?

**Comment by efoster** [comment]
The fully qualified path to `sas.exe` is `C:\\Program Files\\SAS 94TS1M1\\SASFoundation\\9.4\\sas.exe` (backslahes have been escaped) but this did not work because there are spaces in the path. I tried quoting the value in the `cmd` property but got the same result.

I therefore switched to the short name version of the path (`C:\\PROGR~1\\SAS94~T1\\SASFoundation\\9.4\\sas.exe`) but this time I got the original "Unable to execute:..." message.

I tried changing the value of the `sh` property to the same result.

**Comment by noseglid** [comment]
There are [people who are running it on Windows](https://github.com/noseglid/atom-build/pull/7). I'm not very familiar with Windows though, so I am afraid I can not help you track down this issue very much. What you're doing looks like what I've seen other Windows users do and it looks okay. `sh` should be `false` in any way.

**Comment by efoster** [comment]
ok, so I am a [berk](http://www.oxforddictionaries.com/definition/english/berk).

The absolute path I wrote earlier was wrong - it should have been ` C:\\PROGRA~1\\SAS94T~1\\SASFoundation\\9.4\\sas.exe`.

This 'worked' in the sense that the executable was now found and run. However, I had issues the the arguements that were passed in how they were interpreted by SAS (I think this is a SAS problem and not a problem for your package). 

I changed my approach and instead wrote a basic Python script to make the call to SAS. The `.atom-build.json` file now references this script and passes the program I want to run to that script instead.

I guess you can close this now.

**Comment by noseglid** [comment]
Seems like a convoluted way, but whatever works, I guess. Good that you have something that will work.
