### ISSUE TITLE
Unhelpful JSON syntax error

### ISSUE THREAD

**Issue by srid** [noseglid/atom-build#73]
Not sure why I"m getting `/Users/srid/code/chronicle/.atom-build.json: Unexpected token }` (note the lack of line/column number info) when the below `.atom-build.json` looks fine to me:

```json
{
  "cmd": "make",
  "args": [ "compile" ],
  "sh": true,
  "cwd": "",
  "env": {
    "VARIABLE1": "VALUE1",
    "VARIABLE2": "VALUE2",
  },
  "errorMatch": "^regexp$"
}
```

**Comment by srid** [comment]
Trailing comma, sigh. Still, the JSON parser can be improved.

**Comment by noseglid** [comment]
Agreed. It's not very helpful. Unfortunately `node` does not provide any more information. What is written in the error message is the extent of nodejs debugging for JSON files. I'm sure there is a better JSON parser available in `npm`. I might just look into that.

**Comment by srid** [comment]
Nifty package. Random thought: can this be integrated with atom core? This way other packages (especially languages extensions) can provide their regexp for parsing error messages.
