### ISSUE TITLE
Unable To Execute Cargo

### ISSUE THREAD

**Issue by excaliburHisSheath** [noseglid/atom-build#75]
When I try to use atom-build with my rust project I get the following error message:

```
Executing: cargo  build
Unable to execute: cargo
```

I'm running windows 8.1 so I don't know if this is related to #74, but it looks like it could be a different issue.

**Comment by noseglid** [comment]
Do you have Cargo in the path?

**Comment by excaliburHisSheath** [comment]
I had it in my user path but not in my system path. When I copied it over to my system path and restarted Atom build started working again.

**Comment by armink** [comment]
I also have this problem.
