### ISSUE TITLE
Option to open build panel to the right / left / top / bottom [ENHANCEMENT/Question]

### ISSUE THREAD

**Issue by Zilarrezko** [noseglid/atom-build#83]
Been looking through the source code, since I wanted to make the changes myself in a pull and do a merge. I've never made a package before, I still would like to give it a shot (since it seems simple). But I have no idea how to implement into atom for testing and then how to merge.

I would start with a fork I think.
And to add to atom through the fork, I do the: "apm install & apm link" then it would load it into atom?
Then I could do the changes.
then how would I merge?

Noob questions, but I want some experience making packages for atom, and more experience with github.

**Comment by noseglid** [comment]
Hey,

I think you got most of it down! The best way is to simply get started! I use the Atom editor to develop the build package. If the change involves a lot of work, it's never bad to check with the maintainers if they would accept a PR with the changes you intend to make. If not, you save yourself a lot of trouble (and could consider running a separate fork with your changes).

Just as you said, create a fork, clone it into your environment, install dependencies with `apm install` and link it with `apm link`. Now if you reload Atom (`cmd-alt-ctrl-L` or open the command panel and type `reload`, or just restart Atom) it should have loaded the newly cloned build package.

Now you just make the changes and reload Atom to test them out.

Make sure to add some Tests (specs) so whatever changes you make are guaranteed to work as the project evolves.

To open a Pull request, [follow this guide](https://help.github.com/articles/creating-a-pull-request/).

I will then review it and hopefully merge it! Good luck!

**Comment by Zilarrezko** [comment]
Alright. I've taken a bit of time to look through some stuff and some of the atom api. And already committed the implementation of the panel orientation, though I want to fix some of the bugs and the like.

I've tried to keep with your camelCasingScheme, and in all to make it look like your work.

I do have another question, how are you setting the height of the window? I'm currently trying to make the left and right windows conform to your monocle and minimized height properties (was going to change height to length).

**Comment by noseglid** [comment]
I will close this in preferrence for the PR you recently opened.
