### ISSUE TITLE
Unsaved Changes dialog not dismissed

### ISSUE THREAD

**Issue by pmcconnell** [noseglid/atom-build#85]
If the build process is started with unsaved files the unsaved file dialog is shown asking if you want to build with or without saving. Selecting any option will proceed with the build but the dialog is not dismissed.

Occurring in 0.35
OS X

**Comment by noseglid** [comment]
Could it be that you pressed `cmd-alt-b` several times before noticing the dialog? I've noticed that it attaches multiple dialogs even if one exists. I'm planning on correcting this soonish.

**Comment by pmcconnell** [comment]
> On May 26, 2015, at 3:07 PM, Alexander Olsson <notifications@github.com> wrote:
> 
> Could it be that you pressed cmd-alt-b several times before noticing the dialog? I've noticed that it attaches multiple dialogs even if one exists. I'm planning on correcting this soonish.
> 
I have been seeing this issue all day. I did go back and try to be very careful to only press  cmd-alt-b once and I still see the dialog after the build starts.

Thanks for looking into it and the great plug-in.

**Comment by noseglid** [comment]
Is this still an issue? What version of Atom do you use? What version of OS X? Could you detail (possibly through a screencast) what you're doing. I've been trying to reproduce this but I can't get it to happen.
