### ISSUE TITLE
Trigger build on specific files (extensions)

### ISSUE THREAD

**Issue by tomitrescak** [noseglid/atom-build#86]
First, let me thank you for this awesome plugin.
I wanted to ask, if you consider possibility of specifying a filter on files which trigger build process on save? I have many various files in my project and only selected (*.ts) shall trigger the build process which is in my case quite lengthy. So, as I am saving modification on html templates, I do not want the build process to trigger. 

Thanks!

**Comment by noseglid** [comment]
I'm glad you're making use of it!

So if I understand you correctly, this is only an issue when `Automatically build on save` is set, and you want to provide a whitelist filter (perhaps a regex) which allows you to specify which files should trigger the build?

**Comment by tomitrescak** [comment]
That is totally correct. Thanks!!

**Comment by jhasse** [comment]
Shouldn't this be the job of the build system? Checking if a rebuild is needed because an important file has changed?

**Comment by noseglid** [comment]
as @jhasse suggest, while this may be a useful feature. I don't think it's in the scope of this plugin. For instance `gulp` can `watch` files  (such as `*.ts`) and rebuild only when those are changed.
