### ISSUE TITLE
Automatically error match upon build error

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#87]
When a build fails, the first thing I do is pressing Ctrl+Alt+h. Would be great if there was an option (or the default - I wouldn't mind) to always scroll to the first error when a build fails.

**Comment by noseglid** [comment]
This is a duplicate of #49

**Comment by jhasse** [comment]
No, I'm not talking about the build panel ;) Sorry if my English isn't that good to explain what I mean.

**Comment by noseglid** [comment]
Yes, that issue also is in regard to the build panel. The TextEditor already scrolls to the code.

**Comment by jhasse** [comment]
Automatically when my build fails? Without pressing Ctrl+Alt+h? It doesn't for me.

**Comment by noseglid** [comment]
Now I see, you want it to autmatically jump to the error everytime it fails to build? That's not a bad idea and is indeed not a duplicate. I'll reopen this.

**Comment by jhasse** [comment]
Exactly! Thanks for reopining and sorry for me being not clear enough about what I mean.

**Comment by 5n8ke** [comment]
Added this feature in #90 
Default config is set to false
