### ISSUE TITLE
Build only seeing if last command produced an error.

### ISSUE THREAD

**Issue by Zilarrezko** [noseglid/atom-build#92]
Hate to throw a stone in already troubled water. Looks like you're getting flooded with a lot of issues on the issues board.

I've noticed that when going through the build. I think it only catches an error from the last command call.

For example, I have my build batch file that gets called from atom-build, and then  compile. Since it's the last thing I do it catches the error.

Alright. That's awesome. Though, if I wanted to after the compile, go back or do other stuff, and my compile failed, it doesn't catch any errors if there are any. Just says build finished as if it succeeded.
The thing is in my particular case, the command I use to compile, is used twice, once to make into a dll for the program to link to, and the other one to make the executable to run. So if the first command fails to compile, and the last one is doesn't fail. It says build finished.

Edit:
As a test I tried a work around that involves me, instead of having my build batch file as the cmd file pointed to by .atom-build.json. To instead run a stub batch file that calls my build batch file. Since the call was the last thing in the file that atom-build calls, to catch all the errors. However it didn't work.

**Comment by 5n8ke** [comment]
A build is only registered as failed if the used command has a nonzero return value. The package cannot inspect return values of any functions inside the script but only the return value of the script itself. In scripting languages the return value of the whole script equals always the one of the last executed command.

So you have to set up your build script accordingly.
In Linux environments there is the ```set -e``` command to stop a script immediately when an error occurs thus making the command the last one executed and return a nonzero value.
In Windows it is not that easy, but you can do something like ```command || exit 1``` to return on errors.

**Comment by Zilarrezko** [comment]
Seems like that does it, <command> || exit 1. Beautiful.

Thanks.

**Comment by noseglid** [comment]
What @5n8ke said is completely correct. There's no way for the package to inspect the command you choose to execute and actually realize it is multiple commands.

However, never apologize for reporting issues. I want to know about them, otherwise people will just be irritated at a seemingly buggy package. Reporting an issue is contributing, the same as submitting a pull request is!
