### ISSUE TITLE
Should detect absolute path

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#94]
If a file path starts with `/` it should be treated as an absolute one. At the moment I'm getting:

```
Matched file does not exist: /home/jhasse/git/gtoc8//usr/include/boost/test/floating_point_comparison.hpp
```

**Comment by noseglid** [comment]
You must use `absFile` in your `errorMatch` regex instead to indicate that the matched file is absolute.

**Comment by jhasse** [comment]
But the file path is only absolute *sometimes*. So I would need to check for the leading / using the regexp, but wouldn't it be easier if atom-build does this automatically?

**Comment by noseglid** [comment]
Well, `/` is only true in unix environment. Otherwise it is `X:\` which might be a file in a unix environment. There's no way for the package to reliably determine if a file is absolute or not without external input.

**Comment by noseglid** [comment]
Unless, of course, it checked which environment it was running in and determined the initial character sequence for an absolute file...

**Comment by jhasse** [comment]
This seems to be already implemented in Node.js: https://nodejs.org/api/fs.html#fs_fs_realpath_path_cache_callback
