### ISSUE TITLE
Gulp tasks not being found

### ISSUE THREAD

**Issue by Mesoptier** [noseglid/atom-build#98]
I have a gulpfile.js in the correct location with two tasks. The Ctrl-Alt-T view, however, tells me no build configurations can be found.

After some console.logging I found the following: My gulpfile.js is detected, so `isEligable` passes and it is being required. However, I placed `console.log({ tasks: Object.keys(gulp.tasks) });` at the end of my gulpfile.js and in gulp-parser-task.js right after the require, which logged 2 and 0 tasks respectively.

My best bet is that either gulp has weird scoping issues, or something is wrong with the Task stuff atom-build does.

**Comment by noseglid** [comment]
What OS are you on? What version of Atom?

There are [tests which cover this functionality](https://github.com/noseglid/atom-build/blob/master/spec/build-targets-spec.js#L91-L115). Do they work in your environment?

**Comment by phaux** [comment]
Same here. Only the custom `.atom-build.json` task works. Neither `package.json` or `gulpfile.coffee` is detected. :disappointed:

**Comment by noseglid** [comment]
gupfile.coffee support was introduces in c2f6e95c4945dee832a176f98610409127f3d60c, which is not part of a release yet. Please try again on master (or wait for v0.40.0 which shouldn't be too far off).

**Comment by phaux** [comment]
I made it work with `package.json` target (I was missing the `"engines"` field), but now it only runs `npm install`, which only invokes the `"postinstall"` script.

Shouldn't it instead run `npm test` or something that actually triggers all builds? `"postinstall"` is used only for compiling native libraries.

In summary, more sane behaviour would be to:

- default to node when `"engines"` field is missing
- run `npm test` or both `npm install && npm test` upon build

**Comment by noseglid** [comment]
Well, test is one thing, build is another. I think what `build` is currently doing when it finds a  `package.json` is what most would expect. If there is anything else that should be done as part of the build, `postinstall` can be used as you so accutely pointed out.

I'm not sure what you mean with "default to `node`" ? Node wouldn't be able to do anything with the package.json file.

And as I said in previous comment. `gulpfile.coffee` will be supported in next version.
