### ISSUE TITLE
how to run build?

### ISSUE THREAD

**Issue by Marek95** [noseglid/atom-build#99]
hi,
I am new to this i don’t understand some things

but I would like to build and run pascal code from Atom. I made it work with sublime text...

in terminal it works like this with freepascal compiler:
from project folder you just use command
```
fpc program.pas
```

and to run 
```
./program
```

so I have created .atom-build.json file in project folder with this
```
{
  "cmd": "fpc {FILE_ACTIVE}"
}
```
this works good to compile code

so my question is there any way to run command to run compiled with some keyboard shortcut?

thanks!

**Comment by noseglid** [comment]
`build` is meant to build your project, not run it. However, you could build your cmd like `fpc {FILE_ACTIVE} && ./program`. This will run the program. It will not attach any tty (stdin, stdout or stderr) so it is likely that it will not work as it does if you run it by yourself in the terminal.
